- .github/workflows/boolean_benchmark.yml
- .github/workflows/shortint_benchmark.yml
- ci/benchmark_parser.py
- ci/slab.toml
These workflows are meant to be triggered by Slab CI bot server.
This need to be merged into main before able to test and debug the workflows.
> chore(ci): add benchmark workflow for boolean and shortint

- README.md
twitter API closed to 3rd party
see https://github.com/badges/shields/issues/8837
> chore(doc): update README twitter badge

- tfhe/src/shortint/engine/mod.rs
- tfhe/src/shortint/engine/server_side/mod.rs
- tfhe/src/shortint/engine/wopbs/mod.rs
> shortint: Fix KeyId  & refactor the BTreeMap of buffers

- tfhe/benches/shortint/bench.rs
The following operations have been added:
* unchecked_neg
* unchecked_div
* unchecked_greater
* unchecked_less
* unchecked_equal
* unchecked_scalar_div
* unchecked_scalar_mod
* unchecked_scalar_left_shift
* unchecked_scalar_right_shift
> chore(ci): benchmark more operations in shortint

- tfhe/src/core_crypto/algorithms/slice_algorithms.rs
- tfhe/src/shortint/server_key/mod.rs
> chore(tfhe): fix typos

- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- Makefile
- ci/slab.toml
- docker/Dockerfile.wasm_tests
- scripts/integer-tests.sh
- scripts/shortint-tests.sh
- use a 128 vcpu instance
- update script to have a no compromise test run
- update Makefile to be able to run the "no compromise" CI mode
> chore(ci): CI at the speed of ligth

- tfhe/src/integer/server_key/radix/neg.rs
- tfhe/src/shortint/engine/server_side/mul.rs
- tfhe/src/shortint/engine/server_side/neg.rs
- tfhe/src/shortint/engine/server_side/sub.rs
- tfhe/src/shortint/server_key/neg.rs
- tfhe/src/shortint/server_key/sub.rs
closes https://github.com/zama-ai/tfhe-rs-internal/issues/14
> refactor(tfhe): rename with_z function to with_correcting_term

- scripts/integer-tests.sh
- tfhe/src/high_level_api/integers/server_key.rs
- tfhe/src/shortint/engine/wopbs/mod.rs
closes https://github.com/zama-ai/tfhe-rs-internal/issues/92
> fix(integer): fix radix wopbs table size issue

- tfhe/docs/high_level_api/tutorial.md
cherry-pick from release/0.2.x
> chore(doc): fix dead links

- README.md
- tfhe/docs/high_level_api/serialization.md
- tfhe/docs/high_level_api/tutorial.md
cherry-picked from release/0.2.x
> chore(doc): fix TOML

- tfhe/src/integer/server_key/radix_parallel/tests.rs
did not have time to add the test in the PR with the related fix
> chore(integer): add non regression test for scalar mul fix

- tfhe/c_api_tests/test_high_level_128_bits.c
- tfhe/c_api_tests/test_high_level_256_bits.c
- tfhe/c_api_tests/test_high_level_boolean.c
- tfhe/src/c_api/high_level_api/booleans.rs
- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/c_api/high_level_api/utils.rs
- tfhe/src/high_level_api/booleans/tests.rs
- tfhe/src/high_level_api/integers/server_key.rs
- tfhe/src/high_level_api/integers/tests.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/high_level_api/shortints/tests.rs
- tfhe/src/high_level_api/shortints/types/base.rs
- tfhe/src/integer/encryption.rs
- tfhe/src/integer/server_key/radix/mod.rs
closes zama-ai/tfhe-rs-internal#93
> Hlapi trivial encrypts

- .github/workflows/make_release.yml
- Makefile
Backport from main to be able to publish release in this release branch.
> chore(ci): publish tfhe release on-demand

- tfhe/Cargo.toml
- tfhe/docs/core_crypto/tutorial.md
- tfhe/docs/getting_started/installation.md
- tfhe/docs/high_level_api/serialization.md
- tfhe/docs/high_level_api/tutorial.md
to be merged right before releasing (but not before then)
> chore(tfhe): bump version to 0.2.3

- tfhe/src/integer/ciphertext/mod.rs
- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/mul.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
- tfhe/src/shortint/ciphertext/mod.rs
cherry-pick you know the drill
> refactor(integer): remove usage of Mutex for determinism

- tfhe/Cargo.toml
- tfhe/docs/core_crypto/tutorial.md
- tfhe/docs/getting_started/installation.md
- tfhe/docs/high_level_api/serialization.md
- tfhe/docs/high_level_api/tutorial.md
> chore(tfhe): bump version to 0.3.0

- tfhe/src/core_crypto/algorithms/lwe_encryption.rs
closes https://github.com/zama-ai/tfhe-rs-internal/issues/88
> chore(core): avoid having branching depending on secret values in PKE

- tfhe/src/integer/server_key/radix_parallel/mul.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
This improves the mul and scalar_mul algorithms
to be faster
The improvement is made within the code
that was responsible for summing up all
the terms by making better use of carries
and avoiding uncessary propagations.
The scalar mul forwards the call to a right shift
when the scalar is a power of two as it just cost one PBS so it will always be faster.
For 64-bits, target-cpu=native + avx512:
- mul before: 3.4s
- mul after: 900ms
> feat(integer): improve mul and scalar mul

- scripts/integer-tests.sh
Reduce number of test-threads being spawned
to reduce propability if tests getting killed due
to out of memory
> ci(integer): reduce number of test-threads

- .github/workflows/aws_tfhe_multi_bit_tests.yml
required for https://github.com/zama-ai/tfhe-rs/pull/291
> chore(ci): add multibit workflow

- tfhe/src/integer/u256.rs
Address comments made in https://github.com/zama-ai/tfhe-rs/pull/306#discussion_r1213409221
> fix(u256): align with rust for shift behaviours

- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/sub.rs
> Improve default sub

- .github/workflows/aws_tfhe_multi_bit_tests.yml
- .github/workflows/integer_benchmark.yml
- Makefile
- ci/parse_integer_benches_to_csv.py
- will simplify "just to see" benchmarks output parsing to share when iterating on performance work
> chore(ci): add a parser to output csv files for integer benchmarks

- tfhe/docs/integer/operations.md
- tfhe/src/core_crypto/commons/numeric/unsigned.rs
- tfhe/src/integer/block_decomposition.rs
- tfhe/src/integer/server_key/radix/scalar_mul.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
This makes the scalar_mul family of operation
accepts any scalar of type T that implements
the UnsignedInteger traits.
This unlocks scalar_multiplication with
scalar being a u128.
> feat(integer): scalar_mul generic over UnsignedInteger

- tfhe/src/c_api/core_crypto/mod.rs
- tfhe/src/c_api/mod.rs
- tfhe/src/core_crypto/entities/ggsw_ciphertext_list.rs
- tfhe/src/core_crypto/entities/lwe_bootstrap_key.rs
- tfhe/src/core_crypto/entities/lwe_multi_bit_bootstrap_key.rs
@agnesLeroy no C header as discussed with @tmontaigu you will need to incorporate a build step for the C API for TFHE-rs, if you need infos on feature configs let us know !
> Am/c api/multi bit keygen

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/trigger_aws_tests_on_pr.yml
- Makefile
- ci/slab.toml
- scripts/integer-tests.sh
- scripts/shortint-tests.sh
- tfhe/src/integer/server_key/radix_parallel/tests.rs
This is done to get quick feedback to developpers in a Pull Request.
It tests shorint level with only three sets of parameters. Integer level is tested with only the default operations with two sets of parameters.
This profile will be automatically triggered on each push in a pull request.
Conversely the full suite of test will also be triggered automatically but once the review is approved.
> chore(ci): create fast feedback unit test profile

- .github/workflows/boolean_benchmark.yml
- .github/workflows/integer_benchmark.yml
- .github/workflows/pbs_benchmark.yml
- .github/workflows/shortint_benchmark.yml
- .github/workflows/wasm_client_benchmark.yml
resolves zama-ai/tfhe-rs-internal#155
> chore(ci): notify slack channel in case of benchmarks failure

- tfhe/src/shortint/key_switching_key/mod.rs
fixing the doctest of the shortint key switching file
> fix(shortint): key switching key doctests

- tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
- tfhe/src/core_crypto/entities/polynomial.rs
- add indexing and iteration primitives
> chore(core): remove Deref and DerefMut for Polynomial

- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/high_level_api/integers/tests.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/high_level_api/prelude.rs
- tfhe/src/high_level_api/traits.rs
To keep things easy we have to drop the part
where the macro generated the docs.
> feat(hlapi): bind shift by encrypted amount

- tfhe/Cargo.toml
> chore(tfhe): remove wildcard deps

- tfhe/src/integer/block_decomposition.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_bitwise_op.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
- tfhe/src/shortint/engine/server_side/mod.rs
- tfhe/src/shortint/engine/server_side/scalar_bitwise_op.rs
- tfhe/src/shortint/server_key/mod.rs
- tfhe/src/shortint/server_key/scalar_bitwise_op.rs
- tfhe/src/shortint/server_key/tests.rs
Nothing much interesting in terms of performance,
we only use the fact that we can 'inspect' the scalar to avoid unnecessary work.
Fixes https://github.com/zama-ai/tfhe-rs/issues/4
> feat(integer): add scalar bitwise operations

- tfhe/src/integer/server_key/radix_parallel/add.rs
Should fix https://github.com/zama-ai/tfhe-rs-internal/issues/167
> fix(integer): fix strict assert in add_paralellized

- tfhe/examples/utilities/generates_test_keys.rs
- tfhe/src/integer/server_key/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
- tfhe/src/shortint/engine/server_side/mod.rs
- tfhe/src/shortint/engine/wopbs/mod.rs
- tfhe/src/shortint/parameters/mod.rs
- tfhe/src/shortint/server_key/compressed.rs
- tfhe/src/shortint/server_key/mod.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/168
Add the possibility to change the behavior of PBS in terms of determinism (if the PBS has a deterministic and non deterministic version)
> feat(multibit): give the possibility to select deterministic execution

- tfhe/src/c_api/high_level_api/config.rs
- tfhe/src/high_level_api/config.rs
- tfhe/src/high_level_api/integers/keys.rs
- tfhe/src/high_level_api/integers/tests.rs
> fea(hlapi): allow use of multibit for integers

- tfhe/src/core_crypto/commons/numeric/unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/mul.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
It is an implementation of the paper
[Division by Invariant Integers using
Multiplication](https://gmplib.org/~tege/divcnst-pldi94.pdf)
> feat(integer): add scalar division/remainder

- tfhe/src/integer/u256.rs
There was a bug in to_be_bytes_slice, it was missing a `slice.reverse()` (from_be_bytes correctly has it)
The from/to functions have been refactored to used from_be_bytes / to_be_bytes, etc from the stdlib to only have one layer of endianess to manage.
The test value used did not catch that so we change the value used to expose the problem.
> fix(integer): fix U256::copy_to_be_byte_slice

- tfhe/src/integer/server_key/mod.rs
Expose `ScalarMultiplier` and `TwosComplementNegation`, should fix #445 
> feat(integer): expose scalar mul and sub trait

- tfhe/docs/fine_grained_api/integer/operations.md
- tfhe/docs/fine_grained_api/shortint/operations.md
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/196
> chore(docs): add remarks on smart operations taking mutable inputs

- tfhe/benches/integer/bench.rs
- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/high_level_api/integers/tests.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/integer/ciphertext/mod.rs
- tfhe/src/integer/server_key/comparator.rs
- tfhe/src/integer/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix/scalar_mul.rs
- tfhe/src/integer/server_key/radix_parallel/cmux.rs
- tfhe/src/integer/server_key/radix_parallel/div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/mul.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
- tfhe/src/shortint/ciphertext/mod.rs
- tfhe/src/shortint/engine/server_side/mod.rs
- tfhe/src/shortint/engine/server_side/mul.rs
> if_then_else

- .github/workflows/parameters_check.yml
- tfhe/examples/utilities/params_to_file.rs
This PR also ensure that the security check will be run on each push on `main` regardless of the modifications of parameters files.
> Add PBS_KS parameters to security check

- .config/nextest.toml
- scripts/integer-tests.sh
Fixes https://github.com/zama-ai/tfhe-rs-internal/issues/149
> chore(ci): remove ability for tests to be retried

- tfhe/src/integer/wopbs/mod.rs
- tfhe/src/shortint/engine/wopbs/mod.rs
- tfhe/src/shortint/wopbs/mod.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/218
A more sane approach to make it easier to work with the higher level APIs wop luts
> chore(wopbs): rework the inner part of WopLUTBase to be easier to use

- tfhe/src/integer/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
> fix(integer): make trim_radix_msb handle dirty inputs

- tfhe/src/core_crypto/algorithms/lwe_keyswitch.rs
- tfhe/src/core_crypto/algorithms/lwe_private_functional_packing_keyswitch.rs
- tfhe/src/core_crypto/algorithms/misc.rs
- tfhe/src/core_crypto/algorithms/test/lwe_keyswitch.rs
- tfhe/src/core_crypto/algorithms/test/lwe_private_functional_packing_keyswitch.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- tfhe/src/core_crypto/commons/numeric/unsigned.rs
- tfhe/src/core_crypto/entities/lwe_keyswitch_key.rs
- tfhe/src/core_crypto/entities/lwe_private_functional_packing_keyswitch_key.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/mod.rs
Parallel version of the keyswitching algorithms have been added
> feat(core): add parallel LWE PFPKS and LWE KS

- .github/workflows/code_coverage.yml
- .gitignore
- Makefile
- tfhe/Cargo.toml
- tfhe/examples/utilities/generates_test_keys.rs
- tfhe/src/boolean/parameters/mod.rs
- tfhe/src/keycache/mod.rs
- tfhe/src/shortint/key_switching_key/test.rs
- tfhe/src/shortint/keycache.rs
- tfhe/src/shortint/server_key/tests/shortint.rs
- tfhe/src/shortint/server_key/tests/shortint_compact_pk.rs
- tfhe/src/shortint/wopbs/test.rs
This PR, once completed, will lead to test coverage implementation for the other layers.
To do before merging:
> Add test coverage for shortint layer

- .github/workflows/code_coverage.yml
- Makefile
- tfhe/examples/utilities/generates_test_keys.rs
- tfhe/src/boolean/keycache.rs
- tfhe/src/boolean/mod.rs
- tfhe/src/boolean/parameters/mod.rs
- tfhe/src/boolean/server_key/tests.rs
Resolves: zama-ai/tfhe-rs-internal#232
> chore(ci): add boolean layer to code coverage

- tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- tfhe/src/core_crypto/commons/ciphertext_modulus.rs
As discussed, get around the non const unwrap :)
> chore(core): remove unsafe new_unchecked on CiphertextModulus

- tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
- tfhe/src/core_crypto/fft_impl/fft64/math/fft/x86.rs
waiting for bench results
EDIT:
benches (small keys)
benches (large keys)
> feat(core): replace unsafe simd intrinsics

- tfhe/src/boolean/engine/bootstrapping.rs
- tfhe/src/core_crypto/algorithms/lwe_bootstrap_key_conversion.rs
- tfhe/src/core_crypto/algorithms/lwe_multi_bit_bootstrap_key_conversion.rs
- tfhe/src/core_crypto/algorithms/lwe_multi_bit_bootstrap_key_generation.rs
- tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/commons/numeric/mod.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/bootstrap.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
- tfhe/src/core_crypto/fft_impl/fft64/math/fft/mod.rs
- tfhe/src/shortint/engine/server_side/mod.rs
- tfhe/src/shortint/engine/wopbs/mod.rs
- tfhe/src/shortint/server_key/mod.rs
Add parallel bootstrap key conversion (standard -> fft)
Running a benchmark could be useful
Edit by @IceTDrinker :
closes https://github.com/zama-ai/tfhe-rs-internal/issues/210
> feat(core): add par_fill_forward_fourier on bsk

- tfhe/src/core_crypto/algorithms/glwe_linear_algebra.rs
- tfhe/src/core_crypto/algorithms/mod.rs
- tfhe/src/core_crypto/algorithms/slice_algorithms.rs
- tfhe/src/core_crypto/algorithms/test/glwe_linear_algebra.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- tfhe/src/core_crypto/entities/cleartext.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/33
- add appropriate tests and doctest
> feat(core): add GLWE linear algebra primitives

- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/shift.rs
avoid UnsafeCell in high level code by using parallel iterators instead
> fix(integer): replace unnecessary unsafe code in integer shift/add

- apps/trivium/Cargo.toml
- concrete-csprng/Cargo.toml
- tasks/Cargo.toml
- tfhe/Cargo.toml
> chore(deps): update cargo dependencies

- tfhe/src/core_crypto/algorithms/glwe_sample_extraction.rs
- tfhe/src/core_crypto/algorithms/test/glwe_sample_extraction.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- allows to quickly extract all coefficients packed in a GLWE cipehrtext
> feat(core): add parallel variant of extract_lwe_sample_from_glwe

- tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
> chore(integer): add default signed bitand/or/xor tests

- tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/bootstrap.rs
improves pbs performance by 6-8% on my laptop and desktop. waiting for aws bench results.
EDIT: bench results
> feat(core): optimize monic polynomial operations in pbs

- .github/workflows/boolean_benchmark.yml
- .github/workflows/integer_full_benchmark.yml
- .github/workflows/pbs_benchmark.yml
- .github/workflows/shortint_full_benchmark.yml
- .github/workflows/start_full_benchmarks.yml
- .github/workflows/wasm_client_benchmark.yml
- tfhe/benches/integer/bench.rs
- tfhe/benches/integer/signed_bench.rs
- tfhe/src/integer/server_key/radix_parallel/abs.rs
- tfhe/src/integer/server_key/radix_parallel/div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
Could you tell me if there are some benchmarks to comment out ?
Resolves: zama-ai/tfhe-rs-internal#224
> chore(bench): add missing unsigned integer operations

- tfhe/src/integer/client_key/radix.rs
- tfhe/src/integer/mod.rs
- tfhe/src/integer/server_key/mod.rs
- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
This is a first step, a second step would be
to plug the non parallel radix tests so that
they are testing the same things.
> chore(integer): make tests work with different ServerKey

- tfhe/src/integer/server_key/radix_parallel/div_mod.rs
The quotient was slowly computed by
getting a resut bit, shifting it to its position then adding it to a quotient block, i.e quotient += bit << pos;
This meant that the output quotient was noisy, too noisy for parameters like param_message_4_carry_4, and so the signed division would then negate and cmux this quotient and due to the high noise, some computations would fail, on param_message_4_carry_4.
To fix this we clean the quotient's noise before returning it.
> fix(integer): clean output quotient of division

- tfhe/js_on_wasm_tests/test-hlapi-signed.js
- tfhe/js_on_wasm_tests/test-hlapi-unsigned.js
- tfhe/src/high_level_api/integers/client_key.rs
- tfhe/src/integer/public_key/standard.rs
- tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
> feat(wasm): add FheInt support

- tfhe/c_api_tests/test_high_level_256_bits.c
- tfhe/c_api_tests/test_high_level_custom_integers.c
- tfhe/src/c_api/high_level_api/i128.rs
- tfhe/src/c_api/high_level_api/i256.rs
- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/c_api/high_level_api/mod.rs
- tfhe/src/c_api/high_level_api/utils.rs
> feat(hlapi): add C API support for FheInt

- tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
- initial work done in https://github.com/zama-ai/tfhe-rs/pull/394
- useful reworks of the tests have been waiting in that PR, this is to have those tests while NTT usage gets validated
co-authored-by: sarah-ek
> test(core): use polynomial tests from NTT PR

- tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
> chore(integer): add tests for default signed rotations/shifts

- tfhe/src/integer/server_key/crt/mul_crt.rs
- tfhe/src/integer/server_key/crt/tests.rs
- tfhe/src/integer/server_key/crt_parallel/add_crt.rs
- tfhe/src/integer/server_key/crt_parallel/mod.rs
- tfhe/src/integer/server_key/crt_parallel/mul_crt.rs
- tfhe/src/integer/server_key/crt_parallel/tests.rs
- add non reg test for 32 bits mul with 5_1 parameters
> fix(crt): fix mul for non symmetrical parameters

- tfhe/src/shortint/server_key/mod.rs
Fixes https://github.com/zama-ai/tfhe-rs-internal/issues/46
> chore(doc): replace some ^ which could be interpreted as xor not pow

- tfhe/src/integer/server_key/radix_parallel/mul.rs
- currently the filter only applied to the RHS but LHS can also benefit from the filter
> feat(integer): better handle trivial 0 blocks from LHS

- tfhe/src/integer/server_key/crt/scalar_mul_crt.rs
- tfhe/src/integer/server_key/crt/scalar_sub_crt.rs
- tfhe/src/integer/server_key/crt/tests.rs
- tfhe/src/integer/server_key/crt_parallel/scalar_mul_crt.rs
- tfhe/src/integer/server_key/crt_parallel/scalar_sub_crt.rs
- tfhe/src/integer/server_key/crt_parallel/tests.rs
- tfhe/src/shortint/engine/server_side/mul.rs
- tfhe/src/shortint/engine/server_side/scalar_add.rs
- tfhe/src/shortint/engine/server_side/scalar_mul.rs
- tfhe/src/shortint/engine/server_side/scalar_sub.rs
- tfhe/src/shortint/server_key/scalar_add.rs
- tfhe/src/shortint/server_key/scalar_mul.rs
- tfhe/src/shortint/server_key/scalar_sub.rs
- remove buggy unchecked_scalar_add_assign and replace by the proper implementation which had a different name
removed an API entry point which was not required
> chore(integer): add crt 32 bits tests with 5_1 params

- .github/workflows/aws_tfhe_tests.yml
This workflow would run once a Pull Request is approved by a reviewer.
> chore(ci): test examples and apps in the ci

- tfhe/src/core_crypto/entities/lwe_ciphertext.rs
- tfhe/src/core_crypto/entities/lwe_compact_ciphertext_list.rs
- tfhe/src/core_crypto/entities/seeded_lwe_ciphertext.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/high_level_api/integers/types/compact.rs
- tfhe/src/high_level_api/integers/types/compressed.rs
Follow up of 380ee5298660d68f69888f16e12bfc97fa08856f
> test(hlapi): test base and compressed integer conformance

- tfhe/src/high_level_api/integers/mod.rs
- tfhe/src/high_level_api/integers/parameters.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/high_level_api/integers/types/compact.rs
- tfhe/src/high_level_api/integers/types/compressed.rs
- tfhe/src/high_level_api/integers/types/static_.rs
- tfhe/src/high_level_api/internal_traits.rs
Have GenericInteger be generic over the `Id` directly and not some `P` (Parameters) from which we get the `Id`
> Generic int over Id

- tfhe/src/core_crypto/algorithms/misc.rs
- tfhe/src/core_crypto/algorithms/test/ggsw_encryption.rs
- tfhe/src/core_crypto/algorithms/test/glwe_encryption.rs
- tfhe/src/core_crypto/algorithms/test/glwe_linear_algebra.rs
- tfhe/src/core_crypto/algorithms/test/glwe_sample_extraction.rs
- tfhe/src/core_crypto/algorithms/test/lwe_compact_public_key_generation.rs
- tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
- tfhe/src/core_crypto/algorithms/test/lwe_keyswitch.rs
- tfhe/src/core_crypto/algorithms/test/lwe_keyswitch_key_generation.rs
- tfhe/src/core_crypto/algorithms/test/lwe_linear_algebra.rs
- tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/algorithms/test/lwe_packing_keyswitch.rs
- tfhe/src/core_crypto/algorithms/test/lwe_packing_keyswitch_key_generation.rs
- tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
- tfhe/src/core_crypto/commons/generators/encryption/mod.rs
- tfhe/src/core_crypto/commons/generators/encryption/noise_random_generator.rs
- tfhe/src/core_crypto/commons/math/random/gaussian.rs
- tfhe/src/core_crypto/commons/math/random/generator.rs
- tfhe/src/core_crypto/commons/math/random/mod.rs
- tfhe/src/core_crypto/commons/math/random/tests.rs
- tfhe/src/core_crypto/commons/math/torus/mod.rs
- tfhe/src/core_crypto/commons/mod.rs
- tfhe/src/core_crypto/commons/numeric/unsigned.rs
- tfhe/src/core_crypto/entities/lwe_ciphertext.rs
- tfhe/src/core_crypto/entities/lwe_compact_ciphertext_list.rs
- tfhe/src/core_crypto/entities/seeded_lwe_ciphertext.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/320
- updated some function name (for modulus checking) to be clearer on what they do and when to use them
> chore(core): fix noise generation which could overflow the custom modulus

- scripts/integer-tests.sh
Rejoice, as div_rem takes over div and rem!
> chore(ci): refactor integer script and skip div and rem preferring div_rem

- tfhe/src/integer/server_key/radix_parallel/add.rs
In the function that sums a vec of ciphertexts,
we track trivial zeros to avoid un-needed PBSes.
One of this tracker is `last_block_where_addition_happened` however it was not properly computed.
It was initialized to `num_blocks - 1`, and then got applied a bunch of `max(current, new)` where 0 <= new <= num_block - 1 which means last_block_where_addition_happened was always num_blocks - 1.
The correct initial value is 0.
> fix(integer): fix inner index computation in sum

- tfhe/Cargo.toml
- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/src/core_crypto/algorithms/slice_algorithms.rs
this improves the keyswitch performance by 35% with avx2, and 15% with avx512
> feat(core): specialize keyswitch implementation for small scalar values

- .github/workflows/trigger_aws_tests_on_pr.yml
- ci/slab.toml
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/350
> chore(ci): fix a command naming issue for the CI

- tfhe/src/integer/server_key/radix/bitwise_op.rs
This adds boolean_bitand/or/xor/not to work on BooleanBlock This is meant to improve API of BooleanBlock.
> feat(integer): add boolean_ops to work on BooleanBlock

- tfhe/docs/README.md
refs: https://github.com/zama-ai/tfhe-rs/issues/748
fix latex equation typo preventing formatting on GitHub
> chore(doc): fix latex equation typo preventing formatting on GitHub

- Makefile
- tfhe/Cargo.toml
- tfhe/src/high_level_api/integers/mod.rs
- tfhe/src/high_level_api/mod.rs
- tfhe/src/lib.rs
Fixes https://github.com/zama-ai/tfhe-rs-internal/issues/373#event-11372892071
> fix(hlapi): fix safe-deserialization feature gating

- tfhe/src/integer/server_key/radix/mod.rs
These functions does the logic of uX/iX as iX and uX/iX as uX
> feat(integer): add cast_to_signed/unsigned

- backends/tfhe-cuda-backend/implementation/include/bootstrap_multibit.h
- backends/tfhe-cuda-backend/implementation/include/integer.h
- backends/tfhe-cuda-backend/implementation/src/integer/integer.cuh
- backends/tfhe-cuda-backend/implementation/src/pbs/bootstrap_fast_multibit.cuh
- backends/tfhe-cuda-backend/implementation/src/pbs/bootstrap_multibit.cu
- backends/tfhe-cuda-backend/implementation/src/pbs/bootstrap_multibit.cuh
> feat(gpu): implement memory reuse for lut objects

- .github/workflows/aws_tfhe_gpu_tests.yml
Close: zama-ai/tfhe-rs-internal#412
> chore(ci): separate clippy and tests in different job steps

- tfhe/docs/how_to/migrate_data.md
> chore(docs): fix link to 0.4 semver doc

- backends/tfhe-cuda-backend/cuda/include/bootstrap.h
- backends/tfhe-cuda-backend/cuda/include/bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_amortized.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_amortized.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_fast_low_latency.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_fast_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_low_latency.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_low_latency.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_multibit.cuh
Rename "test vector" to "luts" and "tvi" to "lut indexes"
> TFHE-cuda-backend | Rename "test vector" to "luts" and "tvi" to "lut indexes"

- tfhe/docs/SUMMARY.md
- tfhe/docs/how_to/debug.md
- tfhe/docs/how_to/rayon_crate.md
- tfhe/src/test_user_docs.rs
closes https://github.com/zama-ai/tfhe-rs-internal/issues/137
> Doc update

- .github/workflows/pbs_gpu_benchmark.yml
- .github/workflows/start_benchmarks.yml
- .github/workflows/start_full_benchmarks.yml
- Makefile
- ci/slab.toml
- tfhe/benches/core_crypto/pbs_bench.rs
> Add gpu benchmarks for the PBS & multi-bit PBS

- tfhe/benches/integer/bench.rs
> chore(bench): add ciphertexts sum to integer benchmarks

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_bitops.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/core_crypto/gpu/mod.rs
solves a part of: https://github.com/zama-ai/tfhe-rs-internal/issues/276
> chore(gpu): check for all cuda errors and abort in device.cu/.h

- tfhe/src/high_level_api/integers/signed/base.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
- tfhe/src/integer/server_key/comparator.rs
- tfhe/src/integer/server_key/radix_parallel/div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- document results when divisor is 0
- add checked_div (closes https://github.com/zama-ai/tfhe-rs-internal/issues/431)
> Checked div

- Makefile
- tfhe/Cargo.toml
- tfhe/examples/fhe_strings/README.md
- tfhe/examples/fhe_strings/assert_functions/mod.rs
- tfhe/examples/fhe_strings/assert_functions/test_vectors.rs
- tfhe/examples/fhe_strings/ciphertext.rs
- tfhe/examples/fhe_strings/client_key.rs
- tfhe/examples/fhe_strings/main.rs
- tfhe/examples/fhe_strings/server_key/comp.rs
- tfhe/examples/fhe_strings/server_key/mod.rs
- tfhe/examples/fhe_strings/server_key/no_patterns.rs
- tfhe/examples/fhe_strings/server_key/pattern/contains.rs
- tfhe/examples/fhe_strings/server_key/pattern/find.rs
- tfhe/examples/fhe_strings/server_key/pattern/mod.rs
- tfhe/examples/fhe_strings/server_key/pattern/replace.rs
- tfhe/examples/fhe_strings/server_key/pattern/split/mod.rs
- tfhe/examples/fhe_strings/server_key/pattern/split/split_iters.rs
- tfhe/examples/fhe_strings/server_key/pattern/strip.rs
- tfhe/examples/fhe_strings/server_key/trim.rs
This PR adds the FHE str API example.
> docs(tfhe): add fhe_strings example

- tfhe/src/integer/key_switching_key/test.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/177
Make sure integer keyswitching tests run
> chore(integer): plug keyswitching tests with the ci_run_filter for nextest

- tfhe/src/integer/server_key/radix/neg.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/13
Backlog issue
> feat(integer): add smart_neg_assign

- .github/workflows/aws_tfhe_gpu_tests.yml
- Cargo.toml
- Makefile
- backends/tfhe-cuda-backend/cuda/format_tfhe_cuda_backend.sh
- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_amortized.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_amortized.cuh
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/442 and https://github.com/zama-ai/tfhe-rs-internal/issues/440
> chore(gpu): add tfhe-cuda-backend to the workspace

- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
> fix(gpu): fix cuda_memset with size 0

- tfhe/src/boolean/parameters/mod.rs
This will allow to run parameters security checks on all the boolean parameters.
> refactor(boolean): put all parameters into constant array

- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
> fix(gpu): fix 40 bit integer multiplication

- tfhe/benches/integer/bench.rs
- tfhe/benches/integer/signed_bench.rs
- tfhe/benches/utilities.rs
Closes: zama-ai/tfhe-rs-internal#439
> chore(bench): implement integer casting benchmarks

- tfhe/docs/fine_grained_api/shortint/operations.md
- Fix comment in fine grained API docs
> chore(doc): fix docs snippet comments

- .github/workflows/core_crypto_benchmark.yml
- .github/workflows/core_crypto_gpu_benchmark.yml
- .github/workflows/start_benchmarks.yml
- .github/workflows/start_full_benchmarks.yml
- ci/slab.toml
- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/benches/core_crypto/pbs_bench.rs
> chore(bench): fix ks benchmark

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- tfhe/src/integer/gpu/server_key/radix/comparison.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests.rs
closes: one item of https://github.com/zama-ai/concrete-internal/issues/341
> feat(gpu): implement scalar eq/ne

- .github/workflows/aws_tfhe_gpu_tests.yml
- Makefile
- scripts/c_api_tests.sh
- tfhe/build.rs
- tfhe/c_api_tests/CMakeLists.txt
- tfhe/c_api_tests/test_high_level_integers_cuda.c
- tfhe/cbindgen.toml
- tfhe/src/c_api/high_level_api/keys.rs
- This adds GPU support in the C API
- Also make ctest (cmake test launcher) print test output when it fails
> feat(capi): add Cuda support

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_gpu_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/csprng_randomness_tests.yml
A first review is needed to validate the design before extending the changes to others workflows.
> chore(ci): notify ec2 teardown failure on slack channel

- README.md
- Reorganized existing content to follow the new structure
- Aligned all the header links and badges
- Added a table of contents
- Added a call-to-action for users to star the repo
- Checked all links and replaced outdated ones.
- Unified the formatting
- Updated the support banner 
- Improved the overall content quality
- Added missing content where necessary
- Added more “resources” for each product
- Ensured wording is consistent throughout
> chore(doc): Update Readme.md

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
Modify cuda scalar shifts  to use only one wave of pbs
> feat(gpu): scalar shifts with one wave of pbs

- ci/slab.toml
Done to get clang-format-15 and cmake-format and latest packages updates.
> chore(ci): update gpu aws ec2 ami

- .github/workflows/aws_tfhe_gpu_4090_tests.yml
- Makefile
- backends/tfhe-cuda-backend/cuda/format_tfhe_cuda_backend.sh
- tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
Add an RTX 4090 CI workflow triggered on label
> chore(ci): set-up a workflow to use the RTX 4090

- Makefile
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests.rs
> chore(gpu): activate all targets for clippy_gpu

- tfhe/benches/integer/bench.rs
> chore(gpu): add benchmarks for scalar eq/ne and casts

- tfhe/c_api_tests/test_c_doc.c
- tfhe/c_api_tests/test_high_level_integers.c
- tfhe/c_api_tests/test_high_level_integers_cuda.c
- tfhe/c_api_tests/test_high_level_threading.c
- tfhe/src/c_api/high_level_api/mod.rs
- tfhe/src/c_api/high_level_api/threading.rs
Adds necessary tools to allow a C API user to control number of threads used by integer operations.
Its mainly exposing rayon's thread pool in C
> feat(capi): allow control of threading

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/436
> chore(gpu): improve performance of comparison operations

- .github/workflows/aws_tfhe_gpu_tests.yml
- backends/tfhe-cuda-backend/cuda/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/tests/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/tests/include/setup_and_teardown.h
- backends/tfhe-cuda-backend/cuda/tests/include/utils.h
- backends/tfhe-cuda-backend/cuda/tests/setup_and_teardown.cpp
- backends/tfhe-cuda-backend/cuda/tests/src/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/tests/src/README.md
- backends/tfhe-cuda-backend/cuda/tests/src/test_classical_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests/src/test_fft.cpp
- backends/tfhe-cuda-backend/cuda/tests/src/test_keyswitch.cpp
- backends/tfhe-cuda-backend/cuda/tests/src/test_multibit_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests/utils.cpp
> feat(gpu): Reintroduce a tool to independently test PBS, Keyswitch, and fft

- .github/workflows/gpu_4090_full_benchmark.yml
> chore(gpu): add core crypto benches to 4090 bench workflow

- .github/workflows/gpu_4090_full_benchmark.yml
> chore(gpu): fix 4090 bench workflow

- backends/tfhe-cuda-backend/cuda/include/integer.h
> fix(gpu): fix scalar eq for booleans

- tfhe/src/core_crypto/algorithms/lwe_private_functional_packing_keyswitch.rs
- tfhe/src/core_crypto/algorithms/test/lwe_private_functional_packing_keyswitch.rs
> feat(core_crypto): add parallelized pfpks with lwe ciphertext list

- .github/workflows/gpu_4090_full_benchmark.yml
- .github/workflows/integer_gpu_benchmark.yml
- .github/workflows/integer_gpu_full_benchmark.yml
- .github/workflows/integer_multi_bit_gpu_benchmark.yml
as a follow we will add an actionlint workflow
> chore(ci): fix workflows, missing leading $, skipped does not exist

- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_multibit.cu
Solves https://github.com/zama-ai/tfhe-rs-internal/issues/487
> chore(gpu): change recomended lwe_chunk_size for NVIDIA Tesla H100 GPUs

- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_multibit.cu
> fix(gpu): fix memory bug in multi-bit PBS

- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/CMakeLists.txt
> chore(gpu): fix compilation without a device

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/utils/helper.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
reduce key switch operations twice, reduce PBS layers twice, and remove compression and decompression operations. remove most of the memcopies.
add an entry point for summ_ciphertexts
solves: [404](https://github.com/zama-ai/tfhe-rs-internal/issues/404)
solves: [437](https://github.com/zama-ai/tfhe-rs-internal/issues/437)
> feat(gpu): optimize gpu integer multiplication  vector_ add block.

- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
> fix(integer): fix parallel carry propagation on empty input

- backends/tfhe-cuda-backend/cuda/.gitignore
- backends/tfhe-cuda-backend/cuda/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/cuda_config.h.in
- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
Follow the advice in https://developer.nvidia.com/blog/cuda-pro-tip-the-fast-way-to-query-device-properties/
> chore(gpu): reduce scratch time

- tfhe/src/integer/wopbs/mod.rs
- tfhe/src/integer/wopbs/test.rs
closes: https://github.com/zama-ai/tfhe-rs/issues/849
LUT generation had a bug, which was subtle enough to not trigger on LUTs used to test the wopbs, a user (see linked issue) was trying a LUT with a threshold and the generated LUT was full of 0s, i.e. wrong.
This fix allows to properly generate the CRT LUT managing high degress when they arise.
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
> fix(integer): fix the CRT LUT generation

- backends/tfhe-cuda-backend/cuda/format_tfhe_cuda_backend.sh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/setup_and_teardown.h
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/utils.h
> fix(gpu): includes tests_and_benchmarks/include to format_tfhe_cuda_backend.sh

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cu
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/benches/integer/bench.rs
- tfhe/src/integer/gpu/ciphertext/boolean_value.rs
- tfhe/src/integer/gpu/ciphertext/info.rs
- tfhe/src/integer/gpu/ciphertext/mod.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/sub.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_sub.rs
Implement cuda version for unsigned_overflowing_sub
> feat(gpu): implement overflowing_sub

- tfhe/src/high_level_api/keys/server.rs
- tfhe/src/integer/gpu/server_key/mod.rs
> feat(gpu): add an entry point to decompress integer server key to cuda server key

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/benches/integer/signed_bench.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_shift.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_shift.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_shift.rs
- tfhe/src/integer/server_key/crt/tests.rs
- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_comparisons.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_signed.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_shift.rs
- tfhe/src/integer/tests.rs
> feat(gpu): signed scalar shift

- README.md
reported in https://github.com/zama-ai/tfhe-rs/pull/1027 but for lack of CLA we do it here
> chore(doc): fix incorrect comment in repo README

- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
replace hardcoded degrees in integer multiplication with actual values.
> fix(gpu): replace hardcoded degrees in multiplication.cuh 

- tfhe/src/high_level_api/integers/unsigned/inner.rs
- tfhe/src/high_level_api/integers/unsigned/ops.rs
- tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
- tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
- tfhe/src/high_level_api/integers/unsigned/tests/mod.rs
- tfhe/src/high_level_api/keys/server.rs
> feat(hlapi): bind sum for cuda backend

- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
> fix(gpu): fix mult 256 bit benchmark

- tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
> chore(gpu): remove carry prop after scalar mul single carry prop after scalar add/sub

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
> chore(gpu): fix multi-bit scalar mul benchmark

- tfhe/docs/getting_started/benchmarks.md
- tfhe/docs/guides/run_on_gpu.md
> doc(gpu): add benchmark results

- tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- tfhe/src/core_crypto/algorithms/test/params.rs
- tfhe/src/core_crypto/commons/generators/encryption/mask_random_generator.rs
- tfhe/src/core_crypto/commons/generators/encryption/mod.rs
- tfhe/src/core_crypto/commons/generators/encryption/noise_random_generator.rs
- tfhe/src/core_crypto/commons/parameters.rs
- tfhe/src/core_crypto/experimental/algorithms/glwe_fast_keyswitch.rs
- tfhe/src/core_crypto/experimental/algorithms/glwe_partial_sample_extraction.rs
- tfhe/src/core_crypto/experimental/algorithms/mod.rs
- tfhe/src/core_crypto/experimental/algorithms/partial_glwe_secret_key_generation.rs
- tfhe/src/core_crypto/experimental/algorithms/pseudo_ggsw_conversion.rs
- tfhe/src/core_crypto/experimental/algorithms/pseudo_ggsw_encryption.rs
- tfhe/src/core_crypto/experimental/algorithms/shared_glwe_secret_key_generation.rs
- tfhe/src/core_crypto/experimental/algorithms/test/lwe_fast_keyswitch.rs
- tfhe/src/core_crypto/experimental/algorithms/test/lwe_stair_keyswitch.rs
- tfhe/src/core_crypto/experimental/algorithms/test/mod.rs
- tfhe/src/core_crypto/experimental/commons/parameters.rs
- tfhe/src/core_crypto/experimental/entities/fourier_pseudo_ggsw_ciphertext.rs
- tfhe/src/core_crypto/experimental/entities/mod.rs
- tfhe/src/core_crypto/experimental/entities/pseudo_ggsw_ciphertext.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
- tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
had no choice for the generators to have access to the internal generators (which we don't want to tamper with) other than creating the experimental module
I had a big refactor for the randomness which should have allowed to avoid that but I put it on hold as it was very big and not contributing to feature OKRs
> Stair KS and fast KS coming from experimental keytricks

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
> chore(gpu): add lwe_chunk_size targeting RTX 4090 GPUs

- tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
> fix(gpu): add edge test for scalar comparisons

- tfhe/src/high_level_api/integers/signed/compressed.rs
- tfhe/src/high_level_api/integers/unsigned/compressed.rs
This targets the 0.6 release branch, main realistically does not need that
> chore(hl): add method to be able to perform data update from 0.5 compressed

- .github/workflows/m1_tests.yml
- Makefile
- scripts/c_api_tests.sh
- tfhe/c_api_tests/test_boolean_keygen.c
- tfhe/c_api_tests/test_boolean_server_key.c
- tfhe/c_api_tests/test_high_level_zk.c
- tfhe/c_api_tests/test_micro_bench_and.c
- tfhe/c_api_tests/test_shortint_keygen.c
- tfhe/c_api_tests/test_shortint_pbs.c
- tfhe/c_api_tests/test_shortint_server_key.c
> chore(c_api): fix build on M1 mac

- tfhe/src/c_api/core_crypto/mod.rs
- tfhe/src/core_crypto/algorithms/test/params.rs
- tfhe/src/core_crypto/fft_impl/fft128_u128/crypto/ggsw.rs
Finishes fixing https://github.com/zama-ai/tfhe-rs-internal/issues/345
> Small fixes

- tfhe/docs/guides/run_on_gpu.md
> fix(gpu): fix typo in doc

- tfhe/src/high_level_api/integers/signed/base.rs
- tfhe/src/high_level_api/integers/signed/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
> chore(gpu): add casts and signed scalar comparisons to the hl api

- tfhe/benches/integer/bench.rs
> chore(gpu): fix params in GPU integer benchmarks

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap.h
- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/parameters.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
closes:  https://github.com/zama-ai/tfhe-rs-internal/issues/470
> chore(gpu): extend integer multiplication to N other than 2048

- tfhe/docs/getting_started/quick_start.md
> chore(doc): fix broken link

- backends/tfhe-cuda-backend/cuda/format_tfhe_cuda_backend.sh
- backends/tfhe-cuda-backend/get_os_name.sh
- scripts/integer-tests.sh
- scripts/shortint-tests.sh
This is a small fix to enable non-FHS distributions (in my case nixOS) to properly execute bash scripts available in this repository,
> Fix bash script shebangs

- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_vector_comparisons.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_vector_comparisons.rs
- tfhe/src/integer/server_key/radix_parallel/vector_comparisons.rs
- tfhe/src/shortint/parameters/mod.rs
This adds eq_slices functions.
This function, compares to slices of radix ciphertexts and returns true if all pairs of element are equal.
> feat(integer): add an eq_slice function

- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_vector_comparisons.rs
- tfhe/src/integer/server_key/radix_parallel/vector_comparisons.rs
This method returns a Boolean block that tells whether a slice of radix contains a sub slice.
> feat(integer): add contains_sub_slice

- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
Implement host functions with pointer checks for radix_blocks_rotate kernels
> feat(gpu): implement host functions for radix_blocks_rotates

- tfhe/src/core_crypto/entities/glwe_ciphertext_list.rs
- tfhe/src/core_crypto/entities/lwe_ciphertext_list.rs
closes: #1108
The first commit adds `from_fn` methods for `(G)lweCiphertextList`, enabling the user to directly initialize ciphertext lists using a closure. This closure must receive an `usize` as argument (the index) and return a scalar value that will initialize the list at the provided index. The closure is the last function parameter so that `rustfmt` can properly format the function call without skipping additional lines if the provided arguments can fit into a single line.
Following the name convention from `from_fn`, the second commit adds `from_elem` methods that behave similarly to the previous `new` methods, except for following a different parameter order to match `from_fn` parameters. Both `new` methods were marked as deprecated and internally invoke `from_elem` methods. …
> Implement (G)lweCiphertextList::from_fn/from_elem methods

- tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
- was useful for the sampling tool
> chore(core): make the mulit bit mod switch public

- backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
modify api for `integer_radix_apply_bivariate_lookup_table_kb` to accept `shift` parameter, useful for luts generated with factor
> feat(gpu): modify `integer_radix_apply_bivariate_lookup_table_kb` to accept shift parameter 

- tfhe/src/boolean/client_key/mod.rs
- tfhe/src/boolean/engine/mod.rs
- tfhe/src/core_crypto/commons/parameters.rs
- tfhe/src/shortint/client_key/mod.rs
- tfhe/src/shortint/engine/client_side.rs
- tfhe/src/shortint/engine/public_side.rs
- tfhe/src/shortint/parameters/mod.rs
- tfhe/src/shortint/public_key/compact.rs
- tfhe/src/shortint/public_key/compressed.rs
- tfhe/src/shortint/public_key/standard.rs
closes: 
- some parameter selection (like noise distributions) were made manually and were error prone in the past
- factorize those to have fewer places to check and update
> refactor(tfhe): provide functions to select some encryption parameters

- backends/tfhe-cuda-backend/cuda/src/crypto/gadget.cuh
- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_keyswitch.cpp
> chore(gpu): change the number of threads used in the keyswitch

- tfhe/benches/core_crypto/ks_bench.rs
> chore(gpu): remove broken ks benchmark

- .github/workflows/make_release_zk_pok.yml
Closes: zama-ai/tfhe-rs-internal#544
> chore(ci): create release workflow for tfhe-zk-pok

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
> fix(gpu):  disable non-portable cluster sizes on TBC PBSs

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cu
> fix(gpu): fix indexing on DSM mode

- .github/workflows/hyperstack_tfhe_gpu_tests.yml
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cu
> chore(gpu): add h100 workflow for tests

- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/integer/ciphertext/boolean_value.rs
> chore(tfhe): add the ability to get raw parts from an FheBool

- backends/tfhe-cuda-backend/build.rs
> chore(gpu): rebuild cuda backend if files changed

- tfhe/docs/getting_started/operations.md
- tfhe/docs/guides/run_on_gpu.md
- tfhe/src/high_level_api/traits.rs
- tfhe/src/integer/server_key/radix_parallel/cmux.rs
Closes https://github.com/zama-ai/tfhe-rs-internal/issues/594
> chore(tfhe): alias if_then_else to select

- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/utils/kernel_dimensions.cuh
> chore(gpu): parallelize keyswitch further

- tfhe/benches/integer/bench.rs
- tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
- tfhe/src/integer/gpu/ciphertext/info.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_add.rs
Implement overflowing unsigned add on cuda backend
> feat(gpu): implement overflowing unsigned add

- .github/workflows/core_crypto_benchmark.yml
- Makefile
- tfhe/Cargo.toml
- tfhe/benches/core_crypto/pbs128_bench.rs
closes: zama-ai/tfhe-rs-internal#449
> chore(bench): add pbs128 to benchmarks suite

- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_fft.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/setup_and_teardown.h
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/utils.h
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/setup_and_teardown.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/utils.cpp
> fix(gpu): fix cuda bench warnings

- tfhe/benches/core_crypto/pbs_bench.rs
closes zama-ai/tfhe-rs-internal#591
> chore(bench): add benchmarks for pbs-ntt64

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cu
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/606
> fix(gpu): use all gpus in omp loops

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
closes:  https://github.com/zama-ai/tfhe-rs-internal/issues/604
> GPU fix: use different streams in  if_then_else for OMP loop

- tfhe/src/integer/ciphertext/compact_list.rs
- fixed the test according to the code that was merged
Missed a typo in a feature during review, this is the corresponding fix
> fix(test): there was a typo in a feature name not picked up by clippy

- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_fft.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
> chore(gpu): fix warnings in pcc_gpu

- backends/tfhe-cuda-backend/Cargo.toml
> chore(gpu): removed unused dependency

- tfhe/src/integer/server_key/radix/add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
This PR refactors signed overflowing add and sub tests to use a function executor, to make GPU integration of these functions easier.
> Refactor signed overflow add sub tests

- tfhe/c_api_tests/test_high_level_2048.c
- tfhe/js_on_wasm_tests/test-hlapi-unsigned.js
- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/c_api/high_level_api/mod.rs
- tfhe/src/c_api/high_level_api/u2048.rs
- tfhe/src/c_api/high_level_api/utils.rs
- tfhe/src/high_level_api/integers/mod.rs
- tfhe/src/high_level_api/integers/unsigned/mod.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/static_.rs
- tfhe/src/high_level_api/mod.rs
- tfhe/src/integer/bigint/mod.rs
- tfhe/src/integer/bigint/static_unsigned.rs
- tfhe/src/integer/bigint/u256.rs
- tfhe/src/integer/bigint/u512.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
- tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
Adds FheUint2048 to 0.6 release
> feat(tfhe): add FheUint2048

- tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping/fft64.rs
- tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/bootstrap.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/526
As indicated in the previous PR easier to do for the PBS as scalar types don't really interact
> feat(core): add variable Scalar type to PBS for input and output

- .github/workflows/aws_tfhe_multi_gpu_tests.yml
- .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
- .github/workflows/integer_multi_gpu_full_benchmark.yml
> Multi-GPU: add workflow for multi-bit (64 bit) benchmarks

- tfhe/src/shortint/parameters/multi_bit/mod.rs
- tfhe/src/shortint/parameters/multi_bit/p_fail_2_minus_40/mod.rs
- tfhe/src/shortint/parameters/multi_bit/p_fail_2_minus_64/ks_pbs_gpu.rs
- tfhe/src/shortint/parameters/multi_bit/p_fail_2_minus_64/mod.rs
> chore(gpu): update gpu parameters

- tfhe/benches/integer/bench.rs
- tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
Implement overflowing scalar add
> feat(gpu): Implement unsigned_overflowing_scalar_add

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/integer/gpu/mod.rs
> chore(gpu): add apply bivariate lut as entry point on the rust side

- .github/workflows/integer_multi_gpu_full_benchmark.yml
- tfhe/benches/integer/bench.rs
+ Fix if_then_else bench name
+ Add bitnot benchmark
+ Add scalar rotate benchmarks
+ Fix multi-gpu workflow 
> chore(gpu): fix benchmarks

- tfhe-zk-pok/Cargo.toml
- tfhe-zk-pok/src/curve_446/mod.rs
- tfhe-zk-pok/src/curve_api.rs
- tfhe-zk-pok/src/curve_api/bls12_381.rs
- tfhe-zk-pok/src/curve_api/bls12_446.rs
- tfhe-zk-pok/src/curve_api/msm.rs
- tfhe-zk-pok/src/proofs/binary.rs
- tfhe-zk-pok/src/proofs/index.rs
- tfhe-zk-pok/src/proofs/mod.rs
- tfhe-zk-pok/src/proofs/pke.rs
- tfhe-zk-pok/src/proofs/range.rs
- tfhe-zk-pok/src/proofs/rlwe.rs
> feat(zk): improve performance of zk pke proofs

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cu
- backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/integer/gpu/ciphertext/info.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
> chore(gpu): Add bitnot operation without using pbs

- tfhe/web_wasm_parallel_tests/package-lock.json
> chore(ci): update npm packages

- backends/tfhe-cuda-backend/Cargo.toml
- tfhe/Cargo.toml
> chore(gpu): bump cuda backend version

- tfhe-zk-pok/src/proofs/binary.rs
- tfhe-zk-pok/src/proofs/mod.rs
- tfhe-zk-pok/src/proofs/pke.rs
- tfhe-zk-pok/src/proofs/range.rs
- tfhe-zk-pok/src/proofs/rlwe.rs
> feat(zk): add randomness to hash functions

- Makefile
- scripts/integer-tests.sh
- scripts/shortint-tests.sh
- tfhe/Cargo.toml
- tfhe/build.rs
- tfhe/docs/guides/zk-pok.md
- tfhe/src/c_api/high_level_api/compact_list.rs
- tfhe/src/c_api/high_level_api/mod.rs
- tfhe/src/core_crypto/algorithms/lwe_encryption.rs
- tfhe/src/core_crypto/algorithms/mod.rs
- tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
- tfhe/src/core_crypto/entities/mod.rs
- tfhe/src/error.rs
- tfhe/src/high_level_api/compact_list.rs
- tfhe/src/high_level_api/mod.rs
- tfhe/src/integer/ciphertext/compact_list.rs
- tfhe/src/integer/mod.rs
- tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
- tfhe/src/js_on_wasm_api/js_high_level_api/mod.rs
- tfhe/src/lib.rs
- tfhe/src/shortint/ciphertext/mod.rs
- tfhe/src/shortint/engine/mod.rs
- tfhe/src/shortint/public_key/compact.rs
following the approval of https://github.com/zama-ai/tfhe-rs/pull/1259
> chore(tfhe): mark zk-pok as non experimental

- tfhe/docs/core_crypto/presentation.md
> chore(docs): fix broken links

- tfhe/docs/SUMMARY.md
- tfhe/docs/fundamentals/serialization.md
- tfhe/docs/guides/data_versioning.md
- tfhe/docs/guides/migrate_data.md
- tfhe/src/test_user_docs.rs
> Add doc for the versioning/backward compat feature

- tfhe/benches/integer/bench.rs
> chore(bench): fix display name for gpu unsigned integer operations

- tfhe-zk-pok/Cargo.toml
- tfhe-zk-pok/src/curve_api/bls12_446.rs
> feat(zk): zk perf improvements

- .github/workflows/hyperstack_tfhe_gpu_tests.yml
> chore(gpu): call nvidia-smi before launching tests on hyperstack

- tfhe/Cargo.toml
- tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
- tfhe/src/core_crypto/gpu/slice.rs
- tfhe/src/core_crypto/gpu/vec.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/549
> chore(gpu): use byte add, update rust msrv

- tfhe/src/core_crypto/commons/math/decomposition/decomposer.rs
- tfhe/src/core_crypto/commons/numeric/unsigned.rs
> feat(perf): optimize some custom mod ops

- Makefile
- tfhe/Cargo.toml
- tfhe/benches/integer/bench.rs
- tfhe/benches/integer/oprf.rs
closes: zama-ai/tfhe-rs-internal#564
> chore(bench): add benchmarks for integer oprf

- tfhe/benches/integer/bench.rs
- tfhe/benches/integer/signed_bench.rs
> chore(gpu): reduce integer bench time

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_integer_gpu_tests.yml
- .github/workflows/aws_tfhe_signed_integer_gpu_tests.yml
- Makefile
- scripts/integer-tests.sh
- scripts/test_filtering.py
Several improvement to make CI faster.
> chore(ci): reduce ci execution time

- scripts/integer-tests.sh
> chore(gpu): fix unsigned ci tests

- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
This PR allocates pinned memory for the BSK to allow for asynchronous copy over all used GPUs.
> chore(gpu): pin bsk host memory

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/addition.cu
- backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/benches/integer/signed_bench.rs
- tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_add.rs
Implements signed overflowing add in cuda backend.
> feat(gpu): implement signed_overflowing_add

- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- condition was not precise enough and we were still running tests on push to internal main
> chore(ci): fix the no internal test patch

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/addition.cu
- backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/benches/integer/signed_bench.rs
- tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_add.rs
Implements signed overflowing sub in cuda backend.
> feat(gpu): implement signed_overflowing_sub

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
> chore(gpu): clean overflowing sub memory

- backends/tfhe-cuda-backend/cuda/src/integer/addition.cu
- backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cu
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cu
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
> chore(gpu): remove unnecessary templates

- backends/tfhe-cuda-backend/cuda/include/integer.h
> chore(gpu): fix some int_radix_luts numbers of blocks

- tfhe/src/high_level_api/backward_compatibility/keys.rs
- tfhe/src/high_level_api/keys/key_switching_key.rs
> feat(hl): add serialize/versionize for hl KSK

- .github/workflows/make_release.yml
cargo package does not generate a lockfile, this fixes that
> chore(ci): generate lockfile before packaging

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
> chore(gpu): remove stream callbacks

- Makefile
Make it possible to chose the branch of the backward data repo used for tests
> chore(backward): allow custom data repo branch for tests

- backends/tfhe-cuda-backend/cuda/include/integer.h
> fix(gpu): add missing delete

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
- tfhe/benches/integer/signed_bench.rs
- tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
- tfhe/src/integer/gpu/server_key/radix/sub.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_sub.rs
Add signed_overflowing_sub in cuda backend
> feat(gpu): Add signed_overflowing_sub in cuda backend

- tfhe/benches/integer/signed_bench.rs
- tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_add.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
Implements `signed_overflowing_scalar_add` and `signed_overflowing_scalar_sub` on cuda backend
> feat(gpu): Add signed_overflowing_scalar_add and signed_overflowing_scalar_sub on cuda backend

- .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
- .github/workflows/integer_multi_gpu_full_benchmark.yml
> chore(gpu): fix hardware name in multi-gpu workflows

- backends/tfhe-cuda-backend/cuda/src/device.cu
> fix(gpu): fix add with 1 block

- .github/workflows/hyperstack_tfhe_gpu_tests.yml
- .github/workflows/integer_gpu_benchmark.yml
- .github/workflows/integer_gpu_full_benchmark.yml
- .github/workflows/integer_multi_bit_gpu_benchmark.yml
- .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
- .github/workflows/integer_multi_gpu_full_benchmark.yml
> chore(gpu): add nvidia-smi call in all hyperstack workflows

- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
> chore(gpu): add checks in hillis&steele to avoid wrong memory access

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/integer/gpu/mod.rs
> fix(gpu): fix full prop with 1 block

- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
> chore(gpu): refactor tree_add_chunks

- tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/sub.rs
> feat(integer): implement unsigned_overflowing_scalar_sub

- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
Closes: zama-ai/tfhe-rs-internal#695
> chore(ci): avoid running integer tests on push to internal repo

- tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
- tfhe/src/core_crypto/fft_impl/fft64/math/fft/x86.rs
> feat(pbs): slightly improve f64 pbs perf

- tfhe/benches/integer/bench.rs
> chore(gpu): add ilog2 bench

- tfhe-zk-pok/src/proofs/pke_v2.rs
- allows to prove less slots than what the CRS can handle
> feat(zk): manage D as an upper bound as in the report

- tfhe-zk-pok/src/proofs/pke_v2.rs
- tfhe/src/zk.rs
Adds a few comments to zk pke v2
> chore(zk): add some comments to the zk pke v2 proof

- ci/slab.toml
> chore(gpu): change multi-gpu tests to run on rtx so it's cheaper

- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
> fix(gpu): fix comparisons

- .github/workflows/benchmark_gpu_integer_full.yml
- tfhe/benches/integer/bench.rs
> chore(gpu): remove unchecked benchmarks and add ilog2 to dedup ops

- tfhe/src/integer/compression_keys.rs
> feat(integer): add raw parts API to integer CompressionPrivateKey

- Makefile
- scripts/integer-tests.sh
> chore(gpu): temporarily set test threads to 1 for the GPU

- .github/workflows/gpu_fast_h100_tests.yml
> chore(gpu): disable slack notification for fast h100 test success

- tfhe-zk-pok/src/proofs/pke_v2.rs
This mirrors what ha been done with zk v1: adds the metadata to the hash operations.
> feat(zk): add metadata to v2

- tfhe/benches/integer/bench.rs
> chore(gpu): add some scalar ops to dedup benchmarks

- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_mul.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_rotate.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_rotate.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
> chore(gpu): print info about inputs in determinism test asserts

- backends/tfhe-cuda-backend/cuda/src/fft/bnsmfft.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
Modified the `FFT` and `inverse FFT` to reduce shared memory reads and writes. Adjusted the `opt` variable for degree parameters. Added a condition for the 2048-size multi-bit bootstrap to select which opt to use based on the num_samples value."
> feat(gpu): implements fft with reduced shared memory read/write.

- backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
see https://zama-ai.slack.com/archives/C0449E8QATY/p1727181877249699
> fix(gpu): fixing plaintext addition

- tfhe/benches/integer/zk_pke.rs
- tfhe/web_wasm_parallel_tests/worker.js
this is a size we want to show in our docs
> chore(bench): bench 64 bits for ZKs

- tfhe/benches/integer/bench.rs
> chore(gpu): add leading zeros/ones benchmarks

- backends/tfhe-cuda-backend/cuda/include/compression.h
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cu
> chore(gpu): change index array type in decompression

- Makefile
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/benches/integer/glwe_packing_compression.rs
- tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/core_crypto/gpu/vec.rs
- tfhe/src/high_level_api/backward_compatibility/compressed_ciphertext_list.rs
- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/high_level_api/booleans/encrypt.rs
- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/high_level_api/integers/signed/base.rs
- tfhe/src/high_level_api/integers/signed/ops.rs
- tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
- tfhe/src/high_level_api/integers/signed/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
- tfhe/src/high_level_api/integers/unsigned/encrypt.rs
- tfhe/src/high_level_api/integers/unsigned/ops.rs
- tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/high_level_api/keys/inner.rs
- tfhe/src/high_level_api/keys/server.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/client_key/radix.rs
- tfhe/src/integer/gpu/list_compression/compressed_server_keys.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
> chore(gpu): add gpu compression in the hl api

- backends/tfhe-cuda-backend/cuda/include/device.h
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
> fix(gpu): fix end index in gpu compression

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
> chore(gpu): refactor lwe_chunk_size

- tfhe/docs/guides/run_on_gpu.md
> chore(gpu) : add module loading info

- tfhe/benches/core_crypto/pbs_bench.rs
- tfhe/docs/getting_started/benchmarks/gpu_benchmarks.md
> chore(gpu): add ks/pbs benchmarks in the documentation

- tfhe/src/integer/gpu/server_key/radix/add.rs
> fix(gpu): remove extra single carry propagation from partial sum

- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/src/core_crypto/gpu/algorithms/lwe_packing_keyswitch.rs
> feat(gpu): add a benchmark for packing keyswitch

- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/CMakeLists.txt
closes: https://zama-ai.slack.com/archives/C0449E8QATY/p1728292406960999?thread_ts=1727957312.934409&cid=C0449E8QATY
> chore(gpu): force cargo profile to release to build cuda tests & benches

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- tfhe/src/integer/gpu/server_key/radix/mod.rs
> fix(gpu): fix sample extract many lut use case

- backends/tfhe-cuda-backend/cuda/src/device.cu
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/768
The max SM size for rtx 4090 was a bit too high, reducing it fixes cuda backend tests.
> fix(gpu): fix rtx 4090 tests

- tfhe/src/core_crypto/entities/glwe_secret_key.rs
- tfhe/src/core_crypto/entities/lwe_secret_key.rs
This is a short term solution to https://github.com/zama-ai/tfhe-rs-internal/issues/786#issue-2576232064, but a more general solution would be appreciated on the long run
> feat(core_crypto): impl Named for LweSecretKey and GlweSecretKey

- Makefile
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- tfhe/docs/fundamentals/compress.md
- tfhe/docs/guides/run_on_gpu.md
- tfhe/src/core_crypto/entities/compressed_modulus_switched_glwe_ciphertext.rs
- tfhe/src/core_crypto/entities/packed_integers.rs
- tfhe/src/high_level_api/tests/tags_on_entities.rs
- tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/shortint/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/shortint/keycache.rs
- tfhe/src/shortint/parameters/list_compression.rs
- tfhe/src/shortint/parameters/mod.rs
- also implements Debug, PartialEq to CompressedCiphertextList
> chore(integer): brings the CPU and GPU tests into line.

- tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
> chore(gpu): make to_glwe_ciphertext_list pub

- tfhe/src/high_level_api/compact_list.rs
- tfhe/src/high_level_api/compressed_ciphertext_list.rs
Fixes https://github.com/zama-ai/tfhe-rs-internal/issues/788
> fix(hlapi): CompressedCiphertextList::get_kind_of

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- tfhe/src/integer/gpu/server_key/radix/mod.rs
> fix(gpu): fix default pbs with many luts

- .github/workflows/check_commit.yml
> chore(ci): enforce commit signature for PRs

- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
> fix(gpu): add template parameter to packing keyswitch calls

- tfhe/src/safe_serialization.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/791
> feat(serialization): add safe_serialized_size

- tfhe/src/integer/bigint/algorithms.rs
- tfhe/src/integer/bigint/static_signed.rs
- tfhe/src/integer/bigint/static_unsigned.rs
- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/comparison.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/shortint/server_key/tests/parametrized_test.rs
Some overflow panics were occurring when
overflow-check=true
Most of them were expected/accepted, so this commit only makes changes so that its now explicit that overflow is accepted.
Related to https://github.com/zama-ai/tfhe-rs-internal/issues/85
> chore: fix some overflow related panics

- apps/trivium/README.md
- concrete-csprng/README.md
co-authored-by: nnsW3
supersedes https://github.com/zama-ai/tfhe-rs/pull/1621
> chore: fix typos

- tfhe/src/integer/ciphertext/compact_list.rs
- if a boolean block is ill formed in a ProveCompactCiphertextList we now have a test that checks that when proper keys are provided slots marked as boolean are properly sanitized to contain only 0 or 1 values after expand
> chore(integer): add a test to check that a malicious list is sanitized

- tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
- this was degrading performance for some parameter sets
- gains were either anecdotal or non existent
run on main
https://github.com/zama-ai/tfhe-rs/actions/runs/11479428832/job/31945780985
run on this branch
https://github.com/zama-ai/tfhe-rs/actions/runs/11479791329/job/31946898326
original PR https://github.com/zama-ai/tfhe-rs/pull/1498/files
> chore(core): remove the fmadd split accumulation

- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/docs/guides/js_on_wasm_api.md
- tfhe/examples/utilities/wasm_benchmarks_parser.rs
- tfhe/web_wasm_parallel_tests/worker.js
> chore(ci): fix odd clippy import issue for ks bench

- ci/webdriver_requirements.txt
This reduces console verbosity.
> chore(ci): update version of selenium to 4.26.0

- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_fast_tests.yml
- .github/workflows/gpu_full_multi_gpu_tests.yml
- .github/workflows/gpu_signed_integer_h100_tests.yml
- .github/workflows/gpu_signed_integer_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
- .github/workflows/gpu_unsigned_integer_tests.yml
> chore(gpu): restrict should run

- backends/tfhe-cuda-backend/build.rs
- backends/tfhe-cuda-backend/wrapper.h
> chore(gpu): restrict bindings generation

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
> fix(gpu): fix memory error in cg classical PBS

- .github/workflows/benchmark_gpu_erc20_2h100.yml
- .github/workflows/benchmark_gpu_erc20_8h100.yml
> chore(gpu): add workflows for erc20 bench with 2 and 8 H100

- tfhe-zk-pok/Cargo.toml
- tfhe-zk-pok/src/curve_446/mod.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/573 https://github.com/zama-ai/tfhe-rs-internal/issues/813
Update arkworks to 0.5.0
> chore(zk): update arkworks to 0.5.0

- .github/workflows/aws_tfhe_fast_tests.yml
- Makefile
Re-enable the safe_(de)serialization tests that were not executed since the name of the module changed
> chore(ci): enable safe_serialization tests

- tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_abs.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_div_rem.rs
> chore(ci): use function executor for abs and signed div tests

- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_fast_tests.yml
- .github/workflows/gpu_full_multi_gpu_tests.yml
- .github/workflows/gpu_signed_integer_classic_tests.yml
- .github/workflows/gpu_signed_integer_h100_tests.yml
- .github/workflows/gpu_signed_integer_tests.yml
- .github/workflows/gpu_unsigned_integer_classic_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
- .github/workflows/gpu_unsigned_integer_tests.yml
A recent commit modifying the integer tests broke the GPU CI, we'd like to avoid that in the future.
> chore(gpu): trigger GPU tests if tests are  modified

- backends/tfhe-cuda-backend/cuda/include/pbs/pbs_multibit_utilities.h
- backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
- backends/tfhe-cuda-backend/cuda/src/crypto/gadget.cuh
- backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/polynomial_math.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/743, https://github.com/zama-ai/tfhe-rs-internal/issues/811
> fix(gpu): general fixes and improvements to PBS

- backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
> fix(gpu): fix signed overflowing sub for one block case

- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
> chore(gpu): simplifications to the zero_out_if method

- tfhe/src/high_level_api/keys/inner.rs
- tfhe/src/high_level_api/keys/public.rs
- tfhe/src/integer/public_key/compact.rs
- tfhe/src/shortint/public_key/compact.rs
Closes https://github.com/zama-ai/tfhe-rs-internal/issues/814
> chore: add parameters getters for CompactPublicKey types

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
> chore(gpu): panic if (k + 1)*l > 8 to avoid issue with tbc

- tfhe-zk-pok/src/proofs/pke.rs
- tfhe-zk-pok/src/proofs/pke_v2.rs
Test zk encryption with a wrong delta
> chore(zk): add a test with a bad delta for encryption

- .github/workflows/benchmark_gpu_integer_common.yml
- tfhe/benches/integer/bench.rs
- tfhe/benches/utilities.rs
> chore(gpu): reduce throughput integer bench time

- tfhe/src/high_level_api/array/gpu/booleans.rs
- tfhe/src/high_level_api/array/gpu/integers.rs
- tfhe/src/high_level_api/array/gpu/mod.rs
- tfhe/src/high_level_api/array/mod.rs
- tfhe/src/high_level_api/array/tests/booleans.rs
- tfhe/src/high_level_api/array/tests/mod.rs
- tfhe/src/high_level_api/array/tests/signed.rs
- tfhe/src/high_level_api/array/tests/unsigned.rs
- tfhe/src/high_level_api/global_state.rs
- tfhe/src/lib.rs
> feat(gpu): add gpu array type in hl api

- tfhe/docs/getting_started/benchmarks/gpu_benchmarks.md
Replaced with the right link for GitBook rendering
> chore(docs): fix the bench table

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
> fix(gpu): fix equal

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
> chore(gpu): remove stream sync in broadcast lut

- tfhe/docs/guides/run_on_gpu.md
> doc(gpu): add an example to use arrays on GPU

- .github/workflows/benchmark_gpu_erc20.yml
- .github/workflows/benchmark_gpu_integer.yml
- ci/slab.toml
> chore(gpu): add sxm5 vm target

- .github/workflows/benchmark_gpu_erc20_common.yml
- .github/workflows/benchmark_gpu_integer_common.yml
> chore(gpu): make artifact name unique across different machines

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
> fix(gpu): fix lut size in are_all_comparison_blocks_true

- tfhe/src/integer/gpu/server_key/radix/mod.rs
Fix noise level calculation after full propagation.
> fix(gpu): fix noise level calculation in full propagation

- tfhe/benches/high_level_api/erc20.rs
> chore(gpu): add inputs to erc20 throughput bench with multiple GPUs

- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- tfhe/src/high_level_api/array/mod.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_vector_comparisons.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_vector_comparisons.rs
- tfhe/src/integer/gpu/server_key/radix/vector_comparisons.rs
- tfhe/src/integer/gpu/server_key/radix/vector_find.rs
> feat(gpu): implement vector comparisons gpu

- backends/tfhe-cuda-backend/Cargo.toml
- tfhe/Cargo.toml
> chore(gpu): bump backend version

- tfhe/docs/README.md
> chore(docs): update discord link

- tfhe/src/core_crypto/algorithms/test/noise_distribution/mod.rs
> chore(test): modify cpu multi-bit parameters for noise test

- tfhe/docs/fundamentals/serialization.md
- tfhe/docs/getting_started/benchmarks/cpu_benchmarks.md
- tfhe/docs/getting_started/benchmarks/gpu_benchmarks.md
- tfhe/docs/getting_started/benchmarks/summary.md
- tfhe/docs/getting_started/benchmarks/zk_proof_benchmarks.md
- tfhe/docs/getting_started/operations.md
- tfhe/docs/getting_started/security_and_cryptography.md
- tfhe/docs/guides/overflow_operations.md
> chore(doc): update links to the benchmark tables

- tfhe/src/core_crypto/gpu/mod.rs
> chore(gpu): update new_multi_gpu() description

- tfhe/docs/getting_started/security_and_cryptography.md
- tfhe/docs/guides/strings.md
- tfhe/docs/references/fine-grained-apis/boolean/parameters.md
- tfhe/docs/references/fine-grained-apis/shortint/parameters.md
> chore(docs): fix various issues with the docs

- tfhe/docs/guides/run_on_gpu.md
Follows https://github.com/zama-ai/tfhe-rs/pull/1977.
> chore(docs): Remove mention to NVLink

- .github/workflows/gpu_4090_tests.yml
- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_fast_tests.yml
- .github/workflows/gpu_full_h100_tests.yml
- .github/workflows/gpu_full_multi_gpu_tests.yml
- .github/workflows/gpu_pcc.yml
- .github/workflows/gpu_signed_integer_classic_tests.yml
- .github/workflows/gpu_signed_integer_h100_tests.yml
- .github/workflows/gpu_signed_integer_tests.yml
- .github/workflows/gpu_unsigned_integer_classic_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
- .github/workflows/gpu_unsigned_integer_tests.yml
> chore(gpu): shorten workflow names

- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
> fix(integer): fix a typo in a comment

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
> fix(gpu): fix noise/degree bug

- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
> chore(gpu): refactor small scalar mul to keep track of degree and noise changes

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_bitops.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cu
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/integer/gpu/ciphertext/info.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/rotate.rs
- tfhe/src/integer/gpu/server_key/radix/shift.rs
> chore(gpu): refactor shift and rotate to keep track of degree and noise changes

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
> fix(gpu): fix degree after shift/rotate

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_shift.rs
> chore(gpu): refactor arithmetic scalar shift

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
> chore(gpu): remove unused variables

- tfhe/src/high_level_api/booleans/base.rs
> feat(gpu): enable if then else for boolean ciphertexts in hlapi

- tfhe/src/high_level_api/integers/signed/ops.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2085)
> feat(gpu): enable signed division in high level api

- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
> fix(gpu): fix wrong assert in division

- tfhe/src/integer/gpu/server_key/radix/mod.rs
> fix(gpu): fix wrong number of blocks used in cast

- backends/tfhe-cuda-backend/README.md
> chore(gpu): update backend readme

- tfhe/docs/integration/js_on_wasm_api.md
The example was still using CompactFheUint32List
which as been removed in favor of the more generic CompactCiphertextList
closes https://github.com/zama-ai/tfhe-rs-internal/issues/798
> docs(js): update JS example

- .github/workflows/gpu_4090_tests.yml
> chore(gpu): increase 4090 test timeout

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/cuda/src/types/complex/operations.cuh
> chore(gpu): replace asserts with panic

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/high_level_api/integers/signed/encrypt.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_comparison.rs
Solves https://github.com/zama-ai/tfhe-rs-internal/issues/927
> fix(gpu): fix scalar comparisons with 1 block

- README.md
backport of README update for the handbook
> docs: add link in the README

- tfhe/docs/getting_started/benchmarks/gpu/README.md
- tfhe/docs/getting_started/benchmarks/gpu/gpu_integer_operations.md
- tfhe/docs/getting_started/benchmarks/gpu/gpu_programmable_bootstrapping.md
> chore(gpu): fix typo in doc

- tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
- tfhe/src/core_crypto/gpu/vec.rs
> feat(gpu): add a function to set a CudaLweList to 0

- backends/tfhe-cuda-backend/cuda/src/types/complex/operations.cuh
refactor double2 operators to use cuda intrinsics
> refactor(gpu): refactor double2 operators to use cuda intrinsics

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
> chore(gpu): refactor full propagation to track noise / degree

- tfhe/examples/utilities/generates_test_keys.rs
- tfhe/src/keycache/mod.rs
> chore: pre-generate keyswitching keys for shortint tests

- Cargo.toml
- Makefile
- apps/trivium/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2178)
> chore: remove trivium from main workspace

- tfhe/src/shortint/server_key/mul.rs
> fix: a shortint docstring had values not matching the explanation

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/benchmark_tfhe_zk_pok.yml
- .github/workflows/benchmark_wasm_client.yml
- .github/workflows/benchmark_zk_pke.yml
- .github/workflows/cargo_test_fft.yml
- .github/workflows/cargo_test_ntt.yml
- .github/workflows/code_coverage.yml
- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_fast_tests.yml
- .github/workflows/gpu_full_multi_gpu_tests.yml
- .github/workflows/gpu_signed_integer_classic_tests.yml
- .github/workflows/gpu_signed_integer_h100_tests.yml
- .github/workflows/gpu_signed_integer_tests.yml
- .github/workflows/gpu_unsigned_integer_classic_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
- .github/workflows/gpu_unsigned_integer_tests.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2182)
> chore(ci): pin changed files action to a sha1 corresponding to a tag

- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
Bug introduced in this commit: 5258acc08fe2ff29744
> fix(gpu): fix bug introduced when reworking host_compare_with_zero

- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
> fix(gpu): fix corner case in sum ctxt

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/include/pbs/pbs_multibit_utilities.h
- backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
- backends/tfhe-cuda-backend/cuda/include/pbs/programmable_bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
> chore(gpu): supress warnings in pcc_gpu

- tfhe/src/integer/server_key/radix_parallel/cmux.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_cmux.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_cmux.rs
Add variants of CMUX where one or two of the possible output values are clear
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2181)
> feat(integer): add scalar cmux

- backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
> chore(gpu): relax too strict condition in copy slice

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
> chore(gpu): detect if we are in first or last iter with template argument for split kernel multi-bit PBS

- tfhe/benches/high_level_api/erc20.rs
> chore(gpu): modify erc20 throughput bench for better multi-gpu performance

- tfhe/benches/utilities.rs
- fix num sms for pcie H100 VM
- reduce minimum loading to avoid oom error on mul 256-bit
> chore(gpu): fix integer throughput bench

- .github/workflows/gpu_full_multi_gpu_tests.yml
> chore(gpu): reduce test threads for multi-gpu tests

- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/high_level_api/integers/signed/base.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
- tfhe/src/high_level_api/prelude.rs
- tfhe/src/high_level_api/traits.rs
- tfhe/src/integer/server_key/radix_parallel/cmux.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_cmux.rs
The current IfThenElse trait was too restrictive
to be able to use it to add these methods so a new trait was added.
This trait uses method name with the scalar prefix to avoid conflicts and avoid introducing breaking changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2208)
> feat(hlapi): add scalar cmux

- tfhe/src/core_crypto/commons/numeric/mod.rs
- tfhe/src/core_crypto/commons/numeric/signed.rs
- tfhe/src/core_crypto/commons/numeric/unsigned.rs
- tfhe/src/high_level_api/array/mod.rs
- tfhe/src/high_level_api/array/traits.rs
- tfhe/src/high_level_api/prelude.rs
- tfhe/src/integer/bigint/algorithms.rs
- tfhe/src/integer/bigint/static_unsigned.rs
- tfhe/src/integer/bigint/u256.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_dot_prod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_dot_prod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_dot_prod.rs
Add function do compute a dot product between a vector of encrypted boolean values and a vector of clear values
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2195)
> feat(integer): boolean_scalar_dot_prod

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
> fix(gpu): update panic condition to apply only to tbc

- scripts/integer-tests.sh
> chore(gpu): decrease test threads for small instances

- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/benches/core_crypto/ks_pbs_bench.rs
- tfhe/benches/core_crypto/pbs128_bench.rs
- tfhe/benches/core_crypto/pbs_bench.rs
- tfhe/benches/utilities.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- tfhe/src/core_crypto/algorithms/test/params.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping_128.rs
- tfhe/src/core_crypto/gpu/entities/lwe_bootstrap_key.rs
- tfhe/src/core_crypto/keycache.rs
- tfhe/src/integer/gpu/server_key/mod.rs
> feat(gpu): add drift to 128-bit pbs tests

- tfhe/docs/_static/cpu_gpu_integer_benchmark_fheuint64_tuniform_2m64_ciphertext.svg
- tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m64_ciphertext.svg
- tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m64_plaintext.svg
- tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m64_ciphertext.svg
- tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m64_plaintext.svg
- tfhe/docs/_static/gpu_pbs_benchmark_tuniform_2m128.svg
- tfhe/docs/_static/gpu_pbs_benchmark_tuniform_2m40.svg
- tfhe/docs/configuration/run_on_gpu.md
- tfhe/docs/getting_started/benchmarks/cpu/README.md
- tfhe/docs/getting_started/benchmarks/cpu/cpu_integer_operations.md
- tfhe/docs/getting_started/benchmarks/cpu/cpu_programmable_bootstrapping.md
- tfhe/docs/getting_started/benchmarks/gpu/gpu_programmable_bootstrapping.md
- tfhe/docs/getting_started/benchmarks/zk_proof_benchmarks.md
- tfhe/docs/tutorials/multi_gpu_device_selection.md
- tfhe/src/test_user_docs.rs
> doc(gpu): update documentation for v1.1 release

- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/983
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2250)
> chore(gpu): update parameter sets in the C++ test/benchmark tools

- .github/workflows/benchmark_gpu.yml
- Makefile
> chore(gpu): add bench command for zk-pok in workflow

- tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/strings/ciphertext.rs
- tfhe/src/strings/test_functions/test_compression.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/982
> fix(integer): handles compression of empty ct in empty list

- tfhe/docs/README.md
cc @samcrx to see if the description suits you
> docs: add handbook reference

- tfhe/benches/integer/zk_pke.rs
- tfhe/src/integer/ciphertext/compact_list.rs
- tfhe/src/integer/gpu/zk/mod.rs
- tfhe/src/shortint/parameters/aliases.rs
- tfhe/src/shortint/parameters/v1_1/key_switching/p_fail_2_minus_128/ks_pbs_gpu.rs
- tfhe/src/shortint/parameters/v1_1/key_switching/p_fail_2_minus_128/mod.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/985
> chore(gpu): add multi-bit parameters to be used with ZK's expand

- scripts/integer-tests.sh
This should fix the out of memory errors we sometimes see in HL API tests on multiple GPUs.
> chore(gpu): reduce test threads for small instances case

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
> chore(gpu): remove unused events for carry prop

- tfhe/docs/fhe-computation/operations/arithmetic-operations.md
This error isn't caught by typos-cli tool.
> docs: fix typo

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/crypto/gadget.cuh
- backends/tfhe-cuda-backend/cuda/src/crypto/ggsw.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
`synchronize_threads_in_block()` becomes `__syncthreads()` . This simplifies things.
> chore(gpu): removes the alias synchronize_threads_in_block()

- tfhe/src/core_crypto/backward_compatibility/entities/compressed_modulus_switched_lwe_ciphertext.rs
- tfhe/src/core_crypto/commons/ciphertext_modulus.rs
- tfhe/src/core_crypto/entities/compressed_modulus_switched_glwe_ciphertext.rs
- tfhe/src/core_crypto/entities/compressed_modulus_switched_lwe_ciphertext.rs
- tfhe/src/core_crypto/entities/compressed_modulus_switched_multi_bit_lwe_ciphertext.rs
- tfhe/src/core_crypto/entities/packed_integers.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/shortint/ciphertext/compressed_ciphertext_list.rs
remove some pub(crates) in core
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2288)
> chore(core): remove some pub(crate) in structs

- CONTRIBUTING.md
- README.md
- tfhe/docs/configuration/parallelized_pbs.md
- tfhe/docs/fhe-computation/compute/parameters.md
- tfhe/docs/references/fine-grained-apis/integer/operations.md
- tfhe/docs/references/fine-grained-apis/shortint/README.md
closes: 
Navigating section links by intended caption
> docs: update section links

- tfhe/docs/getting_started/benchmarks/README.md
- tfhe/docs/getting_started/benchmarks/cpu/README.md
- tfhe/docs/getting_started/benchmarks/cpu/cpu_integer_operations.md
- tfhe/docs/getting_started/benchmarks/cpu/cpu_programmable_bootstrapping.md
> docs(all): add hardware description in the summary bench page

- tfhe/examples/utilities/shortint_key_sizes.rs
- tfhe/src/core_crypto/algorithms/lwe_keyswitch_key_generation.rs
- tfhe/src/core_crypto/algorithms/test/lwe_keyswitch_key_generation.rs
- tfhe/src/core_crypto/entities/seeded_lwe_keyswitch_key.rs
- tfhe/src/integer/gpu/server_key/mod.rs
- tfhe/src/integer/server_key/mod.rs
- tfhe/src/shortint/atomic_pattern/compressed/ks32.rs
- tfhe/src/shortint/atomic_pattern/compressed/mod.rs
- tfhe/src/shortint/atomic_pattern/compressed/standard.rs
- tfhe/src/shortint/atomic_pattern/mod.rs
- tfhe/src/shortint/atomic_pattern/standard.rs
- tfhe/src/shortint/backward_compatibility/atomic_pattern.rs
- tfhe/src/shortint/backward_compatibility/server_key/mod.rs
- tfhe/src/shortint/backward_compatibility/server_key/modulus_switch_noise_reduction.rs
- tfhe/src/shortint/engine/server_side.rs
- tfhe/src/shortint/key_switching_key/mod.rs
- tfhe/src/shortint/server_key/compressed.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2311)
> feat(shortint): add CompressedAtomicPatternServerKey

- .github/workflows/benchmark_dex.yml
- .github/workflows/benchmark_gpu_dex.yml
> chore(bench): update pbs count parsing in dex benchmark

- tfhe-benchmark/benches/high_level_api/dex.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2315)
> chore(gpu): parallelize dex bench

- .github/workflows/benchmark_gpu.yml
- .github/workflows/benchmark_gpu_dex.yml
- .github/workflows/benchmark_gpu_erc20.yml
> chore(gpu): add hardware types for gpu bench

- tfhe/src/high_level_api/gpu_utils.rs
- tfhe/src/high_level_api/integers/signed/ops.rs
- tfhe/src/high_level_api/integers/signed/scalar_ops.rs
- tfhe/src/high_level_api/integers/signed/tests/gpu.rs
- tfhe/src/high_level_api/integers/unsigned/ops.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
- tfhe/src/high_level_api/prelude.rs
- tfhe/src/high_level_api/traits.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
- tfhe/src/integer/gpu/server_key/radix/sub.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2309)
> feat(gpu): add memory tracking functions for add/sub and scalar add/sub

- tfhe-benchmark/src/params.rs
- tfhe-benchmark/src/utilities.rs
fix build in tfhe-benchmark: shortint without internal-keycache and gpu without integer
> fix(bench): compilation error without the internal-keycache feature

- backends/tfhe-hpu-backend/Cargo.toml
Fix tags and dependencies in Cargo.toml for publication
> chore(hpu): fix Cargo.toml for release

- tfhe-benchmark/benches/integer/zk_pke.rs
Heuristic based on PBS count was flawed since a ZK verification operation will eat up to 32 threads on the machine. 
The previous heuristic could generate an input data vector way bigger than the total of threads divided by 32. 
This in turn lead to long execution time for benchmark and generate bad results.
> chore(bench): add suitable heuristic for zk throughput

- tfhe/src/high_level_api/integers/signed/ops.rs
- tfhe/src/high_level_api/integers/signed/scalar_ops.rs
- tfhe/src/high_level_api/integers/signed/tests/gpu.rs
- tfhe/src/high_level_api/integers/unsigned/ops.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
- tfhe/src/high_level_api/prelude.rs
- tfhe/src/high_level_api/traits.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
> feat(gpu): add memory tracking functions for bitops

- tfhe/examples/regex_engine/engine.rs
- tfhe/src/core_crypto/commons/math/decomposition/decomposer.rs
> chore: remove raw decomposition

- tfhe-benchmark/benches/core_crypto/ks_bench.rs
- tfhe-benchmark/src/params.rs
> fix(gpu): fix pbs and ks benchmark

- tfhe/docs/configuration/hpu_acceleration/run_on_hpu.md
minor changes to make the example in HPU doc ready for compilation & run
> fix(doc): hpu example was not compiling

- tfhe/src/integer/gpu/mod.rs
> fix(gpu): fix degrees after abs

- backends/tfhe-cuda-backend/cuda/include/ciphertext.h
- backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
- backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
- backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cu
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/core_crypto/gpu/algorithms/test/modulus_switch_noise_reduction.rs
- tfhe/src/core_crypto/gpu/mod.rs
> fix(gpu): add indexes to modulus switch noise reduction

- backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
> fix(gpu): fix the internal benchmark

- tfhe/src/high_level_api/integers/signed/ops.rs
- tfhe/src/high_level_api/integers/signed/scalar_ops.rs
- tfhe/src/high_level_api/integers/signed/tests/gpu.rs
- tfhe/src/high_level_api/integers/unsigned/ops.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
- tfhe/src/high_level_api/prelude.rs
- tfhe/src/high_level_api/traits.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/comparison.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
> feat(gpu): add memory tracking functions for comparisons

- .github/workflows/gpu_full_multi_gpu_tests.yml
- Makefile
- scripts/integer-tests.sh
> chore(gpu): fix oom error in ci

- tfhe-benchmark/benches/high_level_api/dex.rs
> Add dex throughput benchmarks

- Makefile
- tfhe/src/high_level_api/compact_list.rs
Fix another build issue with hpu, gpu and zk.
I return an error for the HPU case
A panic is imo not a good idea since it is used in deserialisation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2371)
> fix(gpu): build with hpu and zk features

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
> fix(gpu): fix hardcoded use of message modulus

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/cast.cu
- backends/tfhe-cuda-backend/cuda/src/integer/cast.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/integer/gpu/ciphertext/info.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
> refactor(gpu): moving trim_radix_blocks_lsb_async to backend

- backends/tfhe-cuda-backend/cuda/include/zk/zk_utilities.h
- tfhe/src/high_level_api/compact_list.rs
- tfhe/src/integer/gpu/ciphertext/compact_list.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/1024 and https://github.com/zama-ai/tfhe-rs-internal/issues/1006
> fix(gpu): fix race condition on expand when on multi-gpu

- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
> fix(gpu): fix the packing keyswitch buffer not being allocated on large parameter sets

- backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
- backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
> refactor(gpu): return trivial indexes after ms noise reduction

- .github/workflows/data_pr_close.yml
This refactor simplifies reading of data_pr_close workflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2430)
> chore(ci): use gh cli instead of api calls done with curl

- tfhe-csprng/Cargo.toml
- tfhe/Cargo.toml
Some (breaking) changes were made to a trait in CSPRNG
> chore(csprng): bump to 0.6.0

- .github/workflows/make_release_cuda.yml
- backends/tfhe-hpu-backend/src/interface/memory/huge.rs
> chore(ci): add missing env variable in cuda release workflow

- tfhe/src/high_level_api/integers/signed/tests/gpu.rs
- tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
> refactor(gpu): moving get_scalar_div_size_on_gpu to backend and fixing gpu tests

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
- backends/tfhe-cuda-backend/cuda/src/utils/helper.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/ilog2.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
Reimplements sum_ciphertexts_in_vec operation and optimizes it.
> refactor(gpu): optimize sum_ciphertexts in cuda backend

- tfhe/src/integer/server_key/radix_parallel/div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_div_mod.rs
The improvement is to compute the quotient digit by digit and not bit by bit.
This could also probably work for 3_3 and 4_4 but it is not a priority
This brings the 64bits division down to ~5.5s from 8.6s
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2436)
> feat: improve division for 2_2 parameters

- backends/tfhe-hpu-backend/src/ffi/v80/ami.rs
- backends/tfhe-hpu-backend/src/ffi/v80/mod.rs
- setup_hpu.sh
Also enhance error handling related to user misconfiguration. And remove a bug with ami devn reading
> fix(hpu): Remove some hardcoded filename in tandem

- Makefile
- tfhe-zk-pok/src/backward_compatibility/pke_v2.rs
- tfhe-zk-pok/src/proofs/pke.rs
- tfhe-zk-pok/src/proofs/pke_v2/hashes.rs
- tfhe-zk-pok/src/proofs/pke_v2/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2462)
> feat(zk): add compact hash mode for zkv2

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/high_level_api/integers/signed/tests/gpu.rs
- tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
> refactor(gpu): moving unchecked_scalar_div_async to backend

- backends/tfhe-hpu-backend/Cargo.toml
- tfhe/Cargo.toml
Update tfhe-hpu-backend version
> chore(hpu): bump backend version

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
> chore(gpu): remove template from sum ciphertexts, add two missing delete

- tfhe/src/test_user_docs.rs
---
**Description:**  
This pull request corrects a minor typo in the section header from `CONFGIURATION` to `CONFIGURATION` in the `test_user_docs.rs` file.
> Fix Typo in CONFIGURATION Section Header

- tfhe/src/shortint/client_key/mod.rs
closes: https://github.com/zama-ai/tfhe-rs/issues/2495
> chore(shortint): make `decrypt_no_decode` public

- tfhe/docs/fhe-computation/advanced-features/noise-squashing.md
> docs: describe noise squashed compression

- tfhe/docs/SUMMARY.md
- tfhe/docs/configuration/gpu_acceleration/array_type.md
- tfhe/docs/configuration/gpu_acceleration/benchmark.md
- tfhe/docs/configuration/gpu_acceleration/compressing_ciphertexts.md
- tfhe/docs/configuration/gpu_acceleration/gpu_operations.md
- tfhe/docs/configuration/gpu_acceleration/multi_gpu.md
- tfhe/docs/configuration/gpu_acceleration/run_on_gpu.md
- tfhe/docs/configuration/gpu_acceleration/simple_example.md
- tfhe/docs/configuration/gpu_acceleration/zk-pok.md
- tfhe/docs/getting_started/benchmarks/README.md
- tfhe/docs/getting_started/benchmarks/cpu/cpu_integer_operations.md
- tfhe/src/test_user_docs.rs
Implements documentation changes https://github.com/zama-ai/tfhe-rs-internal/issues/1041
**Adds a new section in the TOC: Hardware acceleration under which GPU & HPU are moved**
Major changes
- advantages over CPU: a paragraph is added for the speedup
- main page: maybe some aesthetic changes to make the page more attractive: moved the example to a new page
- summary on main page: features, cryptographic parameters and design principles
- API references on each page
- rephrased some parts for clarity
- Adds the updated ZK-POK page
> feat(gpu): update GPU documentation

- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_div_mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_div_mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_add.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_bitwise_op.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_div_mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_ilog2.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_mul.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_rotate.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_div_mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_mul.rs
> chore(gpu): reduce ci time by reducing testing of unused parameters

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
> refactor(gpu): moving signed_scalar_div_rem to the backend

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
> fix(gpu): fix pbs128 multi-gpu bug

- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
> chore(gpu): minor refactor in sum ctxt

- tfhe-benchmark/benches/integer/zk_pke.rs
> fix(gpu): reduces number of elements in the ZK throughput benchmark

- tfhe-benchmark/benches/high_level_api/erc20.rs
- transfers for the GPU case should be measured using sequential operations (without rayon!)
This PR partially revert commit fd79c4f97208ce93dfb95944a53a7b69cd0ea711
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/1051
> fix(gpu): fix regression on ERC20 throughput

- .github/workflows/gpu_signed_integer_tests.yml
- .github/workflows/gpu_unsigned_integer_tests.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2557)
> chore(gpu): remove nightly schedule now that ci is lighter

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
> refactor(gpu): creating CudaScalarDivisorFFI for storing decomposed scalars and their metadata

- backends/tfhe-cuda-backend/build.rs
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/subtraction.cuh
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cu
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/1063
> chore(gpu): add checks on noise levels in debug mode

- tfhe/src/core_crypto/commons/generators/seeder.rs
corrected typo in comment section in `tfhe/src/core_crypto/commons/generators/seeder.rs`
> fix: fix typo in word "implementor"

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
> fix(gpu): fixes some wrong indexes used in cuda_set_device()

- .github/actions/gpu_setup/action.yml
- .github/workflows/gpu_code_validation_tests.yml
- Makefile
- backends/tfhe-cuda-backend/cuda/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cu
- scripts/check_memory_errors.sh
Adds a new CI workflow that performs:
- compile warnings checking for GPU code
- running HL API tests with compute-santitizer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2577)
> feat(gpu): utility debug workflows in ci

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
> fix(gpu): fix inconsistent types

- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_mul.rs
> chore(gpu): add corner case test for mul

- backends/tfhe-cuda-backend/cuda/src/utils/helper_profile.cuh
> fix(gpu): update soon deprecated version nvtx

- .github/actions/gpu_setup/action.yml
Make sure the requested gcc version is installed
> chore: install & check gcc when needed

- backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cu
- backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
> chore(gpu): change multi gpu logic

- backends/tfhe-cuda-backend/cuda/src/crypto/gadget.cuh
> fix: wrong include guard's name

- .github/workflows/aws_tfhe_noise_checks.yml
also change notification logic to warn if the overall result is not success
> chore: fix noise checks timeout again as there are TWO timeout locations

- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_fast_tests.yml
- .github/workflows/gpu_full_h100_tests.yml
- .github/workflows/gpu_full_multi_gpu_tests.yml
- .github/workflows/gpu_integer_long_run_tests.yml
- .github/workflows/gpu_signed_integer_classic_tests.yml
- .github/workflows/gpu_signed_integer_h100_tests.yml
- .github/workflows/gpu_signed_integer_tests.yml
- .github/workflows/gpu_unsigned_integer_classic_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
- .github/workflows/gpu_unsigned_integer_tests.yml
Using the mps service we see a 2x improvement in the testing times
> chore(gpu): enable nvidia mps in long run tests

- .github/workflows/make_release.yml
- .github/workflows/make_release_cuda.yml
- .github/workflows/make_release_hpu.yml
- .github/workflows/make_release_tfhe_csprng.yml
- .github/workflows/make_release_tfhe_fft.yml
- .github/workflows/make_release_tfhe_ntt.yml
- .github/workflows/make_release_tfhe_versionable.yml
- .github/workflows/make_release_zk_pok.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2651)
> chore(ci): use crates.io trusted publishing feature

- tfhe/src/core_crypto/algorithms/glwe_encryption.rs
- tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/1089#issue-3341747897
> chore(core): add len checks for polynomial lists

- backends/tfhe-hpu-backend/config_store/v80/README.md
- backends/tfhe-hpu-backend/src/ffi/sim/ipc.rs
- tfhe/src/core_crypto/algorithms/slice_algorithms.rs
Copy of https://github.com/zama-ai/tfhe-rs/pull/2602
> chore(gpu): fix typos

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/src/crypto/ggsw.cuh
- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/crypto/packing_keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/cast.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/zk/zk.cuh
Adds two macros:
- GPU_ASSERT : to be used for logic assumption checking | will be disabled in production
- PANIC_IF_ELSE: to be used to check caller provided values are sane | will run in production
> chore(gpu): add assert macro

- .github/workflows/coprocessor-benchmark-gpu.yml
To fix the failing CI  step for coprocessor integration https://github.com/zama-ai/tfhe-rs/actions/runs/17234735267/job/48897429161
> chore(gpu): fix coprocessor bench

- tfhe-fft/src/dif16.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/1092
The code was copy pasted from [tfhe-fft/src/dif8.rs](https://github.com/zama-ai/tfhe-rs/blob/f776c737a18c8f9e74cbb89aa3ab6727933303bb/tfhe-fft/src/dif8.rs#L104) and has not been removed.
> chore(fft): remove dead store in stockham dif16

- backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/include/zk/zk_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/oprf.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_bitops.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
This PR improves the communications:
- when involve non-trivial indexes.
- fixes multiplication
- broadcast luts only to the involved gpus.
- broadcast only lut indexes.
- remove useless synchronizations, use events when needed.
> feat(gpu): improve communication scheme

- tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
- tfhe/src/high_level_api/booleans/squashed_noise.rs
- tfhe/src/high_level_api/compressed_noise_squashed_ciphertext_list.rs
- tfhe/src/high_level_api/integers/signed/squashed_noise.rs
- tfhe/src/high_level_api/integers/unsigned/squashed_noise.rs
- tfhe/src/high_level_api/keys/inner.rs
- tfhe/src/high_level_api/keys/server.rs
- tfhe/src/integer/ciphertext/compressed_noise_squashed_ciphertext_list.rs
- tfhe/src/integer/gpu/ciphertext/compressed_noise_squashed_ciphertext_list.rs
- tfhe/src/integer/gpu/ciphertext/squashed_noise.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/955
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2676)
> feat(gpu): implement support for 128-bit compression on the HL API

- .github/workflows/cargo_test_ntt.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2733)
> chore(ci): configure tfhe-ntt tests to have an avx512 + IFMA instance

- tfhe-benchmark/benches/integer/bench.rs
- tfhe/src/integer/server_key/radix_parallel/cmux.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_cmux.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_cmux.rs
Add the flip(condition: BooleanBlock, a: T, b: T) -> (T, T) operation that homomorphically flip/swap two values if the given encrypted boolean encrypts true
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2741)
Fixes https://github.com/zama-ai/tfhe-rs/pull/2741
> feat(integer): add flip operation

- tfhe/src/c_api/high_level_api/keys.rs
Fixes https://github.com/zama-ai/tfhe-rs/issues/2706
> fix(c-api): add missing safe_deser for ServerKey

- .github/workflows/coprocessor-benchmark-gpu.yml
- .github/workflows/gpu_full_multi_gpu_tests.yml
- .github/workflows/gpu_integer_long_run_tests.yml
- Makefile
- backends/tfhe-cuda-backend/cuda/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/src/device.cu
- ci/slab.toml
- Add custom machine when running the bench manually
- Cuda Profile in throughput mode using manual profiler start on set device
> fix(gpu): coprocessor bench

- .github/workflows/aws_tfhe_integer_tests.yml
> chore(ci): increase timeout to 8hours for unsigned integer tests

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- tfhe/src/high_level_api/booleans/oprf.rs
- tfhe/src/high_level_api/integers/oprf.rs
> Al/fix oprf on GPU

- backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
- backends/tfhe-cuda-backend/cuda/include/integer/compression/compression.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
Implements optimized division algorithm for message_2_carry_2 at least 4 gpus are available
> feat(gpu): Implements optimized division algorithm for message_2_carry_2

- tfhe/src/core_crypto/algorithms/lwe_keyswitch_key_generation.rs
- tfhe/src/core_crypto/commons/parameters.rs
- tfhe/src/high_level_api/compact_list.rs
- tfhe/src/high_level_api/keys/inner.rs
- tfhe/src/high_level_api/xof_key_set.rs
- tfhe/src/shortint/atomic_pattern/ks32.rs
- tfhe/src/shortint/atomic_pattern/mod.rs
- tfhe/src/shortint/atomic_pattern/standard.rs
- tfhe/src/shortint/backward_compatibility/key_switching_key.rs
- tfhe/src/shortint/client_key/atomic_pattern/ks32.rs
- tfhe/src/shortint/client_key/atomic_pattern/mod.rs
- tfhe/src/shortint/client_key/atomic_pattern/standard.rs
- tfhe/src/shortint/engine/server_side.rs
- tfhe/src/shortint/key_switching_key/mod.rs
- tfhe/src/shortint/parameters/ks32.rs
- tfhe/src/shortint/server_key/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2846)
> feat(shortint): add compact pke for the ks32 atomic pattern

- tfhe-benchmark/src/params.rs
- tfhe/src/shortint/parameters/v1_4/meta/cpu.rs
- tfhe/src/shortint/parameters/v1_4/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2864)
> chore(shortint): add metaparams for ks32

- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/high_level_api/integers/signed/base.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
- tfhe/src/shortint/atomic_pattern/mod.rs
- update From impl for conformance parameters to manage the AP params
> feat: make FheUint/FheInt/FheBool compatible with AP params for conformance

- tfhe-benchmark/benches/high_level_api/bench.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2869)
> chore: add cfg guards on kvstore bench
