- .github/workflows/boolean_benchmark.yml
- .github/workflows/shortint_benchmark.yml
- .github/workflows/start_benchmarks.yml
- ci/benchmark_parser.py
- ci/slab.toml
This workflow enables benchmarks automation. It will be called on each push in `main`, and with a workflow-dispatch capability if one wants to run all benchmarks in one go outside a PR.
> chore(ci): add workflow to trigger all benchmarks automatically

- tfhe/docs/shortint/operations.md
Fix the public key encryption example in the doc for shortint (issue 49).
> fix(doc): update pk encryption example for shortint

- .github/workflows/shortint_benchmark.yml
- ci/benchmark_parser.py
This fixes behavior for shortint benchmarks.
> chore(ci): parse subdirectories for shortint benchmark results

- scripts/get_arch_feature.sh
On Linux with Apple M1, the output of `uname -a` is:
```
Linux ... aarch64 aarch64 aarch64 GNU/Linux
```
Therefore, recognize that output as aarch64.
> fix(tools): fix arch detection script for aarch64

- .github/workflows/boolean_benchmark.yml
- .github/workflows/shortint_benchmark.yml
- Makefile
- ci/benchmark_parser.py
- tfhe/Cargo.toml
- tfhe/examples/boolean_key_sizes.rs
- tfhe/examples/shortint_key_sizes.rs
- tfhe/src/boolean/engine/bootstrapping.rs
- tfhe/src/shortint/server_key/mod.rs
I didn't found another way than making the struct public to expose the internals of the boolean server key.
Moreover, I didn't find a way to avoid having two for loops (one for boolean keys and one for shortint). I've tried to implement a function using a generic input argument to refactor the common code but without success.
For now, the measurement is not implemented in the workflow. I should probably create an independent workflow just for this task since it's measuring both boolean and shortint keys in one go, what do you think?
> Compute key sizes in benchmarks

- tfhe/src/core_crypto/algorithms/lwe_encryption.rs
- tfhe/src/core_crypto/commons/math/random/uniform_binary.rs
- tfhe/src/core_crypto/commons/math/random/uniform_ternary.rs
- tfhe/src/core_crypto/commons/math/torus/mod.rs
- enables the use of u128 in ciphertexts
- add encryption test based on shortint 2_2 params
> refactor(core): implement missing traits for u128/i128 to make them usable

- tfhe/Cargo.toml
closes https://github.com/zama-ai/tfhe-rs/issues/1
> chore(tfhe): upgrade csprng version to avoid indirect deprecated aes dep

- tfhe/Cargo.toml
closes https://github.com/zama-ai/tfhe-rs/issues/3
> chore(tfhe): bump criterion version to remove outdated dep from dep tree

- tfhe/src/core_crypto/algorithms/lwe_private_functional_packing_keyswitch_key_generation.rs
- add equivalence keygen test between serial and parallel as we now near exclusively use the parallel version ourselves
closes https://github.com/zama-ai/tfhe-rs/issues/108
> fix(core_crypto): correct PFPKSK serial generation

- .github/workflows/boolean_benchmark.yml
- .github/workflows/shortint_benchmark.yml
- .github/workflows/start_benchmarks.yml
- ci/benchmark_parser.py
- ci/slab.toml
This commit series makes `--throughput` CLI argument for benchmark result parser optional.
In addition an AWS Slab profile for PBS benchmarks had been added. It couldn't run without it... :sweat_smile:
> Compute throughput on boolean and shortint benchmarks

- tfhe/benches/core_crypto/pbs_bench.rs
When using a criterion sample size of 5000, the benchmark duration for PBS using shortint can be very long (3620s for MESSAGE_4_CARRY_4). Switching to a sample size of 2000 would cut down all of the benchmarks duration by a factor of at least 2.
> chore(ci): reduce pbs benchmark execution duration

- .github/workflows/sync_on_push.yml
Enforcing usage of fine-grained token means that a token always have an expiration date. Thus it must be update fromp time to time. The seldom SYNC_DEST_REPO secrets would have contained such fine grained token. By spliting this seldom secret and using CONCRETE_ACTIONS_TOKEN there is no need to update SYNC_DEST_REPO each time the token is updated.
> chore(ci): split sync repo url into several secrets

- tfhe/src/core_crypto/algorithms/lwe_encryption.rs
- tfhe/src/core_crypto/fft_impl/math/fft/tests.rs
These overflows appeared in debug builds,
and are easly fixed by using explicit wrapping operation or correct values.
Fixes #136 (even tho running test in debug mode is not recommended)
> chore(core_crypto): fix overflows in tests

- tfhe/src/c_api/shortint/server_key/pbs.rs
- tfhe/src/shortint/engine/mod.rs
- tfhe/src/shortint/engine/server_side/bitwise_op.rs
- tfhe/src/shortint/engine/server_side/comp_op.rs
- tfhe/src/shortint/engine/server_side/div_mod.rs
- tfhe/src/shortint/engine/server_side/mod.rs
- tfhe/src/shortint/server_key/mod.rs
- tfhe/src/shortint/server_key/tests.rs
A bivariate PBS is a univariate PBS where we encode
the lhs, and rhs values into a singular value:
`univariate_value = (lhs * shift) + rhs`
Some places shifted the lhs by the parameter's message modulus
while others shifted by rhs.degree + 1, this could leed to incoherences
and wrong result in some cases.
The commits adds a `BivariateAccumulator` that stores the shift
value that was used to create the LUT, to avoid said incoherences.
Also, bivariate function family that expected
a univariate closure `Fn(u64) -> u64` will now expect a
bivariate closure `Fn(u64, u64) -> u64` so that they are less
error prone as the user does not need to figure out the
shift to be used.
> fix issue #115

- tfhe/src/integer/server_key/radix/scalar_add.rs
- tfhe/src/integer/server_key/radix/scalar_mul.rs
- tfhe/src/integer/server_key/radix/scalar_sub.rs
- tfhe/src/integer/server_key/radix/tests.rs
This only happens on binary scalar operations over 64bits of precision.
> fix(integer): stop decomposing before overflow

- Makefile
- tfhe/Cargo.toml
This adds the --all-targets to the cargo build commands invoked by the makefile so that when running
`make build_boolean`, lib, tests, benches, examples are built.
See the `cargo help build`
```
--all-targets
Build all targets. This is equivalent to specifying --lib --bins --tests --benches --examples.
```
> chore(makefile): add --all-targets switch to build command

- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
When working on the integer part of the crate,
if you introduced a compile error (as is common when working stuff out) the type inference of rust would not fully work and call to `let dec = cks.decrypt_radix(&ctxt);` would fail to deduce the type of `dec`.
This resulted on many errors in the compiler output about "type annotation needed", requiring to scroll up a certain amount to be able to see the errors messages you actually care about.
This commit adds these missing type annotation the the errors won't appear, so as to have less noise.
> chore(integer): annotate decrypt_radix type in tests

- tfhe/src/core_crypto/algorithms/lwe_keyswitch.rs
- tfhe/src/core_crypto/algorithms/lwe_keyswitch_key_generation.rs
- allows to avoid reversing the iterator, potentially improving cache access during a keyswitch
BREAKING CHANGE: the keyswitch key level order has been reversed
TODO: fix the mismatch between DecompositionTerm and DecompositionIter for the meaning of a decomposition level see
https://github.com/zama-ai/tfhe-rs-internal/issues/72
The same could be done for the PBS but the change is not wopbs friendly (kind of expected) and is a much more impacting change than this one
> chore(core): reverse the order in which we encrypt KS levels

- .github/workflows/boolean_benchmark.yml
- .github/workflows/integer_benchmark.yml
- .github/workflows/pbs_benchmark.yml
- .github/workflows/start_benchmarks.yml
- Makefile
- ci/benchmark_parser.py
- ci/slab.toml
- tfhe/Cargo.toml
- tfhe/benches/boolean/bench.rs
- tfhe/benches/core_crypto/pbs_bench.rs
- tfhe/benches/integer/bench.rs
- tfhe/benches/shortint/bench.rs
- tfhe/benches/utilities.rs
- tfhe/examples/boolean_key_sizes.rs
- tfhe/examples/shortint_key_sizes.rs
This is done to comply with the new Zama benchmark standard. Exhaustive parameters list is stored so once it's parsed and send to database, one can easily filter results on such parameters in visualization tool.
> chore(ci): record benchmarks parameters to be stored in database

- Makefile
This allows to invoke the Makefile with a cargo profile eg:
- `make CARGO_PROFILE=devo build_integer`
- `make CARGO_PROFILE=dev build_integer`
- `make CARGO_PROFILE=release build_integer`
By default still use release profile.
> chore(makefile): allow passing cargo profile

- tfhe/src/core_crypto/algorithms/test/lwe_linear_algebra.rs
- otherwise we are just checking that x.wrapping_sub(x) == 0
> chore(core): more reasonable LWE sub test

- tfhe/benches/shortint/bench.rs
First batch of default operations, it might miss some, just list the ones missing.
> chore(ci): add shortint default ops to benchmarks

- .gitignore
- tfhe/benches/integer/bench.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
- a product was overflowing, we now compute a progressive division with the same effect and stop once we reach zero to limit the number of generated tasks
> fix(integer): fix scalar mul bug when representing integers > 64 bits

- tfhe/src/integer/server_key/comparator.rs
- only extract assign message instead of doing a full propagate as carries are not supposed to be non zero (though the degree will have grown)
Cherry pick to get better peformance on 0.2.x
> chore(integer): restore empty carry check for default comparator tests

- tfhe/src/high_level_api/integers/types/static_.rs
The FheUint32 was wrongly defined as being 32 blocks of 2 bits when it should have been 16 blocks.
> fix(hlapi): use correct number of blocks for FheUint32

- tfhe/docs/getting_started/benchmarks.md
> chore(doc): updated benchmarks for min to reflect the fix done to min/max

- tfhe/benches/boolean/bench.rs
- tfhe/benches/core_crypto/pbs_bench.rs
- tfhe/benches/integer/bench.rs
- tfhe/benches/shortint/bench.rs
- tfhe/benches/utilities.rs
- tfhe/examples/boolean_key_sizes.rs
- tfhe/examples/shortint_key_sizes.rs
Decomposition basis wasn't correctly set to handle CRT. Now it uses a Vec that would be displayed as a string in the database. In addition the bit size has been added to ease comparison between various of them in Grafana.
> chore(ci): fix decomposition basis and add bit size to params

- .github/workflows/make_release.yml
This is done to be able to test the effective worklfow implementation in a development branch.
> chore(ci): create dummy release workflow

- tfhe/src/boolean/engine/mod.rs
- tfhe/src/boolean/engine/tests.rs
This new associated function allows to replace
the engine used in the thread.
> cherry-pick
> feat(boolean): add BooleanEngine::replace_thread_local

- .github/workflows/make_release.yml
- Makefile
This will perform automatic release on GitHub. It will append a CHANGELOG file that will be versioned. It will create a new version tag and create a release entry on GitHub along with all the changes in the same format as CHANGELOG.
> chore(ci): create release with semantic-release

- tfhe/src/core_crypto/commons/generators/encryption.rs
- tfhe/src/core_crypto/commons/math/random/generator.rs
- we still check we generate non zero values but add retry conditions or have less stringent checks, to allow some values to be zero for example as it's a valid value that can be generated
- each test suite (test and doctest) for these tests ran 1000 times without failure
> chore(core): change rng tests to better avoid false failures

- tfhe/benches/integer/bench.rs
- tfhe/src/integer/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix/shift.rs
- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
This reworks the left/right scalar shift method.
This new implementation takes more advantage of the
radix representation property and use a combo
of shifting/moving blocks via a rotate_left/right
optionnaly followed by in-block shifting and propagation
to other blocks.
This new implementation requires the carries to be empty
(not sure what the preconditions were for the previous implementation)
and the output will also have clean carries.
Requiring empty carries allows to do the shift in a way
that scales well with the number of blocks as we can use truly parallel
operations.
This means that the time required to shift is dependent
in the shift value, which should not be a security problem
as its a clear value. (The previous implementation also
had timing that depended on the shift value) …
> feat(integer): improve scalar shifts performances

- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/rotate.rs
- tfhe/src/integer/server_key/radix_parallel/shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
Like shifts, rotates are implemented by combining
a rotation of the block and bivariate PBSs in case the rotation number `n` is not a multiple of the number of bits in a block.
Since the behaviour of rotations is to 'cycle' bits back the end/beginning of the 'bit slice' (i.e. no bits is ever lost like it can with shifts), the performance is always the same when (n % nb_bits_in block) != 0. However the implementation is simpler.
So assuming a machine where the number of threads
is >= to the ciphertext's number of block, the operation cost one bivariate PBS.
closes #145
> feat(integer): add parallelized scalar rotate_left/right

- tfhe/c_api_tests/test_high_level_256_bits.c
- tfhe/docs/high_level_api/operations.md
- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/high_level_api/integers/tests.rs
- tfhe/src/high_level_api/integers/types/base.rs
requires:
This adds the casting of integer types.
Downcasting truncates blocks.
Upcasting appends 0s
Casting is done via the introduced `cast_from` associated
function and the `cast_into` method. They are the equivalent of
the `From` and `Into` traits.
It was not possible to implement casting by implementing the
standard `From` and `Into` traits as initially planned because:
```rust
impl<P1, P2> From<GenericInteger<P1>> for GenericInteger<P2>
where P1: IntegerParameter,
P2: Integer Parameter, {
fn from(_: GenericInteger<P1>) -> Self {
todo!()
}
}
```
As it conflicts the blanket impl found in the stdlib
`impl<T> From<T> for T;` as P1, P2 may be the same and we have no way
of telling the compiler to consider this impl only when P1 != P2.
So we had to create our own stuff
> hlapi casting

- ci/benchmark_parser.py
Since most of the operations are over 1 ms, there is no point to compute the number of operation per millisecond.
> chore(ci): compute throughput as operations per second

- tfhe/benches/core_crypto/pbs_bench.rs
It's the optimal value measured on an m6i.metal instance where we run the benchmarks.
See: https://zama.grafana.net/d/a60a669c-5199-4e26-bcd6-8a69d7bc97e5/misc-panels-to-help-team?orgId=1&from=1683712319833&to=1683885119833&var-branch=ci%2Fbench_multi_bits&var-messagemodulus=All&var-hardware=m6i.metal
> bench(multi-bit-pbs): hard set the number of threads to 10 for the multi-bit PBS

- tfhe/src/high_level_api/booleans/mod.rs
- tfhe/src/high_level_api/booleans/server_key.rs
- tfhe/src/high_level_api/booleans/types/static_.rs
- tfhe/src/high_level_api/details.rs
- tfhe/src/high_level_api/integers/keys.rs
- tfhe/src/high_level_api/integers/mod.rs
- tfhe/src/high_level_api/keys/client.rs
- tfhe/src/high_level_api/keys/mod.rs
- tfhe/src/high_level_api/keys/server.rs
- tfhe/src/high_level_api/mod.rs
- tfhe/src/high_level_api/shortints/mod.rs
- tfhe/src/high_level_api/shortints/server_key.rs
- tfhe/src/high_level_api/shortints/types/mod.rs
- tfhe/src/high_level_api/shortints/types/static_.rs
- tfhe/src/high_level_api/tests.rs
- tfhe/src/integer/mod.rs
- tfhe/src/integer/server_key/mod.rs
Now that WopPBS key are optional in the hlapi
we can have a CompressedServerKey.
If a user tries to create a CompressedServerKey
but has enabled function evaluation on integers
(WopPBS) then it will panic as WopPBS are not yet compressible. And 'stuffing' the non-compressed wopbs-key in the compressed server key, would defeat the purpose of compressed server key, as WopPBS key makes of for
the vast majority of the space used.
Also having CompressedServerKey is required to
be able to have wasm API of the hlapi
as wasm cannot generate normal server key.
> feat(hlapi): add CompressedServerKey

- Makefile
- tfhe/Cargo.toml
- tfhe/docs/regex/implementation-details.md
- tfhe/docs/regex/patterns.md
- tfhe/docs/regex/tutorial.md
- tfhe/examples/regex_engine/ciphertext.rs
- tfhe/examples/regex_engine/engine.rs
- tfhe/examples/regex_engine/execution.rs
- tfhe/examples/regex_engine/main.rs
- tfhe/examples/regex_engine/parser.rs
- tfhe/src/lib.rs
Most important locations:
- the tutorial is in `tfhe/docs/regex/tutorial.md`
- the example implementation is in `tfhe/src/regex/..`
Not quite sure if you want the example implementation to be under `tfhe/src` directly (how it is in this PR atm), or to have it be more of an external dependency (like how I initially had set it up in a separate repo). Let me know.
I might still want to add a `Further work` section at the end of the tutorial, and to add some comments to the code. But I think it's best to open this PR now to get the final review process started.
---
To run the included tests run: `cargo test --release --features=x86_64,integer --example regex_engine`.
> FHE Regex Pattern Matching Engine

- Makefile
- tfhe/Cargo.toml
- tfhe/docs/tutorial/dark_market.md
- tfhe/examples/dark_market.rs
This pull request solves the [Dark Market](https://github.com/zama-ai/bounty-program/blob/main/Bounties/Application/create-a-dark-market-app-tutorial.md) bounty.
Two file change has been made and two new files are added to the repository.
1. `tfhe/Cargo.toml` file has been updated to include the new example.
2. `tfhe/docs/SUMMARY.md` file has been changed to include links to the added Dark Market tutorial.
3. `tfhe/docs/tutorial/dark_market.md` file is added to describe how to implement the Dark Market algorithm with TFHE-rs.
4. `tfhe/examples/dark_market.rs` file is added that consists of three different implementations of the Dark Market algorithm: Plain, FHE and Parallelized FHE. These implementations can be run with the commands given in the tutorial.
Thank you so much
Yagiz
> doc(tfhe): add dark market example

- Makefile
- tfhe/Cargo.toml
- tfhe/docs/tutorial/sha256_bool.md
- tfhe/examples/sha256_bool/boolean_ops.rs
- tfhe/examples/sha256_bool/main.rs
- tfhe/examples/sha256_bool/padding.rs
- tfhe/examples/sha256_bool/sha256_function.rs
This is the updated PR with the squashed commits.
> docs(tfhe): add boolean sha256 tutorial

- tfhe/Cargo.toml
- tfhe/examples/regex_engine/ciphertext.rs
- tfhe/examples/regex_engine/engine.rs
- tfhe/examples/regex_engine/parser.rs
For whatever reason some backtrace feature gets enabled, remove anyhow we don't need it
> chore(tfhe): remove anyhow, just use Box<dyn std::error::Error>

- tfhe/src/high_level_api/integers/client_key.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/integer/block_decomposition.rs
- tfhe/src/integer/client_key/mod.rs
- tfhe/src/integer/client_key/radix.rs
- tfhe/src/integer/encryption.rs
- tfhe/src/integer/mod.rs
- tfhe/src/integer/public_key/compressed.rs
- tfhe/src/integer/public_key/standard.rs
- tfhe/src/integer/public_key/tests.rs
- tfhe/src/integer/server_key/comparator.rs
- tfhe/src/integer/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/u256.rs
This new implementation should hopefully be a little bit easier to understand.
But more importantly it is more general/generic,
the previous implementation required the input type to be able to be described as u64 words, the new one works for any type (as long as needed trait are implemented)
Also the new implementation is separated from the encryption code, meaning it will be usable by scalar operation, which will allow us to deduplicate code and start making scalar ops support scalar values that are on more than 64-bits.
> refactor(integer): improve decomposition/recomposition into blocks

- tfhe/src/shortint/ciphertext/mod.rs
- tfhe/src/shortint/engine/server_side/mod.rs
This PR provides CiphertextBase with functions to convert from a generic type OpOrder to a specific struct.
This allows removing all calls to std::mem::transmute in shortint/engine/server_side/mod.rs, isolating unsafe blocks in the conversion functions. This makes the code safer and more likely to panic! in case of an error.
This means when you have a function `my_fun` that takes a `CiphertextBase<KeyswitchBootstrap>` and you only have a `CiphertextBase<OpOrder: PBSO0rderMarker>` that you know to be the right type, you can just do `my_fun(ct.to_concrete_type())`.
> CiphertextBase can convert from generic type to explicit type

- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/trigger_aws_tests_on_pr.yml
- Makefile
- ci/slab.toml
This is mostly done to avoid failure on AWS tests (core, boolean, shortint, ...) workflow due to flaky tests in WASM.
> chore(ci): put wasm tests in their own workflow

- tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/shortint/server_key/mod.rs
- skip thread_count on serialization, deserialize using the function to properly populate thread_count
closes https://github.com/zama-ai/tfhe-rs-internal/issues/126
> chore(shortint): proper ThreadCount serialization for bootstrapping key

- tfhe/src/core_crypto/commons/numeric/unsigned.rs
- tfhe/src/high_level_api/integers/server_key.rs
- tfhe/src/integer/block_decomposition.rs
- tfhe/src/integer/server_key/radix/scalar_add.rs
- tfhe/src/integer/server_key/radix/scalar_sub.rs
- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/neg.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
- tfhe/src/integer/u256.rs
- scalar_add now uses the same parallel carry propagation algorithm
as the add function.
- scalar_sub now uses the same parallel carry propagation algorithm
as the sub function.
- the 'default' negation function uses the now improved scalar_add
to be faster
- unchecked_scalar_add, smart_scalar_add, checked_scalar_add, scalar_add
have been updated to work on generic scalar type so it should work
on u32, u64, u128, U256, etc
- unchecked_scalar_sub, smart_scalar_sub, checked_scalar_sub, scalar_sub
have been updated to work on generic scalar type so it should work
on u32, u64, u128.
As U256 does not yet implement the UnsignedInteger trait, its not
usable yet as a scalar type for the sub operation.
- The HLAPI is still locked to u64 scalars, it will be updated
when most / all scalar ops are …
> Scalar add sub neg

- tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
- tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
An alternative way of generating the key bits for the multi-bit bootstrapping, computations are made in the standard domain meaning the resulting ciphertext contains less noise, but is more costly to compute, it is interesting to have that trade-off to better manage noise even if it means using more thread to keep the consumer thread saturated
> feat(core): add std multi-bit bootstrapping

- tfhe/c_api_tests/test_boolean_keygen.c
- tfhe/c_api_tests/test_boolean_server_key.c
- tfhe/c_api_tests/test_micro_bench_and.c
- tfhe/src/c_api/boolean/client_key.rs
- tfhe/src/c_api/boolean/destroy.rs
- tfhe/src/c_api/boolean/mod.rs
- tfhe/src/c_api/boolean/parameters.rs
The same thing was done in 3508019cd2b46dc105d5374988dc337e2ce2ff66 for shortint.
This does it for booleans
#Fixes https://github.com/zama-ai/tfhe-rs-internal/issues/60
> feat(c_api): add #[repr(C)] for boolean parameters

- .github/workflows/wasm_client_benchmark.yml
- tfhe/examples/utilities/boolean_key_sizes.rs
- tfhe/examples/utilities/wasm_benchmarks_parser.rs
Now use the CI version of the make recipe to run WASM client benchmarks. In addition, boolean keys and wasm parsing is fixed so that benchmarks_parameters directory is created and populated under tfhe directory.
> chore(ci): fix wasm benchmarks and boolean keys measurement

- tfhe/c_api_tests/test_boolean_keygen.c
- tfhe/c_api_tests/test_boolean_server_key.c
- tfhe/c_api_tests/test_high_level_custom_integers.c
- tfhe/c_api_tests/test_micro_bench_and.c
- tfhe/c_api_tests/test_shortint_keygen.c
- tfhe/c_api_tests/test_shortint_pbs.c
- tfhe/c_api_tests/test_shortint_server_key.c
- tfhe/src/c_api/boolean/destroy.rs
- tfhe/src/c_api/shortint/destroy.rs
This adds a null check in the different destroy function of the C API. The performance impact of this should be negligible / inexistant but should make usage more ergonomic and safer.
Also this renames the detroy functions from being named `destroy_shortint_*` | `destroy_boolean_*` to
`shortint_destroy_*` | `boolean_destroy_*` as it is more coherent with the rest of the API where functions starts with `shortint` or `boolean`.
Fixes https://github.com/zama-ai/tfhe-rs-internal/issues/76
> feat(c_api): safer destroys

- tfhe/src/high_level_api/integers/client_key.rs
- tfhe/src/high_level_api/integers/keys.rs
- tfhe/src/high_level_api/integers/server_key.rs
- tfhe/src/high_level_api/integers/tests.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/high_level_api/integers/types/compact.rs
- tfhe/src/high_level_api/integers/types/compressed.rs
Since 8b3d31ae8af18d0a513a1769f0b1a4f5e2ac5d7c
integers use the same serve key, so
the `GenericIntegerServerKey<P>` type was removed.
Since `GenericIntegrServerKey<P>` does not exist,
there is much less need for the collection
of server key traits (ServerKeyAdd, SeverKeySub).
This commit removes them, as well as the macro layer that was used to implement it
> refactor(hlpai): remove ServerKeyOp trait and macros

- Makefile
Parsing program is using tfhe/ as working directory. Thus providing a relative path starting with tfhe/ would result to an error while trying to walk the directory.
> chore(ci): use correct relative path to wasm bench directory

- tfhe/benches/integer/bench.rs
- tfhe/src/integer/server_key/comparator.rs
- tfhe/src/integer/server_key/radix_parallel/comparison.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
- tfhe/src/integer/u256.rs
This adds scalar comparisons and min/max
- eq (==) and ne (!=) have similar performances to the non scalar version, only gaining a few milliseconds when the scalar value is smaller than the encrypted value
- orderings (<, >, <= ,>=) have more interesting performances gain the more the scalar value is small than the number of encrypted bits in the integer ciphertext.
e.g: comparing an encrypted U256 to a value <= u128::MAX brings the comparison time from 234 ms to 194 ms
comparing an encrypted U256 to a value <= u64::MAX brings the comparison time from 234 ms to 169 ms
> feat(integer): add scalar comparisons

- tfhe/src/high_level_api/global_state.rs
Tiny change to fix building the docs with `--document-private-items`.
> Fix building docs with `--document-private-items`

- tfhe/src/integer/u256.rs
This implements the following operators for U256
- BitXor
- Mul
- is_power_of_two
- ilog2
- SubAssign
This makes us progress on https://github.com/zama-ai/tfhe-rs-internal/issues/120
> feat(integer): implement more U256 operators

- tfhe/benches/shortint/casting.rs
- tfhe/benches/utilities.rs
This is a simple fix to put the benchmark CI back on tracks.
> chore(ci): write shortint casting benchmarks to json file

- tfhe/examples/utilities/generates_test_keys.rs
- tfhe/src/shortint/parameters/mod.rs
Easier to dump the non deterministic key as a default case and chose deterministic execution when required
> chore(tfhe): dump non deterministic key and use deterministic when required

- ci/benchmark_parser.py
- tfhe/benches/boolean/bench.rs
- tfhe/benches/core_crypto/pbs_bench.rs
- tfhe/benches/integer/bench.rs
- tfhe/benches/shortint/bench.rs
- tfhe/benches/utilities.rs
- tfhe/examples/utilities/boolean_key_sizes.rs
- tfhe/examples/utilities/hlapi_compact_pk_ct_sizes.rs
- tfhe/examples/utilities/shortint_key_sizes.rs
- tfhe/examples/utilities/wasm_benchmarks_parser.rs
- tfhe/src/core_crypto/commons/ciphertext_modulus.rs
closes: zama-ai/tfhe-rs-internal#164
This implies to add a conversion method to CiphertextModulus in order to create the CryptoParametersRecord struct used as utils.
> chore(ci): add pbs throughput benchmarks

- tfhe/benches/core_crypto/pbs_bench.rs
Use up-to-date crypto parameters for PBS benchmarks with multi-bit instead of hardcoded ones.
> chore(ci): use multi-bit params in shortint for pbs benchmarks

- tfhe/src/integer/server_key/radix_parallel/bit_extractor.rs
- tfhe/src/integer/server_key/radix_parallel/div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
- tfhe/src/integer/u256.rs
- tfhe/src/shortint/engine/server_side/scalar_mul.rs
Adds a simple and slow algorithms for division/remainder but at least it enables to use of this operators.
This also adds the same implementation in clear
so we will now be able to have u256 div.
> feat(integer): add division by encrypted value

- tfhe/Cargo.toml
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/178
> chore(tfhe): bump version to 0.3.0

- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests.rs
- tfhe/src/shortint/ciphertext/mod.rs
Ciphertext::copy_from did not copy the degree
resulting in potential bad results for some operations.
This fixes it, and rewrites to use destructuring
in order to prevent such thing from happenning again
(with destructuring, if a member is not destructured,
a compile error is emited)
Also we move the implementation of copy_from into
clone_from.
Fixes https://github.com/zama-ai/tfhe-rs/issues/410
> fix(shortint): Ciphertext::copy_from

- tfhe/src/integer/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix/scalar_mul.rs
- tfhe/src/integer/server_key/radix/scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
The scalar (T) in scalar_sub could be at most a u128
because the bounds were `T: UnsignedInteger` and our
U256 does not implement this trait yet.
To make scalar_sub accept a U256 we create
a smaller trait.
> Scalar sub mul 256

- tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
In 35c6aea84b7ee89e0ded748fe4f822d9e3a10a13 the bounds for the scalar_div family of functions were changed.
However, the a few bounds `u64: From<T>` were
not removed meaning the functions which still
had these were still stuck with u64 as the max scalar value.
> fix(integer): remove incorrect bounds

- tfhe/src/integer/server_key/radix/shift.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_rotate.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_shift.rs
This is mainly for convenience.
Also, rust implements shift by u8, u16..u128 for each types.
(even shift by i8...i128 are implemented).
> feat(integer): allow scalar shift/rotate with more unsigned types

- tfhe/src/integer/server_key/mod.rs
- tfhe/src/shortint/server_key/compressed.rs
closes: https://github.com/zama-ai/tfhe-rs/issues/460
fix(integer): set proper MaxDegree for CompressedServerKey
- add shortint API to generate a CompressedServerKey with MaxDegree
- add non regression test based on the user issue
- factorize MaxDegree computation for integer server keys
> fix(integer): set proper MaxDegree for CompressedServerKey

- tfhe/src/shortint/keycache.rs
- allows to easily create named parameters from non standard shortint parameter structs
- allows to reate such named parameters easily outside of the keycache mod the way the macro was written before expanded to more macro calls that may not have been in scope and rendered the macro virtually useless
> refactor(keycache): refactor the named_params_impl macro

- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/c_api/high_level_api/utils.rs
- tfhe/src/high_level_api/integers/types/base.rs
This enables to use u128 and U256 as operands to
operations in the high level api.
BREAKING CHANGE: a breaking change in the C API for scalar operations
for FheUint128 and FheUint256 as they previously required
a u64 and now a U218 / U256 respectively.
> feat(hlapi): allow scalar ops on values up to U256 

- .github/workflows/integer_full_benchmark.yml
- .github/workflows/shortint_full_benchmark.yml
- ci/parse_integer_benches_to_csv.py
- tfhe/benches/integer/bench.rs
- tfhe/benches/shortint/bench.rs
Scalar operations benchmark is done against scalar bit sizes.
Scalar division and modulo are added to the benchmark set.
> chore(ci): bench multiple scalar bit sizes and add operators

- .github/workflows/integer_full_benchmark.yml
- .github/workflows/start_full_benchmarks.yml
- tfhe/benches/integer/bench.rs
This is done to avoid hitting GitHub's hard limit of 6 hours maximum execution per job.
This PR also enable the cron job for the full benchmarks suite.
> chore(bench): Put integer comparisons ops in different groups

- .github/workflows/start_full_benchmarks.yml
This is done to avoid having the same name than the other full benchmarks workflow.
> chore(ci): change full suite benchmarks worflow description

- ci/lattice_estimator.sage
This third-party parameters set is known to be insecure, so there is no need to make the CI fail because of this set.
> chore(ci): ignore tfhe_lib_parameters check in lattice esitmator

- tfhe/benches/integer/bench.rs
Previously, unchecked_eq benchmark would fail at each run. Since unchecked operations require clean inputs, we change the way we instantiate benchmark functions.
> chore(bench): use clean inputs for unchecked ops benchmarks

- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/neg.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/sub.rs
The parallel carry propagation algorithm is a lot faster than the non parallel one, however to actually be faster it requires the CPU to have enough threads.
This adds checks so that we use the parallel algorithm only if this condition is met.
This should improve performance on smaller CPUs
typically found in standard laptops/desktops.
> feat(integer): be smarter about parallel carry propagation usage

- tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
To work the scalar div requires that the scalar type (u32, u64, etc) has at least as many bits of precision that what the ciphertext encrypts (e.g. if the ciphertext encrypt 32bits, the scalar type must have at least 32 bits)
We were missing the assert which lead to misuse, so we add it.
> fix(integer): add assert on scalar bits in scalar_div

- tfhe/src/c_api/utils.rs
closes: https://github.com/zama-ai/tfhe-rs/issues/526
chore(c_api): mark some functions manipulating pointers as unsafe
- restrict visibility to the c_api
> chore(c_api): mark some functions manipulating pointers as unsafe

- .github/workflows/trigger_aws_tests_on_pr.yml
If two or more reviewers approve a Pull Request successively with no new commits in between, the full test suite would have been run for each approval. With this commit, the full test suite would be run again upon approval only if a push has occurred.
> chore(ci): avoid running full suite several times on approval

- .github/workflows/code_coverage.yml
- .github/workflows/trigger_aws_tests_on_pr.yml
- Makefile
- ci/slab.toml
This PR does the following:
- exclude files from coverage reports
- trigger code coverage only if sources changed
- run coverage on AWS EC2
Resolves: zama-ai/tfhe-rs-internal#234
> chore(ci): improve code coverage execution

- .github/workflows/trigger_aws_tests_on_pr.yml
- codecov.yml
This is done to avoid noisy reports in GitHub since coverage in all the library layers haven't been implemented yet.
> chore(ci): disable codecov patch status

- concrete-csprng/src/generators/implem/aarch64/block_cipher.rs
- concrete-csprng/src/generators/implem/aesni/block_cipher.rs
- concrete-csprng/src/seeders/implem/rdseed.rs
adding `#[target_feature(enable = "...")]` attributes to functions using simd intrinsics can improve performance by allowing the intrinsics to get inlined. if we don't do this, then we pay the overhead of a function call + accessing arguments/return value on the stack for every intrinsic we use, which is a big cost
> fix(csprng): enable target_feature attributes for functions using simd intrinsics

- .github/workflows/parameters_check.yml
- ci/lattice_estimator.sage
The devo profile is used to speed up the compilation phase.
Resolves: zama-ai/tfhe-rs-internal#245
> chore(ci): print security level in parameters check

- tfhe/src/integer/server_key/radix/mod.rs
By unconditionally propagating carries after trimming we would sometimes do work for nothing and as propagating carries not cheap at all it would degrade performances.
So only propagate when necessary
> fix(integer): only propagate if necessary after trimming

- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/mul.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
This changes the algorithm for scalar_mul.
The new algorithm allows to remove a lot of work.
For small precisions (16, 32, 64) the gains are in range 5%-10% for higher precisions the gains are 25%-50%.
This also changes the mul to use the functions that sums many clean ciphertexts in parallel. For mul, there is only a 5%-10% improvements for 128bits and 256bits mul.
> feat(integer): improve scalar_mul

- .github/workflows/code_coverage.yml
- Makefile
- tfhe/examples/utilities/generates_test_keys.rs
- tfhe/src/boolean/key_switching_key/test.rs
- tfhe/src/boolean/public_key/compressed.rs
- tfhe/src/boolean/public_key/standard.rs
- tfhe/src/boolean/server_key/tests.rs
This is done by reducing the number of parameters set run in tests.
> chore(ci): speed-up boolean coverage

- tfhe/docs/fine_grained_api/integer/operations.md
- tfhe/src/integer/server_key/radix/add.rs
- tfhe/src/integer/server_key/radix/neg.rs
- tfhe/src/integer/server_key/radix/sub.rs
The way we did the is_neg/add/sub possible at the integer level was incorrect in two ways.
1) We simply called the is_neg/add/sub_possible from
the shortint impl on each block as if the were independant.
However that is not the case, and to the check did not reflect
actual computation.
2) We checked that we did not go beyond max degree on each block,
However, a more correct approach would be to check that adding
the potential carry from preceding block would not exceeding the
current block max capacity.
Fixes asserts for is_sub_possible being triggered in  https://github.com/zama-ai/tfhe-rs/pull/536
> fix(integer): is_neg/sub/add possible

- tfhe/src/integer/bigint/algorithms.rs
- tfhe/src/integer/bigint/i256.rs
> fix(integer): StaticSignedBigInt right shift

- tfhe/src/core_crypto/algorithms/misc.rs
- tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
- tfhe/src/core_crypto/commons/mod.rs
- tfhe/src/core_crypto/commons/numeric/unsigned.rs
Some utils from a work branch on non native moduli that work well enough that I feel confident bringing them in main, they allow to check the noise distribution for non native power of 2 moduli and are therefore a welcome addition
> chore(core): add utils to test noise distribution for power of 2 q

- tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
> feat(integer): add default signed_scalar div/rem/div_rem

- tfhe/src/high_level_api/integers/types/base.rs
Operations that used a scalar as right operand where generically implemented meaning a user could, for example, add a u32 to a FheUint8.
Rust only allows operations between matching types, so we do the same thing.
BREAKING CHANGE: This is a braking change on the Rust API, but for the better I believe. On the C API it is not a breaking change as we already made that assocation as it was simpler to implement
> feat(hlapi): tie scalar ops with corresponding clear type

- tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
- tfhe/src/core_crypto/fft_impl/fft64/math/fft/mod.rs
- tfhe/src/core_crypto/fft_impl/fft64/math/fft/tests.rs
- add an fft backward primitive that can use the input fourier buffer as output as well
- gains 0.6 ms on 2_2 m6i.metal
> refactor(core): remove a copy in the external product

- tfhe/src/high_level_api/integers/client_key.rs
- tfhe/src/high_level_api/integers/keys.rs
- tfhe/src/high_level_api/integers/parameters.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/high_level_api/integers/types/compressed.rs
- tfhe/src/high_level_api/integers/types/static_.rs
Make the GenericInteger struct have a generic `InnerCiphertext` instead of always RadixCiphertext.
This is to prepare the addition of signed types which will use a SignedRadixCiphertext.
> chore(hlapi): add InnerCiphertext type to integer wrapper

- tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/mod.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
Failure detected in this CI run https://github.com/zama-ai/tfhe-rs/actions/runs/6403238645
> chore(test): fix incorrect memory buffer size in wopbs core_crypto tests

- .github/workflows/aws_tfhe_fast_tests.yml
- Makefile
- tfhe/Cargo.toml
- tfhe/src/conformance.rs
- tfhe/src/core_crypto/algorithms/glwe_sample_extraction.rs
- tfhe/src/core_crypto/algorithms/misc.rs
- tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- tfhe/src/core_crypto/commons/parameters.rs
- tfhe/src/core_crypto/entities/glwe_ciphertext.rs
- tfhe/src/core_crypto/entities/glwe_secret_key.rs
- tfhe/src/core_crypto/entities/lwe_bootstrap_key.rs
- tfhe/src/core_crypto/entities/lwe_ciphertext.rs
- tfhe/src/core_crypto/entities/lwe_compact_ciphertext_list.rs
- tfhe/src/core_crypto/entities/lwe_multi_bit_bootstrap_key.rs
- tfhe/src/core_crypto/entities/seeded_lwe_bootstrap_key.rs
- tfhe/src/core_crypto/entities/seeded_lwe_ciphertext.rs
- tfhe/src/core_crypto/entities/seeded_lwe_multi_bit_bootstrap_key.rs
- tfhe/src/core_crypto/fft_impl/fft128_u128/crypto/tests.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/mod.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
- tfhe/src/high_level_api/integers/types/compact.rs
- tfhe/src/high_level_api/shortints/tests.rs
- tfhe/src/integer/ciphertext/mod.rs
- tfhe/src/lib.rs
- tfhe/src/named.rs
- tfhe/src/safe_deserialization.rs
- tfhe/src/shortint/ciphertext/mod.rs
- tfhe/src/shortint/parameters/mod.rs
Some tests will need to be added
> feat(tfhe): add safe deserialiation

- tfhe/src/integer/server_key/radix_parallel/cmux.rs
unchecked_if_then_else had an assert that required that the condition value looked like it encrypts a boolean usind the degree
However, the only cases where a value looks like it encrypts a boolean value is when they are the result of a comparison (lt, le, eq, etc).
But there are other cases were the value holds a boolean value but due to how degree works, it's not possible to know thus limiting the use of if_then_else.
So we remove that assert, and rely on the developpe knowing its condition is 0 or 1.
Fixes: https://github.com/zama-ai/tfhe-rs/issues/615
Fixes: https://github.com/zama-ai/tfhe-rs-internal/issues/246
> fix(integer): remove remove if_then_else assert

- tfhe/src/integer/server_key/radix_parallel/cmux.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
if_then_else uses two calls to zero_out_if.
In zero_out_if, if the condition block given has a degree of 0
then it would return 0, without calling the predicate function.
This is not correct, as its the predicate function that
gives whether the output should be 0 or the original ciphertext.
Which meant that if if_then_else received a condition with a
degree of 0, it would always return 0.
> fix(integer): handle trivial ct in if_then_else

- tfhe/src/integer/server_key/comparator.rs
- tfhe/src/integer/server_key/radix_parallel/cmux.rs
- tfhe/src/integer/server_key/radix_parallel/div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/sub.rs
using overflowing sub allows to remove the comparison used in the algorithm, giving significant performance boost.
```
before
8        16       32      40       64       128        256
hpc7a:    `981 ms` `2.53 s` `6.41 s` `9.04 s` `16.1 s` `39.3 s` `1.55 min`
m6i:        `1.10 s` `2.97 s` `7.17 s` `10.5 s` `19.7 s` `50.2 s` `2.11 min`
afer:
8        16       32      40       64       128        256
hpc7a:   `604 ms` `1.6 s`  `3.8 s`  `5.14 s` `9.4 s`  `22.4 s`  `54.613 s`
m6i:      `659 ms` `1.77 s` `4.4 s`  `5.9 s`  `11.5 s` `29.8 s`  `79.95 s`
```
> feat(integer): speed-up division by using overflowing_sub

- tfhe/src/integer/server_key/radix/scalar_add.rs
- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
> Full propa test

- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
Use a more precise way to choose between using parallel or non parallel carry propagation.
Fixes an issue where for 256bits scalar div, it would select the non parallel carry propagation slowing things down
> fix(integer): better estimate which algorithm to choose

- tfhe/src/core_crypto/fft_impl/fft128/math/fft/tests.rs
- tfhe/src/core_crypto/fft_impl/fft64/math/fft/tests.rs
- tfhe/src/core_crypto/fft_impl/fft64/math/fft/x86.rs
- observed that the subnormal case is already handled by the shift logic so the special handling was not required
> refactor(core): refactor conversion code from f64 to i64

- tfhe/src/integer/server_key/radix/sub.rs
- tfhe/src/integer/server_key/radix_parallel/sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
unsigned_overflowing_sub does an independant subtraction on each blocks with a correcting term being added to avoid trashing the padding bit (lhs - rhs + correction).
The correction depended on rhs's degree.
e.g. if rhs's degree was in range 1..(msg_mod-1) -> correction =
msg_mod
However if rhs's degree was zero (so rhs is a trivial 0), the correction was also 0, however the borrow propagation rely on that correction to always be added.
Fixes https://github.com/zama-ai/tfhe-rs-internal/issues/296
> fix(integer): fix unsigned_overflowing_sub on trivials

- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
The goal is to avoid holding the key twice in memory when both the executor and the test case needs the key
> chore(integer): use Arc<ServerKey> for executor

- tfhe/src/integer/server_key/radix_parallel/bit_extractor.rs
- tfhe/src/integer/server_key/radix_parallel/shift.rs
In encrypted shifts we pack 3 bits from 3 different blocks into the same blocks by doing `b0 * 4 + 2 * b1 + b2`, and then do a PBS to simulate a hardware mux gate.
If the inputs of shift (ie, in lhs << rhs, lhs != rhs, ie we don't do lhs << lhs) this is fine regarding the norm2 noise.
However if we do things like `a << a` or `a >> a`, which is probably a very rare thing but not impossible, the norm2 noise would go above the limit that guarantees our error probability.
To fix that, we extract the bits that tells shift amount, so that they are already properly aligned to their mux input position. The packing becomes `b0 + 2 * b1 + b2` and so,
the noise growth is ok even in the worst case of doind `a << a`.
> fix(integer): fix worst case noise growth in encrypted shifts

- tfhe/benches/integer/bench.rs
- tfhe/benches/integer/signed_bench.rs
- tfhe/examples/dark_market/improved_parallel_fhe.rs
- tfhe/examples/regex_engine/execution.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/integer/ciphertext/boolean_value.rs
- tfhe/src/integer/ciphertext/mod.rs
- tfhe/src/integer/client_key/mod.rs
- tfhe/src/integer/client_key/radix.rs
- tfhe/src/integer/mod.rs
- tfhe/src/integer/server_key/comparator.rs
- tfhe/src/integer/server_key/mod.rs
- tfhe/src/integer/server_key/radix/comparison.rs
- tfhe/src/integer/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix_parallel/cmux.rs
- tfhe/src/integer/server_key/radix_parallel/comparison.rs
- tfhe/src/integer/server_key/radix_parallel/div_mod.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_comparisons.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
The BooleanValue wrapper type is meant to convey the fact that
the ciphertext encrypts a 0 or 1.
Since its meant to be a simple wrapper, the goal for is to be flexible
and not add more burden than usefulness.
Hopefully this implementation somehow achieves that
Breaking Changes:
- This changes the return type of comparisons from a T to
a BooleanBlock. Requiring existing code to explicitely convert
using `.into_radix`.
- This makes the cmux/if_then_else functions take a BooleanValue
as the input type  Requiring existing code to wrap their condition
ciphertext in a new BooleanValue
> Boolean value wrapper

- apps/trivium/src/trans_ciphering/mod.rs
- tfhe/docs/getting_started/operations.md
- tfhe/docs/tutorials/ascii_fhe_string.md
- tfhe/src/c_api/high_level_api/booleans.rs
- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/c_api/high_level_api/utils.rs
- tfhe/src/high_level_api/booleans/mod.rs
- tfhe/src/high_level_api/integers/mod.rs
- tfhe/src/high_level_api/integers/tests_signed.rs
- tfhe/src/high_level_api/integers/tests_unsigned.rs
- tfhe/src/high_level_api/integers/types/base.rs
- tfhe/src/high_level_api/prelude.rs
- tfhe/src/high_level_api/traits.rs
- tfhe/src/integer/public_key/compressed.rs
- tfhe/src/integer/public_key/standard.rs
- This makes FheBool use integer::BooleanBlock internally.
- It makes comparisons (eq, ne, le, etc) return a FheBool instead of
FheUint/FheInt.
- It also moves the if_then_else and cmux methods to FheBool.
- Adds casting from FheBool to FheUint/FheInt (but not from
FheUint/FheInt to FheBool as we expect users to do `a.ne(0)`
as its matches Rust)
- Comparisons now return FheBool
- if_then_else/cmux are now methods of FheBool.
> Fhebool boolean block

- tfhe/src/integer/server_key/radix_parallel/mul.rs
When the parameters have 1 bit of message (message modulus == 2) then the multiplication of 2 blocks does not create a result that can go into the carry space.
We use that fact to avoid doig un-necessary computations when multiplying integers encrypted under parameters with 1 bit.
> feat(integer): avoid un-necessary computations in mul params 1_X

- ci/ec2_products_cost.json
- ci/slab.toml
This instance type hpc7a.96xlarge yields better performances for nearly the same hourly cost.
> chore(ci): change benchmark aws ec2 machine type

- tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/fft_impl/common.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/330
- the identity function more easily detects errors in the PBS as each mega case contains a different value compared to its neighbours
> chore(core): change the test LUT to apply the identity function

- Makefile
This is the Makefile for semver trick compatibility on 0.4.x something similar had already been commited to main, this is now a preparatory commit for the upcoming feature on 0.4.x
Make pcc passes locally with the semver-trick enabled dependency
> chore(ci): update Makefile for semver trick

- tfhe/src/core_crypto/algorithms/lwe_encryption.rs
- tfhe/src/core_crypto/algorithms/lwe_linear_algebra.rs
- tfhe/src/core_crypto/algorithms/seeded_lwe_ciphertext_decompression.rs
- tfhe/src/core_crypto/algorithms/seeded_lwe_ciphertext_list_decompression.rs
- tfhe/src/core_crypto/algorithms/slice_algorithms.rs
- tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
- tfhe/src/core_crypto/algorithms/test/lwe_linear_algebra.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
- tfhe/src/core_crypto/commons/ciphertext_modulus.rs
- tfhe/src/core_crypto/commons/numeric/unsigned.rs
Add support for non power of 2 q for LWE encryption and linalg, LWE encryption tests and LWE linear algebra tests have been updated to make use of the Solinas set of parameter
> feat(tfhe): add LWE encryption with non power of 2 moduli

- .gitignore
- this was hiding some source files in vscode search and could likely have been very annoying when commiting stuff
> chore(ci): .gitignore was ignoring all files/directories names keys

- ci/slab.toml
This is done to mitigate resource shortages in our base AWS region (eu-west-3) due to the high number of instances that are launched in parallel in our Pull Requests.
> chore(ci): add aws ec2 fallback profile for cpu tests

- tfhe/src/shortint/wopbs/mod.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/5
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/348
The doctests were using parameters with too little precision, update to avoid flaky doctests
> chore(ci): fix doctest by using parameters with enough precision

- tfhe/benches/shortint/bench.rs
- tfhe/src/shortint/wopbs/mod.rs
- tfhe/src/shortint/wopbs/test.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/354
- the alteration is a trick to be able to perform the wopbs in the native crt mode but it modifies the input ciphertext and leaves it modified meaning that the input no longer represents the same data/encryption
- applying the functon several times likely would lead to incorrect results starting from the second call with increasing error/divergence from the original encrypted data
- clone locally instead, should be negligible given wopbs runtime
programmable_bootstrapping_native_crt signature has changed
~* [ ] Tests for the changes have been added (for bug fixes / features)~
~* [ ] Docs have been added / updated (for bug fixes / features)~
[conventional-breaking]: …
> fix(shortint): programmable_bootstrapping_native_crt could alter its input

- tfhe/src/core_crypto/commons/math/decomposition/tests.rs
- the classic native decomposer results are exact and there aren't that many cases to test so tests are changed to be exhaustive
- non native currently still has some work in progress parts so won't be made exhaustive right away, additionally the next PR for the prime Q effort will make some changes to it, so this is why the current code has not been touched for the non native decomposer
This is a preparatory commit to re-organize the native decomposer tests, the non native have not been touched in this PR as the next commit for the prime Q effort will modify them, so no value in updating it for now, plus the prime Q stuff still has some rough edges and so tests are not transposable 1:1
> chore(core): freshen up native decomposition tests

- tfhe/src/integer/ciphertext/boolean_value.rs
- tfhe/src/integer/ciphertext/mod.rs
- tfhe/src/integer/client_key/mod.rs
- tfhe/src/shortint/ciphertext/mod.rs
This adds a decrypt_trivial method to all ciphertext types of shortint and integer.
This functions tries to "decrypt" the ciphertext if it is a trivial one, otherwise it return an error.
This is meant to be a debugging 'tool':
To debug a function / circuit, users can call the function on trivial ciphertexts intead of real ciphertext, that way, computations are faster _and_ they will now be able to see intermediate values via these decrypt_trivial, to do some print-debugging or use a debugger.
> feat(integer): add decrypt_trivial

- tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
- tfhe/src/core_crypto/entities/seeded_ggsw_ciphertext.rs
- tfhe/src/core_crypto/entities/seeded_ggsw_ciphertext_list.rs
- tfhe/src/core_crypto/entities/seeded_glwe_ciphertext.rs
- tfhe/src/core_crypto/entities/seeded_glwe_ciphertext_list.rs
- tfhe/src/core_crypto/entities/seeded_lwe_bootstrap_key.rs
- tfhe/src/core_crypto/entities/seeded_lwe_ciphertext_list.rs
- tfhe/src/core_crypto/entities/seeded_lwe_compact_public_key.rs
- tfhe/src/core_crypto/entities/seeded_lwe_keyswitch_key.rs
- tfhe/src/core_crypto/entities/seeded_lwe_multi_bit_bootstrap_key.rs
- tfhe/src/core_crypto/entities/seeded_lwe_packing_keyswitch_key.rs
- tfhe/src/core_crypto/entities/seeded_lwe_public_key.rs
- as random uniform generation has rejection sampling for non native moduli the seeded decompression currently does not work as it allocates just enough bytes for a native integer and not for the various retries which may be needed
- follow-up issue: https://github.com/zama-ai/tfhe-rs-internal/issues/358
> chore(core_crypto): disable seeded entities for non power of 2 moduli

- tfhe/src/integer/keycache.rs
- tfhe/src/integer/server_key/mod.rs
- the API required passing the client_key to get access to the message and carry modulus, as the shortint ServerKey already has that information drop the requirement to pass the ClientKey
new_radix_server_key_from_shortint, new_crt_server_key_from_shortint APIs have changed and no longer require a ClienKey, the max degree methods now only take a MessageModulus and CarryModulus instead of the full parameter set
~~* [ ] Tests for the changes have been added (for bug fixes / features)~~
~~* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description~~
> chore(integer): simplify an API to create a ServerKey from a shortint one

- README.md
I have seen a few typos in the README while having a look. Sorry, I don't know all your conformance tools, so I might miss a few conventions.
> style(docs): fixing a few typos in the README

- tfhe/src/high_level_api/integers/types/static_.rs
closes: https://github.com/zama-ai/tfhe-rs/issues/761
~~Probably a copy paste mistake, fixed~~
Macro was shared between types and the doc! macro arguments were not managing signed vs. unsigned.
Also fixes a spacing issue
> chore(doc): fix docstring for FheIntX types

- tfhe/src/boolean/client_key/mod.rs
While working on forward compatibility it appears that some struct have no way of being deconstructed and reconstructed for data migration purposes.
This PR is a very small example on the boolean::ClientKey to align on the design of these APIs. Expect a lot of small PRs with a similar goal and once we agree here on the design, a very similar design.
This current patch is aimed at the release/0.4.x branch but will also be added to the main branch as the APIs to reconstruct will be used for data migration from 0.4 to 0.5 and later on deconstruction primitives will be used for migration from 0.5 to 0.6
added:
- into_raw_parts allows to deconstruct a ClientKey
- new_from_raw_parts allows to construct a ClientKey
~~* [ ] Relevant issues are marked as resolved/closed, related issues are linked …
> feat(boolean): add raw parts methods to the ClientKey

- tfhe/src/core_crypto/commons/math/decomposition/mod.rs
- tfhe/src/core_crypto/commons/math/decomposition/term.rs
- those structures are not expected to be serialized by a user
clean up a bit given what was found during the semver trick exploration
> chore(core_crypto): remove Serde on some decomposition structs

- .github/workflows/integer_full_benchmark.yml
- .github/workflows/signed_integer_full_benchmark.yml
- tfhe/benches/integer/bench.rs
- tfhe/benches/integer/signed_bench.rs
Instead of having multiple BENCH_OP_FLAVOR to run for full benchmarks, criterion groups are now gathered by operation kind (default, smart, unchecked).
> chore(ci): gather common benchmarks groups

- tfhe/src/shortint/server_key/comp_op.rs
BREAKING_CHANGE: change mutability of scalar_equal/scalar_not_equal arguement
> refactor(shortint): make scalar_eq/scalar_not_eq take & not &mut

- tfhe/benches/integer/bench.rs
Operation flavors for GPU don't end with "_gpu" anymore. So we can't rely on these string, instead we are using the configuration feature to select which multi-bit parameters set we use. The bit size limitation for CPU in multi-bit is also put back in place.
> chore(bench): fix multi-bit parameters selection for multi-bit

- tfhe/docs/SUMMARY.md
- tfhe/docs/how_to/migrate_data.md
Preliminary documentation for forward compatibility for developers using the rust APIs of TFHE-rs
This targets 0.4.x as it will be part of the 0.4 documentation, a link with a lighter documentation will be added to 0.5
> doc(data_migration): add documentation on how to migrate data for TFHE

- tfhe/docs/SUMMARY.md
- tfhe/docs/how_to/migrate_data.md
Preparing the terrain for redirecting to 0.4 documentation about data migration as 0.5 does not have code to handle that itself
> doc(tfhe): add doc page about data migration which will redirect to 0.4 doc

- tfhe/src/high_level_api/integers/unsigned/tests.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_rotate.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_shift.rs
In scalar_shift/rotate, we get the number of bits to shift/rotate as a generic type, the can be casted to u64.
We compute the total number of bits the ciphertext has, cast that number to the same type as the scalar, and do "shift % num_bits".
However, if the number of bits computed exceeds the max value the scalar type can hold, we could end up doing a remainder with 0.
e.g 256bits ciphertext and scalar type u8, 256u64 casted to u8 results in 0.
Fix that by casting the scalar value to u64.
> fix(integer): fix cast in scalar_shift/rotate

- tfhe/src/core_crypto/algorithms/lwe_encryption.rs
- tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
- update tests to have non zero values in structures to avoid depending on the initialization of the structs
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
~~* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description~~
~~* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]~~
> fix(core): ignore value in the body when doing LWE encryption

- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_comparisons.rs
Fix a bug where in is_scalar_out_of_bounds, if the scalar was negative and the ciphertext a signed one with more blocks than the decomposed scalar, we would do an out of bound access (i.e a panic).
This fixes that, this will fix doing signed_overflowing_mul on 256 bits where the bug first appeared
> fix(integer): is_scalar_out_of_bounds handles bigger ct

- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/core_crypto/gpu/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/algorithms/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_keyswitch.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
- tfhe/src/core_crypto/gpu/entities/lwe_bootstrap_key.rs
- tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
- tfhe/src/core_crypto/gpu/entities/lwe_keyswitch_key.rs
- tfhe/src/core_crypto/gpu/entities/lwe_multi_bit_bootstrap_key.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/integer/gpu/ciphertext/mod.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_rotate.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/433
This PR fixes the `cuda_drop` binding between C++ and Rust.
It also makes all async functions unsafe in the GPU modules, adds some missing synchronize calls and removes two redundant ones.
> Fix cuda_drop binding, mark async functions unsafe

- tfhe/docs/getting_started/benchmarks.md
"forward port to main"
I targeted 0.5 to have the doc up to date faster, picking the commit on main for content consistency
> docs(bench): add scalar benchmarks for integer

- tfhe/src/shortint/parameters/mod.rs
- it stated it represented a number of bits while it represents the actual modulus
> chore(doc): fix modulus struct docstrings in shortint

- backends/tfhe-cuda-backend/cuda/include/integer.h
> Reuse pbs_buffer, tmp_lwe_before/after for single carry propagation

- README.md
- tfhe/docs/getting_started/installation.md
- added more clearly the information for x86 windows machines
as discussed the installation sections should better match
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/443
> chore(doc): update installation to match README

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_fast_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstraping_key.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/276
> chore(gpu): abort when trying to launch 32 bit multi-bit PBS

- tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/shortint/engine/mod.rs
- tfhe/src/shortint/server_key/mod.rs
- tfhe/src/shortint/server_key/tests/shortint.rs
- it does not require any new primitive so was made into a test at the core crypto level
- shortint will have a more user friendly API but it requires some design
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
~~* [ ] Relevant issues are marked as resolved/closed, related issues are linked in the description~~
~~* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]~~
> test(core): add a many LUT test in core crypto

- .github/workflows/core_crypto_benchmark.yml
- .github/workflows/core_crypto_gpu_benchmark.yml
- Makefile
- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/benches/core_crypto/pbs_bench.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/446
> bench(gpu): add a benchmark for keyswitch on GPU

- tfhe/cbindgen.toml
with `documentation=true` cbindgen now properly
generates/copies any rust documentation that
are on `#[no_mangle] pub extern "C" fn` into
their corresponding declaration in the header file.
This will allows to finally start adding some documentation on the CAPI (tfhe.h)
> feat(capi): allow cbindgen to generate docs

- .github/workflows/boolean_benchmark.yml
- .github/workflows/core_crypto_benchmark.yml
- .github/workflows/core_crypto_gpu_benchmark.yml
- .github/workflows/integer_benchmark.yml
- .github/workflows/integer_full_benchmark.yml
- .github/workflows/integer_gpu_benchmark.yml
- .github/workflows/integer_gpu_full_benchmark.yml
- .github/workflows/integer_multi_bit_benchmark.yml
- .github/workflows/integer_multi_bit_gpu_benchmark.yml
- .github/workflows/shortint_benchmark.yml
- .github/workflows/shortint_full_benchmark.yml
- .github/workflows/signed_integer_benchmark.yml
- .github/workflows/signed_integer_full_benchmark.yml
- .github/workflows/signed_integer_multi_bit_benchmark.yml
- Makefile
- tfhe/docs/getting_started/benchmarks.md
- was too error prone when used by other people in the company, no more doubts and we are generally not interested in non avx512 results
> chore(ci): make avx512 enabled by default for benchmarks

- tfhe/src/c_api/high_level_api/booleans.rs
- tfhe/src/c_api/high_level_api/utils.rs
- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/high_level_api/booleans/compressed.rs
- safe ser/de
- classical ser/de
- comparisons
- scalar binary fn/comparisons
- compact & compressed fhe bool encryption
> fix(c-api): add missing function on FheBool

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_gpu_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/csprng_randomness_tests.yml
This is done to handle case where a PR is merged before AWS EC2 instance teardown. If we use profile input in this case, Slab will try to fetch ci/slab.toml on a git reference that doesn't exists anymore thus sending back an error without being able to terminate the instance. By using aws-region Slab won't fetch slab.toml file.
> chore(ci): use aws-region as input to stop ec2 instances

- .github/workflows/integer_gpu_4090_full_benchmark.yml
This missing backslash causes the Python command to fail since some input arguments are missing.
> chore(ci): fix missing backslash in rtx benchmark workflow

- .github/workflows/parameters_check.yml
Latest version of lattice-estimator produce overflow errors. We force the checkout to the last working version to avoid a red CI.
> chore(ci): lock version of lattice-estimator in workflow

- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/benches/core_crypto/pbs_bench.rs
This is done to reflect format used in integer benchmarks and also to ease parsing for our internal data fetching tool.
> chore(bench): format core_crypto benchmark names to ease parsing

- ci/ec2_products_cost.json
RTX4090 we're using here is owned by Zama. So we don't pay an hourly rate to AWS per se. But in ordrer to compute throughput on benchmarks results, the parser needs a numeric value corresponding to the hardware used. Ops-per-dollar metric is not really used today conversely ops-per-seconds is.
> chore(ci): add product cost for rtx4090 to compute throughput

- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix_parallel/ilog2.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
This starts splitting the long test radix tests files into
smaller ones, starting with the add family of function.
---
This adds degrees and noise levels checks as well as comparing
individual decrypted block values with their degrees.
---
smart_add test is not 'hardened' yet, but I want some feedback already
> Start test reorg

- tfhe/src/core_crypto/algorithms/lwe_compact_ciphertext_list_expansion.rs
- tfhe/src/core_crypto/algorithms/lwe_encryption.rs
- this makes sure the product computed for the first ciphertext matches the product computed for a single ciphertext in the non list case
all previous compact public key list encryptions are not compatible with the new layout
> refactor(core): change layout of compact public key encryption for LWE list

- .github/workflows/core_crypto_gpu_benchmark.yml
- .github/workflows/integer_gpu_benchmark.yml
- .github/workflows/integer_gpu_full_benchmark.yml
- .github/workflows/integer_multi_bit_gpu_benchmark.yml
A small mistake was made while fixing lints in the workflows, restore the cuda path bin to be sent to GITHUB_PATH
> chore(ci): fix CUDA_PATH bin not being exported in GITHUB_PATH

- ci/benchmark_parser.py
core_crypto benchmark name format has been changed to reflect what's used in other layers. Benchmark result parser was no longer able to compute the right value for the PBS throughput.
> chore(ci): handle new name format to get pbs throughput values

- tfhe/benches/core_crypto/pbs_bench.rs
This is done to speed-up benchmark duration.
> chore(bench): reduce measurement duration to 60 for pbs benchmarks

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_gpu_4090_tests.yml
- .github/workflows/aws_tfhe_gpu_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/boolean_benchmark.yml
- .github/workflows/cargo_build.yml
- .github/workflows/code_coverage.yml
- .github/workflows/core_crypto_benchmark.yml
- .github/workflows/csprng_randomness_tests.yml
- .github/workflows/gpu_4090_full_benchmark.yml
- .github/workflows/integer_benchmark.yml
- .github/workflows/integer_full_benchmark.yml
- .github/workflows/integer_gpu_benchmark.yml
- .github/workflows/integer_gpu_full_benchmark.yml
- .github/workflows/integer_multi_bit_benchmark.yml
- .github/workflows/integer_multi_bit_gpu_benchmark.yml
- .github/workflows/m1_tests.yml
- .github/workflows/shortint_benchmark.yml
- .github/workflows/shortint_full_benchmark.yml
- .github/workflows/signed_integer_benchmark.yml
- .github/workflows/signed_integer_full_benchmark.yml
- .github/workflows/signed_integer_multi_bit_benchmark.yml
- .github/workflows/wasm_client_benchmark.yml
- Default Linux thread stack size seems to be 8 MB, rust limits it to 2 MB by default, change that to avoid tests failing because of overflowed stacks
> chore(ci): to avoid stack overlow crashes increase thread stack size

- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/neg.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/sub.rs
For the full_propagation, the changes makes it do the best thing depending in the degrees of the input.
First, the sum now uses full_propagate as its last step as opposed to do a custom full propagation. This leads to timing improvements for <= 8 bits, as the full_propagation selects the sequential propagation that is always faster for these precisions.
This will also improve any function that uses a sum with small precision (like ilog2, leading/trailing_zeros/ones)
This will also improve performances for all precisions when computations are done on modest hardware.
Second, the core algorithm of the sum now reasons
in terms of columns not rows which makes the code easier. This makes us do less mistakes when computing the range for which we have to extract messages and carry leading to …
> feat(integer): improve propagation & sum algorithms

- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/455
> feat(gpu): add support to larger polynomials on multi-bit PBS

- .github/workflows/aws_tfhe_wasm_tests.yml
- Makefile
- tfhe/examples/utilities/wasm_benchmarks_parser.rs
- tfhe/src/shortint/engine/server_side.rs
- tfhe/web_wasm_parallel_tests/.prettierignore
- tfhe/web_wasm_parallel_tests/Makefile
- tfhe/web_wasm_parallel_tests/babel.config.js
- tfhe/web_wasm_parallel_tests/index.html
- tfhe/web_wasm_parallel_tests/index.js
- tfhe/web_wasm_parallel_tests/jest.config.js
- tfhe/web_wasm_parallel_tests/package-lock.json
- tfhe/web_wasm_parallel_tests/package.json
- tfhe/web_wasm_parallel_tests/serve.json
- tfhe/web_wasm_parallel_tests/test/common.mjs
- tfhe/web_wasm_parallel_tests/test/compact-public-key.test.js
- tfhe/web_wasm_parallel_tests/test/compressed-publik-key-small.test.js
- tfhe/web_wasm_parallel_tests/test/public-key-ct.test.js
- tfhe/web_wasm_parallel_tests/test/server-key.test.js
- tfhe/web_wasm_parallel_tests/worker.js
This contains several commits to make changes more concise.
> chore(wasm): benchmark server keys and format javascript code

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_gpu_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/boolean_benchmark.yml
- .github/workflows/core_crypto_benchmark.yml
- .github/workflows/core_crypto_gpu_benchmark.yml
- .github/workflows/csprng_randomness_tests.yml
- .github/workflows/gpu_4090_full_benchmark.yml
- .github/workflows/integer_benchmark.yml
- .github/workflows/integer_full_benchmark.yml
- .github/workflows/integer_gpu_benchmark.yml
- .github/workflows/integer_gpu_full_benchmark.yml
- .github/workflows/integer_multi_bit_benchmark.yml
- .github/workflows/integer_multi_bit_gpu_benchmark.yml
- .github/workflows/shortint_benchmark.yml
- .github/workflows/shortint_full_benchmark.yml
- .github/workflows/signed_integer_benchmark.yml
- .github/workflows/signed_integer_full_benchmark.yml
- .github/workflows/signed_integer_multi_bit_benchmark.yml
- .github/workflows/wasm_client_benchmark.yml
- sometimes the notification will say fail while it did not really fail
- use the generic form which can never be wrong
> chore(ci): change slack notifications to be less confusing and more robust

- ci/slab.toml
p4 (A100) and p5 (H100) resources are too scarce on AWS EC2 to use them. A100 for example almost always fails on spawn request.
> chore(ci): run aws gpu benchmark only on p3 instances

- .github/workflows/aws_tfhe_gpu_4090_tests.yml
- .github/workflows/gpu_4090_full_benchmark.yml
- always() forces the evaluation of the PR removal even if there was a failure before, which is irrelevant for removing a label
> chore(ci): force the removal of the 4090 label for PRs even for failures

- .github/workflows/make_release_cuda.yml
- backends/tfhe-cuda-backend/cuda/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/cuda_config.h.in
- backends/tfhe-cuda-backend/cuda/include/device.h
The build currently fails, it will be fixed on cuda backend code side.
> chore(ci): build cuda crates on aws instead on github runner

- tfhe/src/integer/gpu/mod.rs
Fixes a forgotten artifact related to https://github.com/zama-ai/tfhe-rs-internal/issues/482
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/482
> chore(gpu): replaces a mention to the low-latency PBS by just 'classical PBS' and removes a mention to the amortized variant

- tfhe/Cargo.toml
In practice it should already use the 0.4.1 version but this way it will be officially faster
> feat(tfhe): use concrete-fft 0.4.1 for faster pbs 128 by default

- Makefile
- tfhe/src/core_crypto/experimental/algorithms/lwe_shrinking_keyswitch.rs
- tfhe/src/core_crypto/experimental/algorithms/lwe_shrinking_keyswitch_key_generation.rs
- tfhe/src/core_crypto/experimental/algorithms/mod.rs
- tfhe/src/core_crypto/experimental/algorithms/shared_lwe_secret_key_generation.rs
- tfhe/src/core_crypto/experimental/commons/mod.rs
- tfhe/src/core_crypto/experimental/commons/parameters.rs
- tfhe/src/core_crypto/experimental/entities/lwe_shrinking_keyswitch_key.rs
- tfhe/src/core_crypto/experimental/entities/mod.rs
- tfhe/src/core_crypto/experimental/mod.rs
- tfhe/src/core_crypto/experimental/prelude.rs
- tfhe/src/core_crypto/mod.rs
- tfhe/src/keycache/mod.rs
We want to get the core keytricks code in the main branch as an experimental feature so that the code does not rot, this is the first PR to do that.
We do not have very low error prob parameters in general so the recommendation from JB was to have doctests only (or tests with single iterations) for this first integration to still test things but avoid large amount of repetitions which could lead to flaky tests.
The code has to be clean but it's fine if some features are missing, like seeded entities (which would be required to be usable in production).
> feat(core): add experimental lwe shrinking keyswitch from keytricks

- tfhe/docs/guides/run_on_gpu.md
> doc(gpu): add missing benchmark results

- tfhe/src/integer/gpu/server_key/mod.rs
- tfhe/src/safe_deserialization.rs
- tfhe/src/shortint/engine/server_side.rs
- tfhe/src/shortint/server_key/compressed.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/399
Also has the serialization version update, we will need to make a 0.6.1 and yank the 0.6.0 otherwise we have a problem for serialization
This is for main, backport later
> refactor(shortint): add max_noise_level field to CompressedServerKey

- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/utils.h
- tfhe/c_api_tests/test_boolean_keygen.c
- tfhe/c_api_tests/test_boolean_server_key.c
- tfhe/c_api_tests/test_c_doc.c
- tfhe/c_api_tests/test_high_level_128_bits.c
- tfhe/c_api_tests/test_high_level_256_bits.c
- tfhe/c_api_tests/test_high_level_boolean.c
- tfhe/c_api_tests/test_high_level_custom_integers.c
- tfhe/c_api_tests/test_high_level_integers.c
- tfhe/c_api_tests/test_high_level_integers_cuda.c
- tfhe/c_api_tests/test_high_level_threading.c
- tfhe/c_api_tests/test_high_level_zk.c
- tfhe/c_api_tests/test_micro_bench_and.c
- tfhe/c_api_tests/test_shortint_keygen.c
- tfhe/c_api_tests/test_shortint_pbs.c
- tfhe/c_api_tests/test_shortint_server_key.c
- tfhe/docs/guides/c_api.md
- as tfhe is not a system library C/C++ practice is to use the "" style
> chore(c): change include <tfhe.h> to "tfhe.h"

- tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/algorithms/test/mod.rs
- tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
> chore(gpu): add tests for N=8192 multi-bit PBS

- tfhe-zk-pok/src/proofs/pke.rs
- tfhe/src/zk.rs
The motivation of this PR is that sometimes the CRS is generated by a ceremony, instead of centrally.  So it is useful to have some function that computes the CRS witness dimension without generating the CRS centrally.
> feat(zk): open up the API to output the CRS witness dimension

- tfhe-zk-pok/src/curve_446/mod.rs
This fixes (de)serialization of uncompressed BLS12-446 curve points by using the correct byte indices.
> fix(zk): correct byte indices for uncompressed serializtion

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
`host_integer_scalar_mul_radix` relies on `host_integer_sum_ciphertexts_vec_kb`, which initializes `luts_message_carry`, a pair of LUTs initialized to handle `total_count` PBSs in parallel. 
The current implementation assumes the worse case always with `total_count = num_blocks_in_radix * max_num_radix_in_vec`. This may imply in several GBs being allocated only for scalar_mul, which becomes a big problem on more limited GPUs as RTX4090.
This PR moves the allocation of those LUTs to the host function so we only allocate the amount of bits we really need for the given inputs. 
> chore(gpu): reduce memory consumption in host_integer_sum_ciphertexts_vec_kb

- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/560
> chore(gpu): automatically compute the best lwe_chunk_size

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap.h
- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/parameters.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
https://github.com/zama-ai/tfhe-rs-internal/issues/450
https://github.com/zama-ai/concrete-internal/issues/345
> feat(gpu): implement PBSs that use new Hopper's features

- tfhe/src/core_crypto/experimental/algorithms/test/lwe_stair_keyswitch.rs
- the actual large LWE dimension to consider is the partial fill as those are the non zero coefficients on which the shared coefficients are then computed/based on
- the 4 bits parameters don't exhibit the bug as they are not on the GLWE noise plateau
> chore(core): fix the stair KS test for more generic stair KS parameters

- tfhe/benches/integer/signed_bench.rs
closes: zama-ai/tfhe-rs-internal#565
> chore(bench): fix naming format for signed scalar operations

- backends/tfhe-cuda-backend/Cargo.toml
- backends/tfhe-cuda-backend/build.rs
The `build.rs` of the cuda backend uses the default install path from the nvidia runfile to look for libraries. Linux distributions may install the cuda libs in another location. The pkg-config utility should be able to automatically the path of libraries if cuda was installed using a package manager. We can add "best effort" support to other installation methods using this tool.
This has been tested by running the pcc_gpu checks using the cuda provided by the package manager of Archlinux.
> feat(gpu): add compatibility with cuda from package managers

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_gpu_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/csprng_randomness_tests.yml
- .github/workflows/make_release_cuda.yml
- ci/slab.toml
This PR needs to be merged alongside shipping the latest Slab version into production.
> chore(ci): update usage of slab-github-runner to last version

- backends/tfhe-cuda-backend/cuda/src/device.cu
> chore(gpu): add a compilation conditional to assert we won't be checking for cudaDevAttrClusterLaunch on archs < 9.0

- .github/workflows/core_crypto_gpu_benchmark.yml
- .github/workflows/integer_gpu_benchmark.yml
- .github/workflows/integer_gpu_full_benchmark.yml
- .github/workflows/integer_multi_bit_gpu_benchmark.yml
Slack notification GitHub action need Docker to be installed on the system before the action is effectively used.
To mitigate this issue, we set the step it's in own job. The previous job takes care of installing Docker along with other dependencies needed to run the benchmarks.
> chore(ci): fix slack notification in gpu benchmarks

- .github/workflows/aws_tfhe_tests.yml
This is done to imporve iteration time and feedback for devs.
There is no point to run the full test suite each time. A given development could impact only tfhe-zk-pok for example. In this case only tfhe-zk-pok test would run and thus cutting workflow duration from around 3 hours down to a few minutes.
> chore(ci): run workflows based on file changes

- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/integer/ciphertext/boolean_value.rs
cc @titouantanguy 
we will backport that in 0.6 as well
> chore(tfhe): add the ability to get raw parts from an FheBool

- .github/workflows/approve_label.yml
- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_gpu_4090_tests.yml
- .github/workflows/aws_tfhe_gpu_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/csprng_randomness_tests.yml
- .github/workflows/m1_tests.yml
closes zama-ai/tfhe-rs-internal#578
> chore(ci): new workflow target to handle ci execution from forks

- .github/workflows/approve_label.yml
- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_gpu_4090_tests.yml
- .github/workflows/aws_tfhe_gpu_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/csprng_randomness_tests.yml
- .github/workflows/m1_tests.yml
Using pull_request_target event to handle PR from forks was clashing with pull_request event. It would launch double amount of actions and moreover leads to cancellation in jobs due to the concurrency directive.
> chore(ci): use only pull_request event in workflow

- tfhe/Cargo.toml
- it is used as a Random Oracle for the PRF at the shortint level
> chore(tfhe): make sha3 an optional dependency enabled with shortint

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/neg.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
- tfhe/src/integer/gpu/server_key/radix/sub.rs
cuda backend `propagate_single_carry` now returns `carry_out` instead of only processing input carries.
> fix(gpu): ensure `single carry propagation` returns carry

- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
This PR fixes naming in gpu rotations and increases the number of threads in some kernels (to use the maximum possible number of threads always).
> chore(gpu): change the number of threads in smart copy, pack blocks and blocks rotate

- tfhe/src/core_crypto/algorithms/lwe_keyswitch.rs
- tfhe/src/core_crypto/algorithms/test/lwe_keyswitch.rs
refs: https://github.com/zama-ai/tfhe-rs-internal/issues/526
Add a separate function for switching Scalar types between input and ouptut while keyswitching.
I have preferred this approach for now as it was making the bounds and the code way more convoluted in the existing keyswitch.
But if we think it's better to put it in the same function I can.
A follow-up PR will do that for the PBS but should be much easier to write as the two types do not interact at all (as everything happens in the fourier domain), here we need to cast to make computations with both types
> feat(core): add keyswitch that changes the scalar type from input to output

- tfhe/c_api_tests/test_high_level_compact_list.c
- tfhe/c_api_tests/test_high_level_custom_integers.c
- tfhe/docs/fundamentals/compress.md
- tfhe/docs/guides/public_key.md
- tfhe/js_on_wasm_tests/test-hlapi-signed.js
- tfhe/src/c_api/high_level_api/booleans.rs
- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/c_api/high_level_api/utils.rs
- tfhe/src/high_level_api/booleans/encrypt.rs
- tfhe/src/high_level_api/integers/signed/encrypt.rs
- tfhe/src/high_level_api/integers/signed/tests.rs
- tfhe/src/high_level_api/integers/unsigned/encrypt.rs
- tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
- tfhe/src/high_level_api/keys/inner.rs
- tfhe/src/high_level_api/keys/public.rs
- tfhe/src/integer/ciphertext/compact_list.rs
- tfhe/src/integer/encryption.rs
- tfhe/src/integer/public_key/compact.rs
- tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
- tfhe/src/shortint/ciphertext/compact_list.rs
- tfhe/src/shortint/ciphertext/zk.rs
- tfhe/src/shortint/parameters/compact_public_key_only.rs
- tfhe/src/shortint/parameters/mod.rs
- tfhe/src/shortint/public_key/compact.rs
- tfhe/src/shortint/server_key/tests/shortint_compact_pk.rs
- for casting from the CompacthPublicKey parameter we need to add the notion of a kind on the CompactCiphertextList, where one kind will need to be cast thanks to an auxiliary keyswitching key and the other kind can just be expanded as before
- to avoid weird situations/corner cases we remove the ability to encrypt a "normal" ciphertext from a CompactPublicKey (which consisted in expanding right after encryption)
> refactor(tfhe): create associated CompactPrivateKey and prepare casting

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/wasm_client_benchmark.yml
- .gitignore
- Cargo.toml
- Makefile
- scripts/clone_backward_compat_data.sh
- tfhe/Cargo.toml
- tfhe/src/lib.rs
- tfhe/tests/backward_compatibility/mod.rs
- tfhe/tests/backward_compatibility/shortint.rs
- tfhe/tests/backward_compatibility_tests.rs
Add tests for types backward compatibility:
- the repo https://github.com/zama-ai/tfhe-backward-compat-data holds data for historical tfhe-rs versions with associated metadata (eg: for a ciphertext, the metadata is the value of the cleartext)
- for the current version, the test tries to load/deserialize/unversionize the historical data and check their validity using the provided metadata
> test(tfhe): add tests for types backward compatibility

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_bitops.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- ci/ec2_products_cost.json
- tfhe/src/integer/gpu/mod.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/597
> feat(gpu): copy lut and lut indexes to all GPUs

- tfhe-zk-pok/src/curve_api.rs
- tfhe-zk-pok/src/curve_api/bls12_381.rs
- tfhe-zk-pok/src/curve_api/bls12_446.rs
- tfhe-zk-pok/src/lib.rs
- tfhe-zk-pok/src/proofs/mod.rs
- tfhe-zk-pok/src/proofs/pke.rs
- tfhe/js_on_wasm_tests/test-hlapi-signed.js
- tfhe/src/c_api/high_level_api/zk.rs
- tfhe/src/js_on_wasm_api/js_high_level_api/zk.rs
- tfhe/src/zk.rs
This is to allow specifying whether data should be compressed as compression and validation adds a very signigicant overhead especially in wasm where deserialization goes from 6 min to 450ms
> feat(zk): impl CanonicalSerialize/Deserialize

- tfhe/c_api_tests/test_high_level_integers.c
- tfhe/src/c_api/high_level_api/booleans.rs
- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/c_api/high_level_api/utils.rs
- tfhe/src/high_level_api/mod.rs
- tfhe/src/safe_deserialization.rs
Adds a few methods for versioned serializations:
- `safe_serialize_versioned`
- `safe_deserialize_versioned`
- `safe_deserialize_conformant_versioned`
To avoid conflict with the `SERIALIZATION_VERSION`, a different number `VERSIONING_VERSION` is used to record the version of the versioning scheme that has been used. A specific header type has been created that will be embed inside the serialized packet and records if the message is versioned or not. To be compatible with other message serialized with previous 0.6, this header is not used for messages that are not versioned.
However this might be useless in the future since the SERIALIZATION_VERSION should not evolve anymore when versioning will be used by default.
[conventional-breaking]: …
> feat(all): add `safe_serialize_versioned`

- tfhe/tests/backward_compatibility/high_level_api.rs
- tfhe/tests/backward_compatibility/shortint.rs
- tfhe/tests/backward_compatibility_tests.rs
This adds multiple backward compat tests for hl:
- FheInt (normal, compressed, compact)
- FheUint (normal, compressed, compact)
- FheBool (normal, compressed, compact)
- CompactLists (fheint, fheuint, fhebool)
- ClientKey
- PublicKey (normal, compressed, compact, compressedcompact)
- ServerKey (normal, compressed)
The tests for int/uint are done with 8 bits integers, since the IntId is not versioned the structures are identical for every sizes.
> Add backward compatibility tests for hl types

- tfhe/src/shortint/server_key/mod.rs
- tfhe/src/shortint/server_key/tests/parametrized_test.rs
We forgot increase the number of PBSes when doing
a many_lut PBS on a trivial input.
This fixes that, and changes the many_lut test to
test the result on trivial ciphertext and also test that the PBS count is correct.
> fix(shortint): count PBS in trivial_many_lut

- ci/slab.toml
Rustup was installed using snap and could clash in the workflow notably on cargo-clippy calls.
> chore(ci): update gpu ec2 ami with rustup snap package removed

- tfhe/docs/guides/data_versioning.md
`CompactFheIntX`, `CompactFheUintX`, `CompactFheIntXList`, and `CompactFheUintXList` are also data breaking change since they no longer exist on 0.7. This adds a section in the doc to explain how they can be loaded.
> chore(doc): add missing doc for a data breaking change

- .github/workflows/make_release.yml
NPM doesn't accept tags that are similar to a semantic-version compatible string (e.g 0.7.0 or v0.7). We only publish "latest" tag on release manager discretion.
> chore(ci): publish only one tag for npm packages

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
Create API for `propagate_single_carry_get_input_carries` which is the same as `propagate_single_carry`, but we can keep the intermediate state of carries into the `input_carries` parameter. can be used in signed_overflowing_add.
> feat(gpu): Implement propagate_single_carry_get_input_carries

- tfhe-zk-pok/Cargo.toml
Sarah pushed some code improvements for the ZKs for performance, we can release a 0.2.1 to benefit from it in the 0.7.0 release
> chore(zk): bump version to 0.2.1 for perf patch release

- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- scripts/integer-tests.sh
- scripts/test_filtering.py
This only apply for CI triggered in pull-request.
A nightly run is added that run 4bits message/4bits carry parameters set.
> chore(ci): reduce ci duration by not running 4_4 parameters set

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
In this PR I break the pattern to cleanup data in the cleanup function for scalar mul, because this function requires a lot of memory and we end up with out of memory errors in the 4090 benchmarks. I don't see how to reuse memory for sum_ciphertexts_vec in scalar_mul, contrarily to mul, so that's why I chose to release some memory early for this one.
> refactor(gpu): start releasing memory before cleanup in scalar mul

- .github/workflows/aws_tfhe_integer_gpu_tests.yml
- .github/workflows/aws_tfhe_signed_integer_gpu_tests.yml
- .github/workflows/aws_tfhe_tests.yml
Any other label added other than "approved" would trigger these workflow which is not desired.
> chore(ci): check labels to launch only on approval

- backends/tfhe-cuda-backend/cuda/include/integer.h
> fix(gpu): add missing delete

- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap.h
- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstraping_key.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/polynomial_math.cuh
> refactor(gpu): add restrict and const keywords

- tfhe/Cargo.toml
- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/high_level_api/integers/signed/base.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
Makes it possible to grab the number of plaintext bits of a FheUint or FheInt or FheBool.
Useful to know the number of bits of the plaintext whilst using the type aliases.
> feat(hlapi): Make it possible to get num_bits for FheUint type

- tfhe/src/c_api/core_crypto/mod.rs
- tfhe/src/core_crypto/algorithms/ggsw_encryption.rs
- tfhe/src/core_crypto/algorithms/lwe_bootstrap_key_generation.rs
- tfhe/src/core_crypto/algorithms/lwe_multi_bit_bootstrap_key_generation.rs
- tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping/fft64.rs
- tfhe/src/core_crypto/algorithms/test/ggsw_encryption.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
- functions take un-encoded values, reflect that by taking Cleartext instead of Plaintext
> refactor(core): make GGSW encryption consistent

- tfhe/src/integer/server_key/radix/shift.rs
Small copy/paste error in the doc for the integer shl operation
> doc(integer): fix typo in shl doc

- backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
…
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/668
> refactor(gpu): refactor sample extract and modulus switch to match CPU's version

- .github/workflows/data_pr_close.yml
During rebase I used the wrong variable name for merge/close info. This should fix it.
> fix(ci): auto merge job used wrong variable

- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
This PR fixes a memory error observed on the 4090 benchmarks:
https://github.com/zama-ai/tfhe-rs/actions/runs/10014320825/job/27703372553
When reusing an int_radix_lut object it is absolutely necessary to call the int_radix_lut constructor with memory reuse, otherwise it may cause memory errors.
> fix(gpu): fix memory error in mul

- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
add comments inside host_integer_sum_ciphertexts_vec_kb, to describe why smart_copy is used with same pointer as source and destionation
> chore(gpu): add comments inside host_integer_sum_ciphertexts_vec_kb function

- .github/workflows/gpu_4090_benchmark.yml
- Makefile
- tfhe/benches/core_crypto/pbs_bench.rs
I'm keeping only 64-bit benchmarks for multi-bit default operations. 256-bit scalar div gives an out of memory error, and I had to reduce the number of inputs for the multi-bit PBS throughput measurement, otherwise I was also getting an out of memory error.
> chore(gpu): simplify 4090 bench workflow

- tfhe/src/integer/key_switching_key/test.rs
- tfhe/src/shortint/key_switching_key/mod.rs
- tfhe/src/shortint/key_switching_key/test.rs
- tfhe/src/shortint/parameters/key_switching.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/670
- this manages better all the cases we encouter, we force a refresh PBS in all cases for now which is less optimal in certain cases but allows to be safe in cases where keyswitches might be chained
cc @titouantanguy to check the cases which were failing previously
> refactor(shortint): refactor the shortint keyswitching code

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
> fix(gpu): fix scalar shifts

- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/sub.rs
- tfhe/src/integer/server_key/radix/add.rs
- tfhe/src/integer/server_key/radix/scalar_sub.rs
- tfhe/src/integer/server_key/radix/sub.rs
- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/neg.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
> feat(integer): improve carry propagation algorithm

- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/core_crypto/gpu/slice.rs
- tfhe/src/core_crypto/gpu/vec.rs
- tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
Rename some variables to try and make the code clearer
> chore(gpu): remove remaining par_iter over gpu_indexes

- utils/tfhe-versionable/src/lib.rs
It was not possible to use `unversionize(...)?` in an async block.
> chore(versionable): add Send and Sync marker traits to Err type

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap.h
- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/integer/gpu/mod.rs
Always use max shared memory from device 0 to configure the kernels, to avoid bugs with multi-GPU configurations
> refactor(gpu): remove max_shared_memory from pbs arguments

- backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/core_crypto/gpu/mod.rs
> chore(gpu): remove lwe chunk size argument from the multi-bit PBS

- utils/tfhe-versionable/src/lib.rs
The implem converts to `Vec<T::Versioned>` for HashSet and `Vec<(K::Versioned, V::Versioned)>` for HashMap to remove the bound on Eq/Hash for the versioned type. That shouldn't matter since the versioned type is not supposed to be modified before serialization.
This PR also implements Versionize for `Box<[T]>` and `ABox<[T]>` (boxed slices)
> impl Versionize for HashSet/HashMap and Box<[T]>/ABox<[T]>

- backends/tfhe-cuda-backend/cuda/include/ciphertext.h
- backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
- backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/core_crypto/gpu/algorithms/glwe_sample_extraction.rs
- tfhe/src/core_crypto/gpu/algorithms/mod.rs
- tfhe/src/core_crypto/gpu/algorithms/test/glwe_sample_extraction.rs
- tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
- tfhe/src/core_crypto/gpu/mod.rs
This PR:
- introduces a rust test for GPU's sample extraction,
- fixes it when `nth > 0`,
- refactors it so the input (the glwe) is not modified by the method.
We might also observe another performance improvement.
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/671
> refactor(gpu): fix sample extraction when nth > 0 and keep input unchanged

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/675
I don't know how this bug was not detected before, it exists since we merged the dispatch/gather logic.
With small numbers of inputs there were no local cuda streams on some GPUs but we were trying to use them in the scalar shifts, which happen on 2*num_blocks inputs.
> fix(gpu): fix multi-gpu error in division

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
> refactor(gpu): Specify launch bounds on kernels

- utils/tfhe-versionable/src/lib.rs
- utils/tfhe-versionable/tests/types.rs
Add versionize support for statically sized arrays (`[T; N]`) and `std::num::Wrapping<T>`.
Static arrays are converted to slice/vec before versioning since serde does not support const generics in arrays: https://github.com/serde-rs/serde/issues/1937
> Impl versionize for statically sized arrays

- tfhe/src/error.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
- tfhe/src/high_level_api/integers/unsigned/tests/mod.rs
- tfhe/src/high_level_api/prelude.rs
- tfhe/src/high_level_api/traits.rs
- tfhe/src/integer/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix/slice.rs
- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/slice.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_slice.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/640
Adds a bitslice operation to the integer API. This operation extracts a range of bits from an integer. On native rust integers, this is roughly equivalent to the following operation: 
```rust
fn bitslice(val: u64, start_bit: usize, end_bit: usize)  -> u64 {
(val % (1 << end_bit)) >> start_bit
}
```
On FHE radix integers, we have different cases based on the alignment of the slice bounds w.r.t the block size:
- If start_bit is block aligned, we can simply copy full blocks until we are left with fewer bits than the block size
- If start_bit is not aligned, we have to create blocks by "merging" higher bits from a block and lower bits from its successor. This is done using PBS with bivariate LUTs (one per block).
- In both cases, …
> feat(integer): Adds bitslice operation

- tfhe/src/integer/server_key/radix_parallel/sub.rs
The subtraction is done via addition of the negation, the negation is done via unchecked_neg, this will make the first block have a carry.
Then we called add_assign_with_carry_parallelized which did a carry propagation on the rhs which here is the negated value, meaning the subtraction would do 2 carry propagation.
To fix that we directly call the lower function.
> fix(integer): remove double carry prop in sub

- tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
- tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
> feat(integer): improve {overflowing_}scalar_add/sub

- tfhe/Cargo.toml
- tfhe/js_on_wasm_tests/test-hlapi-signed.js
- tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
This adds the missing push functions for some big
uint type that the fhEVM needs
> feat(wasm): add missing push_u{512,1024,2048}

- tfhe/benches/integer/bench.rs
- tfhe/benches/integer/glwe_packing_compression.rs
> fix(gpu): fix compression bench name

- tfhe/src/integer/server_key/radix_parallel/add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
This adds `overflowing_add` and `add` tests that
are on trivial inputs. As these are faster to run they can be more extensive than on true encryptions
This also binds the advanced_add_assign functions tests to include overflow computation
On a standard laptop with 1 test thread it takes ~7 minutes to run these trivial tests
> chore(integer): addition test based on trivial inputs

- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_bitwise_op.rs
This makes the remaining non-parallel ops implementation use the same test cases that are used for parallel implementations.
There are still some test that do not share the test case but its either because they do not have a parallel impl (not interesting to have) or when its tests about encryption/decryption
Closes https://github.com/zama-ai/tfhe-rs-internal/issues/265
> chore(integer): make remaining non-parallel test use defined test cases

- tfhe/src/high_level_api/keys/inner.rs
probably what led to some wasm bench to be slower
cc @nsarlin-zama when you are back
> chore(hl): a bad merge led to two server key generation

- tfhe/src/core_crypto/fft_impl/fft64/math/fft/x86.rs
> feat(tfhe): replace asm with rust intrinsics

- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
The internal benchmark tool got broken for the TBC PBS during some of the updates we had in the last weeks / months. This PR fixes it.
closes: 
> fix(gpu): update the internal benchmark tool for the TBC pbs

- tfhe/src/core_crypto/gpu/algorithms/glwe_sample_extraction.rs
- tfhe/src/core_crypto/gpu/vec.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
> chore(gpu): remove device synchronization in drop for CudaVec

- .github/workflows/benchmark_gpu_integer_multi_gpu_full.yml
Multi-GPU weekly benchmarks will now execute only multi-bit default operations. Single GPU benchmarks will still run everything. 
> chore(gpu): reduce the amount of weekly multi-gpu bench

- backends/tfhe-cuda-backend/cuda/include/device.h
- backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
- backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cu
- backends/tfhe-cuda-backend/src/cuda_bind.rs
closes:
I rewrote all the binding to be sure it's consistent with the c++ headers.
> chore(gpu): pass over all cuda bind

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/polynomial_math.cuh
closes: [#667](https://github.com/orgs/zama-ai/projects/21?pane=issue&itemId=74014357)
> refactor(gpu): avoid synchronizations in the keybundle

- backends/tfhe-cuda-backend/cuda/CMakeLists.txt
Introduces a cmake flag, `CMAKE_BUILD_TYPE`, to compile in Release mode (`-O3`) or not (`-O0 -G -g`).
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/570
> chore(gpu): add debug/release modes

- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_fast_tests.yml
- .github/workflows/gpu_full_multi_gpu_tests.yml
- Makefile
- backends/tfhe-cuda-backend/cuda/include/compression.h
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cu
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
- tfhe/src/integer/gpu/mod.rs
Fixes some edge cases, including booleans and multi-gpu.
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/686
> fix(gpu): fix compression

- tfhe/web_wasm_parallel_tests/package.json
https://github.com/jestjs/jest/issues/10777
the open handle thing is it seems a known issue freezing the test runner, removing it from our tests/benchmarks as it's not helping at the moment
> chore(ci): the detect handles option from jest is freezing the runner

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- tfhe/src/integer/server_key/mod.rs
- tfhe/src/integer/server_key/radix/comparison.rs
- tfhe/src/integer/server_key/radix_parallel/comparison.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
Parameters are made with with assumptions on the number of leveled add/sub/scalar_mul operations are made, so that the noise level before doing a PBS has a correct level and everything is safe, secure and correct.
So the lib implementation has to uphold these assumptions in order to keep the error probability failure correct.
In the comparisons, at some point we had a vector of ciphertexts with a degree == 1, so we greedily summed them (e.g with 2_2 params we summed them by chunks of 15), while it is correct with regards to the carry and message space it is however less correct with regards to the noise level.
Noise wise, doing this huge sum is correct as long as the noise of each ciphertext is independent from the others in the same chunk.
While it may generally be the case we are in, …
> fix(integer): do sum by safe chunk sizes

- .github/workflows/gpu_fast_h100_tests.yml
- scripts/integer-tests.sh
> chore(gpu): use only 1 thread for core crypto tests to better track down bugs

- .github/workflows/ci_lint.yml
Add a check to verify all actions used in CI workflow are pinned by commit hash and not by tag for security reason.
> chore: ensure actions are pinned by commit hash

- Makefile
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- tfhe/src/core_crypto/entities/compressed_modulus_switched_glwe_ciphertext.rs
- tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
- tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/708
> feat(gpu): implement conversion between CudaCompressedCiphertextList and CompressedCiphertextList

- backends/tfhe-cuda-backend/Cargo.toml
- tfhe/Cargo.toml
Update the dependency to cuda backend in the alpha
> chore: update tfhe to 0.8.0-alpha.8 / cuda-backend to 0.4.0-alpha.1

- tfhe/src/high_level_api/compact_list.rs
- tfhe/src/shortint/ciphertext/compact_list.rs
- it meant that lists needing unpacking could crash during expand
added non reg test
> fix: expand_with_key was not providing the safest set of modes

- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/724
> chore(gpu): improve compression tests

- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- tfhe/src/integer/gpu/mod.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/713
> chore(gpu): add checks to ensure limits for compression

- backends/tfhe-cuda-backend/cuda/include/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
> chore(gpu): initialize some arrays to 0

- .github/workflows/gpu_full_h100_tests.yml
This PR adds a workflow file to trigger all GPU tests on H100, from a workflow only (not in PRs), to better monitor the CI.
> chore(gpu): add file to run full tests on H100 from workflow only

- tfhe/benches/integer/bench.rs
- tfhe/benches/integer/signed_bench.rs
- tfhe/src/high_level_api/integers/signed/base.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
- tfhe/src/integer/server_key/mod.rs
- tfhe/src/integer/server_key/radix_parallel/count_zeros_ones.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_count_zeros_ones.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_count_zeros_ones.rs
The non naive version made for 2_2 parameters
only bring slight (10-15%) for some small sizes like (64, 128, 256 bits) but reduces number of PBS. The place where it brings the best improvements it for very large numbers (e.g 6400 blocks 1.8s for naive, 1.1 sec for non-naive)
fixes https://github.com/zama-ai/tfhe-rs-internal/issues/638
> feat(integer): add count_ones/zeros

- tfhe/src/core_crypto/gpu/vec.rs
It was too unsafe to remove device_synchronize. A good move would probably to remove all asynchronous entry points on the Rust side if we want to be safe, otherwise we need to keep this.
> fix(gpu): add back cuda device synchronize in Drop

- Makefile
- scripts/integer-tests.sh
- scripts/shortint-tests.sh
- tfhe/examples/utilities/generates_test_keys.rs
- tfhe/src/integer/keycache.rs
- tfhe/src/integer/mod.rs
- tfhe/src/integer/wopbs/mod.rs
- tfhe/src/shortint/engine/mod.rs
- tfhe/src/shortint/engine/wopbs/mod.rs
- tfhe/src/shortint/keycache.rs
- tfhe/src/shortint/mod.rs
- tfhe/src/shortint/wopbs/mod.rs
This puts the WOPBS features of shortint and integer modules behind the "experimental" feature.
Due to the versioning feature, the structs definitions are not gated behind the "experimental" feature, however they are only pub(crate) in that case.
> refactor!: gate wops behind "experimental" feature

- utils/tfhe-versionable/src/lib.rs
- utils/tfhe-versionable/tests/types.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/749
The versioning of Vec<T> has a shortcut for rust native type (that implement `NotVersioned`). The goal of this shortcut is to avoid to do call "versionize" on each element of an integer vector and clone it.
This is implemented via the `VersionizeVec` trait. `VersionizeVec` has a blanket impl for `T: NotVersioned` but should be manually implemented for other types.
The `#[derive(Versionize)]` proc macro implements it, but it was not implemented for `Vec<T>`. Due to the "conflicting implementation" rule of the rust compiler, this is at the price of the shortcut impl for `Vec<Vec<T: NotVersioned>>`
> feat(versionable): impl Versionize for `Vec<Vec<T>>`

- tfhe/src/high_level_api/mod.rs
Pub re-export the `HlCompressible` and `HlExpandable`
traits, as users may need them to write generic code
that manipulates CompressedCiphertextList/Builder
> fix(hlapi): pub use HlCompressible,HlExpandable

- .github/workflows/gpu_fast_h100_tests.yml
- Makefile
- scripts/integer-tests.sh
> chore(gpu): reset all test thread values

- backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
- backends/tfhe-cuda-backend/cuda/src/types/complex/operations.cuh
Normalization for bsk is changed to divide on 2^bits_in_torus instead of TORUS_MAX. cast from double to torus is modified to avoid casting into in128
> feat(cuda): modify double to torus cast and normalization for bsk

- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/766
I realized we unwrap in `blocks_of` for the Cuda compression, which causes the user doc example for compression to fail on GPU.
> chore(gpu): do not unwrap in blocks_of, to have the same behavior as the CPU

- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
This reverts commit 1c0b6fbbd466b31e5594581218fcfa52355ec1c7.
Maybe this would fix the performance loss observed by Concrete when linking to the tfhe-cuda-backend, but it's unsure.
> chore(gpu): increase max sm size again to gain performance on 3_3 params on H100

- tfhe-zk-pok/src/curve_api/bls12_381.rs
- tfhe-zk-pok/src/curve_api/bls12_446.rs
- utils/tfhe-versionable-derive/src/associated.rs
- utils/tfhe-versionable-derive/src/lib.rs
- utils/tfhe-versionable-derive/src/versionize_attribute.rs
- utils/tfhe-versionable/examples/manual_impl.rs
- utils/tfhe-versionable/examples/recursive.rs
- utils/tfhe-versionable/examples/simple.rs
- utils/tfhe-versionable/examples/upgrades.rs
- utils/tfhe-versionable/tests/convert_with_bounds.rs
- utils/tfhe-versionable/tests/convert_with_generics.rs
- utils/tfhe-versionable/tests/testcases/struct.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/748
The `Versionize` proc macro accepts some arguments that will affect the implementation of the traits. From example, the `#[versionize(SerializableMyTypeVersions, from = SerializableMyType, into = SerializableMyType)]` will apply a conversion method before the versioning, like serde does: https://serde.rs/container-attrs.html#from. However before this PR, this parameter did not work if the conversion type had generics, or if the conversion method needed specific bounds.
On a side note, the syntax was a bit updated. The `from`/`try_from`/`into` keywords were used to mimic serde, for user convenience. However in Versionize we actually don't support having a different value for from and into. This is now checked during the …
> versionize: rework of the from/into/convert feature to allow conversion with generics

- .github/workflows/benchmark_erc20.yml
- Makefile
- tfhe/Cargo.toml
- tfhe/benches/high_level_api/erc20.rs
- tfhe/src/high_level_api/keys/client.rs
This adds benchmarks of both latency and throughput
of 4 variants of the erc20 transfer.
It also prints the PBS count of each versions.
- "whitepaper" is the variant written in the fhevm whitepaper
- "no_cmux" is similar to whitepaper, but uses a "boolean multiplication"
instead of a cmux
- "overflow" uses an overflowing_sub to remove the need for comparison
- "safe" use both overflowing_sub and overflowing_add to make sure both
then sender has enough money and the that the transfer won't overflow
the receiver's money
"overflow" has the lowest latency, and second best throughput
"no_cmux" has the second lowest latenc and the best throughput
> Erc20 bench

- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/740
> chore(gpu): panic in single carry prop if message modulus is 2 (1_1 params)

- ci/webdriver.py
Rust script wasn't able to parse results if the browser name was suffixed after parameters name.
> chore(ci): fix browser identification on wasm benchmarks

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/742
> chore(gpu): limit base log to 32 because of int32 cast in decomposition

- tfhe/src/integer/server_key/radix_parallel/bit_extractor.rs
- tfhe/src/integer/server_key/radix_parallel/block_shift.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/rotate.rs
- tfhe/src/integer/server_key/radix_parallel/shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_rotate.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_rotate.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_shift.rs
This commit does a few things:
* Changes the BitExtractor to use many_lut to reduce number of PBS done
* Add blocks rotation/shift operation
* Implement a new algorithm for bit shift/rotation by encrypted amounts
* Add support bit shift/rotation for 1_1 parameters (as result of adding block shift/rotation)
The gist of the new bit shift/rotation is to use the same idea as the scalar version where we first shift blocks between adjacent blocks, then use a rotation of blocks.
Doing this requires to do a division and modulo operation:
```rust
let (shift_within_blocks, block_rotations) =
(amount / bits_per_block, amount % bits_per_block)
```
When `amount` is clear this operation is simple, when `amount` is encrypted then is harder (`bits_per_block` is always clear). However, when bits_per_block …
> feat(integer): improve shift/rotate by encrypted amount

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/benchmark_wasm_client.yml
- Makefile
- ci/slab.toml
Some libs were missing to be able to run Firefox out of the box. Besides, action runner is now installed as ubuntu user since Firefox is not able to run as root.
> chore(ci): fix firefox wasm benchmarks with new aws ami

- .github/workflows/benchmark_boolean.yml
- .github/workflows/benchmark_erc20.yml
- .github/workflows/benchmark_gpu_erc20.yml
- .github/workflows/benchmark_shortint.yml
- .github/workflows/benchmark_zk_pke.yml
- ci/benchmark_parser.py
Since not only key sizes are measured now, it makes more sense to rename it to --object-sizes.
> chore(ci): rename benchmark parsing option to object-sizes

- tfhe/src/safe_serialization.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/794
The user provided serialized size limit did not include the header during serialization, and an upper bound of the header during de-serialization. The size is now always the complete serialized size, header included.
This PR also includes a fix with unlimited size: we used 0 as an unlimited size value, which did not work with bincode.
> fix(serialization): serialized_size_limit includes the header

- tfhe/web_wasm_parallel_tests/worker.js
fix a broken bench using safe_serialize with a size bound that was too low
> fix(wasm): fix size used for serialization in benches

- tfhe/web_wasm_parallel_tests/worker.js
backport of https://github.com/zama-ai/tfhe-rs/pull/1708
> backport: fix size used for serialization in benches

- tfhe/src/core_crypto/backward_compatibility/entities/seeded_lwe_keyswitch_key.rs
- tfhe/src/core_crypto/backward_compatibility/entities/seeded_lwe_packing_keyswitch_key.rs
- tfhe/src/high_level_api/backward_compatibility/keys.rs
- tfhe/src/integer/backward_compatibility/key_switching_key.rs
- tfhe/src/integer/backward_compatibility/list_compression.rs
- tfhe/src/integer/backward_compatibility/server_key/mod.rs
- tfhe/src/shortint/backward_compatibility/key_switching_key.rs
- tfhe/src/shortint/backward_compatibility/list_compression.rs
- tfhe/src/shortint/backward_compatibility/server_key/mod.rs
Use the `Deprecated` type from `tfhe-versionable` for all the deprecated versions. This removes a bit of code in the backward_compat folders and will improve the error messages because most errors should happen at deserialization, before the call to the "upgrade" method.
Sadly the `Deprecable` trait for the types that have deprecated versions is a bit hard to implement with a declarative macro, because the macro needs to handle types with generics (especially with "nested" generics like `<Scalar: UnsignedInteger, C: Container<Element = Scalar>>`). I think it would require a proc-macro, but I don't know if its worth the price for a few impl (And I think it would be the same thing with impl of `Named`)
> chore(backward): use the Deprecated type from tfhe-versionable

- tfhe/src/core_crypto/commons/math/decomposition/decomposer.rs
- tfhe/src/core_crypto/commons/math/decomposition/iter.rs
- tfhe/src/core_crypto/commons/math/decomposition/tests.rs
- tfhe/src/core_crypto/experimental/algorithms/glwe_fast_keyswitch.rs
- tfhe/src/core_crypto/fft_impl/fft128/crypto/ggsw.rs
- tfhe/src/core_crypto/fft_impl/fft128_u128/crypto/ggsw.rs
- tfhe/src/core_crypto/fft_impl/fft128_u128/crypto/tests.rs
- tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
- tfhe/src/core_crypto/fft_impl/fft64/math/decomposition.rs
It was brought to our attention that a decomposition over 1 level was not properly balanced and could have a mean value of 0.5 which can be an issue when being fed in an FFT (generating harmonics in the process) this fixes that.
A tests has been added to check on a selected 1 level decomposition that the average of the values returning during decomposition is ~0
cc @agnesLeroy and maybe @guillermo-oyarzun so that you can check how to update this on your end, I can explain the formula in more detail, but normally the comment in the code explains how it works
> fix(core): fix decomposition over 1 level to be balanced

- Makefile
Fix benchmarks by updating chrome, feels like something like chrome auto update is fucking up the binary while the benchmark runs resulting in the driver losing connection to it, updating chrome seemingly fixes the issue as can be seen in this run https://github.com/zama-ai/tfhe-rs/actions/runs/11533886276
> chore(ci): update chrome version

- .github/workflows/make_release.yml
- .github/workflows/make_release_concrete_csprng.yml
- .github/workflows/make_release_cuda.yml
- .github/workflows/make_release_tfhe_versionable.yml
- .github/workflows/make_release_zk_pok.yml
- .github/workflows/verify_tagged_commit.yml
Enforce commit being associated to a tag.
The tag must be committed by a member of the release team. In addition, the tag needs to be verified. Finally, triggering actor must also be a member of the release team.
> chore(ci): verify commit on release

- concrete-csprng/src/seeders/implem/apple_secure_enclave_seeder.rs
We checked the macOS version to be sure that the
SecRandomCopyBytes was available.
Since rust 1.74 (which is older than our current msrv)
rust only supports macOS >= 10.12, thus we can expect
SecRandomCopyBytes to always be available and can remove the check
Closes https://github.com/zama-ai/tfhe-rs-internal/issues/806
> chore(scope): no longer check macOS version

- .github/workflows/gpu_signed_integer_classic_tests.yml
- .github/workflows/gpu_unsigned_integer_classic_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
I'm removing classic PBS tests from the H100 workflows and moving them to dedicated workflows on RTX to be sure we test them, since there's currently a shortage of H100's on Hyperstack.
> chore(gpu): rework ci to adapt to the shortage of h100

- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
The results are not expected to match bitwise
> chore(gpu): remove decompressed ct comparison btw cpu and gpu

- backends/tfhe-cuda-backend/cuda/src/device.cu
> chore(gpu): increase sm for rtxa6000

- .github/workflows/aws_tfhe_wasm_tests.yml
- .gitignore
- Makefile
- tfhe/js_on_wasm_tests/package.json
- tfhe/tests/zk_wasm_x86_test.rs
- tfhe/tests/zk_wasm_x86_test/index.js
- tfhe/tests/zk_wasm_x86_test/package.json
- tfhe/web_wasm_parallel_tests/package.json
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/810
This PR adds a test that:
- generates a crs and public key in rust
- load them in js and generate a proven ct list
- verify the proof in rust
This is done to validate proof compatibility between wasm (32b) and x86_64
> chore(zk): add a proof compat test between x86_64 and wasm

- tfhe/src/high_level_api/tests/tags_on_entities.rs
This was a missing sub case for the tag test for the parameter update needs of the BC use case
> test: add tag check for parameter keyswitch in HL API

- .github/workflows/benchmark_boolean.yml
- .github/workflows/benchmark_core_crypto.yml
- .github/workflows/benchmark_erc20.yml
- .github/workflows/benchmark_integer.yml
- .github/workflows/benchmark_shortint.yml
- .github/workflows/benchmark_signed_integer.yml
- .github/workflows/benchmark_zk_pke.yml
- ci/slab.toml
will run benchmarks here to check it works fine
> chore(ci): run bench profile as ubuntu

- ci/slab.toml
I'm changing the target for multi-gpu tests as L40s seem to be still quite available, while rtx a6000 are not anymore...
> chore(gpu): change target for multi-gpu tests

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/abs.cu
- backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/benches/integer/signed_bench.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/abs.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_signed/test_abs.rs
Implements abs operation in GPU backend.
> feat(gpu):  Implement abs operation on gpu backend

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
Now that we don't cast to u32 in the decomposition anymore the assert on base log can be updated.
> chore(gpu): update asserts on base log now that we don't cast to u32 in decomposition

- ci/fft_benchmark_parser.py
Another fix for the bench parser which could not find the data it needed as it was not in the crate root anymore
> chore(ci): fix fft bench parser

- tfhe/src/high_level_api/booleans/inner.rs
- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/ciphertext/mod.rs
The hlapi builder target device was selected depending on features (gpu enabled ? gpu : cpu), but if at `build` time the thread_local key did not match the expected device, an error would be returned.
This is a bit too limiting for users that might want to do some processing on GPU and compression on CPU.
So the Builder is changed to delay, the selection of device used to compress when `build` is called.
This new design is more flexible for end users, at the cost of a bit more memory copies
* There should be no API breaking change
* There is no serialization breaking change as only the builder
(which is not serializable) has been changed
> fix(hlapi): rework CompressedCiphertextListBuilder

- .github/workflows/benchmark_tfhe_zk_pok.yml
Fix failed workflow: https://github.com/zama-ai/tfhe-rs/actions/runs/11983559817/job/33413286395#step:8:42
> fix: zk-pok bench workflow using an invalid argument

- tfhe/src/integer/server_key/comparator.rs
- tfhe/src/integer/server_key/radix/tests.rs
- tfhe/src/shortint/ciphertext/common.rs
Contains a test to recreate an issue we have been having at Belfort. The min - max functions seem to fail at the assertion that [the carries are empty](https://github.com/zama-ai/tfhe-rs/blob/46cf46563770f8e8072ff97692bf18d7d8673158/tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_comparison.rs#L611). IIUC, this is due to the fact that `unchecked_add` will add together the degrees, but we know that either the LHS or the RHS will be set to 0 after performing the LUT [here](https://github.com/zama-ai/tfhe-rs/blob/46cf46563770f8e8072ff97692bf18d7d8673158/tfhe/src/integer/server_key/comparator.rs#L405-L406).
It can be solved in the following ways:
1. Set the degree to `Degree::new(msg_modulus - 1)`.
2. Add a remainder operation in the LUTs (`% message_modulus`).
3. Calculate the …
> Fix: degree for min max

- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_comparison.rs
Fixes the equality in cases of empty blocks.
> Fix: Comparison for less/equal than

- scripts/shortint-tests.sh
- only warn if no tests are run with the big parameters filter
> chore(ci): add debug mode to shortint test script for easier debug later

- tfhe/docs/guides/js_on_wasm_api.md
This adds the steps that might be needed when using the web wasm API with parallel support for rayon.
These are important to document, otherwise the user might not be able to make his project work.
> docs(wasm): add information for web bundlers

- tfhe/src/shortint/key_switching_key/mod.rs
- tfhe/src/shortint/server_key/compressed.rs
- the decompress_into primitives consume the input entity, but we can use a view that won't consume the original owned key
> refactor(shortint): use view -> decompress to simplify key decompression

- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/shortint/server_key/mod.rs
In full_propagate_parallelized we find the first block which has a degree >= msg_mod, meaning it has a carry and start propagating from there.
However, while the preceding blocks may have no carry, their noise level may not be nominal, and so to leave the radix in a consistent state and clean state, full_propagate now also clean the noise for blocks that are not propagated
> fix: clean noise of skipped block in full_propagate_parallelized

- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/shortint/wopbs/mod.rs
- utils/cargo-tfhe-lints-inner/src/main.rs
- utils/cargo-tfhe-lints/src/main.rs
Fix the custom linter that was not running anymore due to an error in the child compiler process that was not propagated. Failure in the child process will now make the ci fail.
This is linked to https://github.com/zama-ai/tfhe-rs/pull/1810 but we also need the PR in rustc-tools to be merged to fix the issue with the toolchain update
> fix(tfhe-lints): linter was not run, missing compile time env var

- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
> fix(gpu): fix scalar ne

- tasks/Cargo.toml
- tasks/src/main.rs
- tfhe/Cargo.toml
- tfhe/examples/regex_engine/engine.rs
- tfhe/src/boolean/keycache.rs
- tfhe/src/core_crypto/keycache.rs
- tfhe/src/integer/keycache.rs
- tfhe/src/shortint/keycache.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/247
Use LazyLock instead of lazy_static. (Or nothing when the value is already const)
> chore(all): remove the dependency to lazy_static

- .github/workflows/benchmark_gpu_erc20.yml
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
> chore(gpu): rework select to avoid using local streams

- tfhe/docs/references/fine-grained-apis/shortint/README.md
Close https://github.com/zama-ai/tfhe-rs-internal/issues/648
> doc(shortint): add some clarification about shortint size

- tfhe/src/core_crypto/gpu/slice.rs
- tfhe/src/core_crypto/gpu/vec.rs
- tfhe/src/integer/gpu/server_key/radix/ilog2.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
> fix(gpu): fix single gpu on device other than 0

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/check_triggering_actor.yml
If a contributor that open a Pull Request from a fork is not part of the repository collaborators, then the workflow using check_triggering_actor subworkflowwill exit with a failure. It could be re-run later by a collaborator who has a write access.
This allows reviewers to read the code proposition before running the CI, ensuring no secrets are leaked outside the repository.
> chore(ci): verify triggering actor on pull request from fork

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
> chore(gpu): rework single carry prop to avoid using local streams

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- tfhe/src/core_crypto/gpu/mod.rs
> chore(gpu): fix inconsistency in the use of AmortizedDegree

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
- tfhe/src/integer/gpu/ciphertext/info.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/mod.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_vector_find.rs
- tfhe/src/integer/gpu/server_key/radix/vector_find.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/vector_find.rs
> feat(gpu): implement subarray search

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
> chore(gpu): add option to pre-release some buffers in scalar mul

- .github/workflows/gpu_integer_long_run_tests.yml
- .github/workflows/integer_long_run_tests.yml
- Makefile
- scripts/integer-tests.sh
- scripts/test_filtering.py
- tfhe/Cargo.toml
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_long_run/mod.rs
- tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_random_op_sequence.rs
- tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_signed_erc20.rs
- tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_signed_random_op_sequence.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_long_run/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_random_op_sequence.rs
- tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_erc20.rs
- tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_random_op_sequence.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
> chore(ci): add randomized long run tests on CPU and GPU

- backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
- backends/tfhe-cuda-backend/cuda/include/keyswitch.h
- backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cu
- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
Optimize packing ks for level count == 1
- Adds an optimized GEMM kernel
- Adds an alternative packing keyswitch implementation using the gemm kernel
- Implements a fast path for packing keyswitch for levels==1 using the gemm kernel
- Adds the fast path to the integer compression GPU code and adds a test with custom parameters that use the fast path
Achieves ~4x speedup for packing keyswitch
> feat(gpu): speed up packing KS for levels==1

- tfhe/Cargo.toml
the new 1.3.0 version changes the way some files are bundled, I don't want to discover during the release that nothing works properly anymore.
> chore: force wasm-bindgen-rayon to 1.2.2

- .github/workflows/aws_tfhe_fast_tests.yml
Since the addition of pull_request_target event, `github.ref` context object return name of the base branch. So when a workflow was triggered on the base branch during an execution in a pull request, the latter would be cancelled.
Using `github.head_ref`, when available, fixes this behavior. On any other event than `pull_request` or `pull_request_target`, `github.ref` will still be used and work as before.
> chore(ci): fix concurrency group format on pull request event

- backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
- ci/slab.toml
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
> chore(ci): switch gpu tests on push to l40

- backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
- Modifies the generation of the LUT used in decompression so that the delta is calculated with a different precision, as in the CPU implementation
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/845
> chore(gpu): port fix to compression encoding

- Makefile
- tfhe/src/js_on_wasm_api/shortint.rs
- tfhe/web_wasm_parallel_tests/worker.js
Fix parsing of wasm bench names, by exporting a method to get the parameter name as a string.
> fix(bench): use correct name for parameters in wasm benches

- tfhe/src/integer/gpu/server_key/mod.rs
- tfhe/src/integer/gpu/server_key/radix/vector_find.rs
> fix(gpu): fix cornercase in match value function

- tfhe/benches/integer/zk_pke.rs
- tfhe/src/js_on_wasm_api/shortint.rs
- tfhe/web_wasm_parallel_tests/worker.js
Adds benchmark of zkv1 vs zkv2 inside the tfhe crate
> chore(zk): add bench zk v1 vs v2

- tfhe/src/core_crypto/algorithms/test/noise_distribution/mod.rs
follow up is here: https://github.com/zama-ai/tfhe-rs-internal/issues/872
It is most likely down to stuff like float precision as we have hand optimized assembly for x86 and not for aarch, meaning some rounding mode might be different (and some fmadd less precise on aarch64)
> chore(ci): temporarily disable the multi bit noise check on Apple M1

- .github/workflows/aws_tfhe_fast_tests.yml
To be able to run CI for external contribution, through forked repository, and be able to test CI modification in a development branch, we need to discriminate pull request events. 
For the former 'pull_request_target' event is needed to have access to GitHub secrets. 'pull_request' event is required for the latter otherwise the workflow would be pulled from the HEAD of the base branch and thus wouldn't contain changes from the developer.
> chore(ci): choose pull request event with path changes

- tfhe-ntt/src/product.rs
- tfhe/src/core_crypto/fft_impl/fft128/math/fft/mod.rs
- tfhe/src/core_crypto/fft_impl/fft128_u128/math/fft/mod.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix/slice.rs
- tfhe/src/integer/server_key/radix_parallel/comparison.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_shift.rs
- tfhe/src/shortint/client_key/mod.rs
- utils/tfhe-versionable-derive/src/lib.rs
Keeping toolchain upgrade for a later PR as CI fails need to be investigated
> chore: fix new lints

- backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
Just adding a reference in the comment of the gemm kernel and removes a variable that's not used.
> chore(gpu): add reference to gemm algorithm

- tfhe/docs/guides/run_on_gpu.md
NVLink is not a constraint anymore to the CUDA backend. Thus, we should update the multi-gpu section to not mention it anymore.
> chore(docs): Remove mention to NVLink

- .github/workflows/aws_tfhe_fast_tests.yml
This would skip 'check-user-permission' job if the event 'pull_request_target' is emitted and CI files have changed. It avoids overlapping of 'pull_request' and 'pull_request_target' events. CI changes would only be tested on 'pull_request' for Zama own pull requests.
> chore(ci): skip aws fast tests if ci files changed

- backends/tfhe-cuda-backend/cuda/include/linear_algebra.h
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cu
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/negation.cu
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/negation.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/benches/integer/bench.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/high_level_api/booleans/oprf.rs
- tfhe/src/high_level_api/integers/oprf.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/oprf.rs
- tfhe/src/integer/gpu/server_key/radix/vector_comparisons.rs
- tfhe/src/integer/gpu/server_key/radix/vector_find.rs
- tfhe/src/shortint/engine/mod.rs
- tfhe/src/shortint/oprf.rs
- tfhe/src/shortint/server_key/mod.rs
> feat(gpu): implement fhe rand on gpu

- tfhe/src/named.rs
- tfhe/src/safe_serialization.rs
- tfhe/src/zk/mod.rs
Adds the possibility to have aliases in the Named trait.
Context:
In previous versions of TFHE-rs only the `CompactPkePublicParams` were serializable. Since 0.11, the `CompactPkeCrs` is the main exposed type and is serializable. For versioning, there is an upgrade path that allows to load and upgrade an old `CompactPkePublicParams` into a new `CompactPkeCrs`. However this could not work in practice for `CompactPkePublicParams` serialized with `safe_serialize` because of the `Named` impl was different and the data was rejected in the header check.
This PR allows to have aliases to a name, that will be accepted when loading this name. This is optional so it does not break previous code. That way, "zk::CompactPkePublicParams" is seen as an alias for …
> fix(safe_ser): aliases in named for renamed types deserialization

- .github/actionlint.yaml
- .github/workflows/parameters_check.yml
Sagemath is not available as a package on Ubuntu 24.04.
> chore(ci): use ubuntu 22.04 to run security checks

- tfhe/src/named.rs
- tfhe/src/safe_serialization.rs
- tfhe/src/zk/mod.rs
backport of https://github.com/zama-ai/tfhe-rs/pull/1982 for 0.11
> backport 0.11: fix(safe_ser): aliases in named for renamed types deserialization

- tfhe/src/js_on_wasm_api/js_high_level_api/mod.rs
- tfhe/src/js_on_wasm_api/mod.rs
- tfhe/src/js_on_wasm_api/shortint.rs
Fixes `cargo clippy --features=shortint_wasm_api`
> chore: feature gating js_high_level_api

- tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
- tfhe/src/shortint/ciphertext/standard.rs
- tfhe/src/shortint/client_key/mod.rs
- tfhe/src/shortint/encoding.rs
- tfhe/src/shortint/engine/client_side.rs
- tfhe/src/shortint/engine/mod.rs
- tfhe/src/shortint/engine/public_side.rs
- tfhe/src/shortint/key_switching_key/mod.rs
- tfhe/src/shortint/mod.rs
- tfhe/src/shortint/parameters/compact_public_key_only/mod.rs
- tfhe/src/shortint/public_key/compact.rs
- tfhe/src/shortint/server_key/mod.rs
- tfhe/src/shortint/server_key/neg.rs
- tfhe/src/shortint/server_key/scalar_add.rs
- tfhe/src/shortint/server_key/scalar_sub.rs
The plaintext encoding in shortint was duplicated all over the code
This commit centralize the encoding used for shortint, so that if an encoding fix is needed there should be one place to do it.
> feat: centralize encoding in shortint

- .github/workflows/check_actor_permissions.yml
White-listed bots have '[bot]' as username suffix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2005)
> chore(ci): use complete bot names on permission checks

- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/abs.rs
- tfhe/src/integer/gpu/server_key/radix/add.rs
- tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
- tfhe/src/integer/gpu/server_key/radix/cmux.rs
- tfhe/src/integer/gpu/server_key/radix/comparison.rs
- tfhe/src/integer/gpu/server_key/radix/div_mod.rs
- tfhe/src/integer/gpu/server_key/radix/ilog2.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/mul.rs
- tfhe/src/integer/gpu/server_key/radix/neg.rs
- tfhe/src/integer/gpu/server_key/radix/rotate.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_rotate.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_shift.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
- tfhe/src/integer/gpu/server_key/radix/shift.rs
- tfhe/src/integer/gpu/server_key/radix/sub.rs
- tfhe/src/integer/gpu/server_key/radix/vector_comparisons.rs
- tfhe/src/integer/gpu/server_key/radix/vector_find.rs
We need to have async entry points for asynchronous execution between the CPU & GPU at the HL API level later. We can't remove it.
> chore(gpu): add back async entry points

- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/high_level_api/array/gpu/booleans.rs
- tfhe/src/high_level_api/array/gpu/integers.rs
- tfhe/src/high_level_api/array/mod.rs
- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/high_level_api/booleans/inner.rs
- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/high_level_api/global_state.rs
- tfhe/src/high_level_api/integers/signed/base.rs
- tfhe/src/high_level_api/integers/signed/inner.rs
- tfhe/src/high_level_api/integers/signed/ops.rs
- tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
- tfhe/src/high_level_api/integers/signed/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
- tfhe/src/high_level_api/integers/unsigned/inner.rs
- tfhe/src/high_level_api/integers/unsigned/ops.rs
- tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/high_level_api/keys/server.rs
- tfhe/src/high_level_api/mod.rs
- tfhe/src/high_level_api/tests/gpu_selection.rs
- tfhe/src/high_level_api/tests/mod.rs
- tfhe/src/integer/gpu/ciphertext/boolean_value.rs
- tfhe/src/integer/gpu/ciphertext/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/1990)
> feat(hlapi): add gpu selection

- tfhe/src/integer/compression_keys.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2015)
> feat(integer): impl Named for compression keys

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cu
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/integer/gpu/ciphertext/info.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/neg.rs
- tfhe/src/integer/server_key/radix/neg.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
> chore(gpu): refactor negate to keep track of degree and noise changes

- tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
After a safe_serialize/safe_deserialize, the CompressedCiphertextList was on Cpu. As the `get` method looked at the device of the data and not the device of the server_key to know where computation needs to happen, it meant that in this case decompressing using Gpu was impossible, only Cpu was usable (as data was always onlu on Cpu)
The fix is twofold:
* First, when deserializing, the data will use the current serverkey (if any) as a hint on where data should be placed
* the `get` method now uses the server_key to know where computations needs to be done, which may incur a temporary copy/transfer on every call to `get` if the device is not correct.
The API to move data has also been added
Note that this was not the case when using regular serialize/deserialize as this would store the …
> fix(hlapi): ciphertext list decompress after safe_deser

- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/benches/core_crypto/pbs_bench.rs
- tfhe/src/core_crypto/gpu/algorithms/glwe_sample_extraction.rs
- tfhe/src/core_crypto/gpu/algorithms/test/glwe_sample_extraction.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_keyswitch.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_packing_keyswitch.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_multi_bit_programmable_bootstrapping_noise.rs
- tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_programmable_bootstrapping_noise.rs
- tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/core_crypto/gpu/slice.rs
- tfhe/src/core_crypto/gpu/vec.rs
- tfhe/src/high_level_api/global_state.rs
- tfhe/src/high_level_api/tests/gpu_selection.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/oprf.rs
- tfhe/src/integer/gpu/server_key/radix/tests_long_run/mod.rs
This commit does 2 things:
* It adds to GpuIndex the invariant that the index corresponds to a valid GPU, to do so, the inner u32 is made private and new/try_new method are now used to construct a GpuIndex these methods checks that the index is valid
* It makes GpuIndex transparent, allowing to safely cast a *const GpuIndex to *const u32, this is to save same copies made to transform Vec<GpuIndex> to Vec<u32> that was used to get a *const u32
BREAKING CHANGES: GpuIndex(some_value) is no longer valid and GpuIndex::new(some_value) / GpuIndex::try_new(some_value) has to be used
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2006)
> refactor!: Add invariant to GpuIndex

- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/benchmark_tfhe_zk_pok.yml
- .github/workflows/benchmark_wasm_client.yml
- .github/workflows/benchmark_zk_pke.yml
- .github/workflows/check_ci_files_change.yml
- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_fast_tests.yml
- .github/workflows/gpu_full_multi_gpu_tests.yml
- .github/workflows/gpu_signed_integer_classic_tests.yml
- .github/workflows/gpu_signed_integer_h100_tests.yml
- .github/workflows/gpu_signed_integer_tests.yml
- .github/workflows/gpu_unsigned_integer_classic_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
- .github/workflows/gpu_unsigned_integer_tests.yml
Running against last remote commit would induce undesired behavior, especially on pull-request approval.
For example a change in integer layer could occur in the pull-request commits list but the changes aren't contained in the last remote commit. Then, on approval, `aws_tfhe_integer_tests.yml` workflow would be skipped although it should run regarding the base commit.
> chore(ci): always run should-run step against base commit

- tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_random_op_sequence.rs
- tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_random_op_sequence.rs
The operations ranges were computed incorrectly in signed & unsigned long run tests which led to only binary/unary ops being triggered.
> chore(gpu): fix long run tests ranges

- tfhe/src/core_crypto/algorithms/test/modulus_switch_noise_reduction.rs
cc @mayeul-zama the check was breaking CI too much, so for now loosened it a bit (we could be facing some rounding problems with f64 given the range of the data, we may want to considering scaling by the modulus and going to torus to use the more precise floats around 0 and 1)
> test(core): make check a little less stringent on improved var for ms

- tfhe/src/core_crypto/entities/glwe_ciphertext.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/core_crypto/gpu/vec.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
- tfhe/src/shortint/ciphertext/compressed_ciphertext_list.rs
This PR fixes two bugs:
One in the metadata after GPU decompression, leading to more carry propagation done
Another in the conversion between Cpu and Gpu CompressedList
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2036)
> CudaCompressedList fixes

- tfhe/src/integer/server_key/radix_parallel/block_shift.rs
- tfhe/src/integer/server_key/radix_parallel/shift.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
This commit fixes a few bugs
* The shift/rotate functions used when blocks encrypt a number of bits that is a power of 2 was causing a panic when working on one block.
- Also, when the number of blocks was low (e.g 2 blocks with 2_2 params) a noise cleaning step was wrongly skipped
* The function used when blocks encrypt non power of 2 number of bits also had a problem
The test have been updated to test with different block sizes and check the noise level
Overall these bugs only affected low block counts (e.g FheUint2, FheUint4) ciphertexts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2041)
> fix(integer): rotations/shifts < 2 blocks

- ci/lattice_estimator.sage
- tfhe/examples/utilities/params_to_file.rs
- tfhe/src/core_crypto/commons/parameters.rs
From SageMath point of view some tfhe-rs parameters set are equivalent. We deduplicate those by storing their name in the tag field. Grouping them that way we decrease analysis time dramatically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2061)
> chore(ci): deduplicate parameters set to send to lattice estimator

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
- tfhe/src/integer/gpu/server_key/radix/ilog2.rs
This PR adds checks on numbers of radix blocks and fixes a bug in shift/rotate.
> chore(gpu): add some checks on radix sizes, fix shift/rotate

- tfhe/src/error.rs
- tfhe/src/high_level_api/compact_list.rs
- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/high_level_api/utils.rs
- tfhe/src/integer/ciphertext/compact_list.rs
- tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/ciphertext/utils.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
- tfhe/src/lib.rs
- tfhe/src/strings/ciphertext.rs
- tfhe/src/strings/test_functions/mod.rs
- tfhe/src/strings/test_functions/test_compact.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2002)
> feat(strings): make strings compatible with compact list

- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
> fix(gpu): enable larger number of samples in the keyswitch

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
> fix(gpu): enable large number of samples in pbs tbc

- .github/workflows/make_release.yml
- re-enabled required permissions, notably write id-token
> chore(ci): fix web packages publish with provenance

- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
Removed unnecessary bounds check for the number of LWEs against polynomial size.
> fix(gpu): Remove unnecessary and incorrect bound check for decompression

- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
> fix(gpu): enable large integers other multi bit pbs

- .github/workflows/make_release_tfhe_versionable.yml
tfhe-versionable crate depends on tfhe-versionable-derive. Workflow, now ensure that derive crate is published before attempting to package tfhe-versionable.
Dry-run option is removed since it cannot be use correctly due the reason aforementioned.
> chore(ci): fix release workflow for tfhe-versionable

- .github/workflows/cargo_test_fft.yml
- .github/workflows/cargo_test_ntt.yml
This is done to avoid testing tfhe-ftt/ntt crates if nothing changes in their source files.
However, these tests would be run unconditionally on each push on main branch.
> chore(ci): add should-run to tfhe-fft and tfhe-ntt tests

- tfhe/src/core_crypto/algorithms/test/modulus_switch_noise_reduction.rs
Temp solution to a check that is too strict (and in that case the obtained value was actually smaller than expected _which is good_)
@mayeul-zama do we have proper intervals for those checks ?
> test: make the bound on the base variance check a bit looser

- .github/workflows/aws_tfhe_backward_compat_tests.yml
- ci/slab.toml
Several network errors occurred while trying to install git-lfs from within backward compatibility tests workflow. Having git-lfs installed directly in the Amazon Machine Image fix this issue.
> chore(ci): update cpu aws ami and install git-lfs

- CONTRIBUTING.md
- tasks/src/check_tfhe_docs_are_tested.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2082)
> chore(ci): add contributing instructions

- backends/tfhe-cuda-backend/cuda/include/ciphertext.h
- backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
- backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/core_crypto/gpu/algorithms/glwe_sample_extraction.rs
- tfhe/src/core_crypto/gpu/algorithms/test/glwe_sample_extraction.rs
- tfhe/src/core_crypto/gpu/mod.rs
feat(gpu): refactor the sample extract entry point so the user can pass how many LWEs should be extracted per GLWE
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/925
> feat(gpu): refactor the sample extract entry point

- tfhe/src/integer/gpu/server_key/mod.rs
- tfhe/src/integer/server_key/mod.rs
- tfhe/src/integer/server_key/radix_parallel/count_zeros_ones.rs
Corner case found when calculating the number of blocks required to store a clear value, when the clear value was 0 it was returning 0. 
> fix(cpu): fix corner case when estimating the num blocks required

- tfhe/src/c_api/high_level_api/integers.rs
- tfhe/src/c_api/high_level_api/utils.rs
cast_into FheUint{12, 512, 1024, 2048} were missing from the C API
> fix(c-api): add missing casts

- ci/slab.toml
Switch n3-H100-SXM5x8 to US-1 as CANADA is out of stock on this instance.
Also L40 instances fallback on n3-RTX-A6000x1 to mitigate resource shortages issues.
> chore(ci): switch environment and add fallback for gpu profiles

- backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
- backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
Compression output size should be `num_glwe * glwe_mask_size + num_lwes`.
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/918
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2075)
> fix(gpu): enforce tighter bounds on compression output

- .github/workflows/benchmark_gpu_core_crypto.yml
- .github/workflows/benchmark_gpu_erc20_common.yml
- .github/workflows/benchmark_gpu_integer_common.yml
- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_full_h100_tests.yml
- .github/workflows/gpu_signed_integer_h100_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
When a shortage occurs on n3-H100x1 instances on Hyperstack, we'll fall back on the permanent one registered on GitHub. This can be done by using 'h100x1' as runner label to run a job on it.
> chore(ci): fallback on permanent h100 instance on shortage

- apps/trivium/src/trans_ciphering/mod.rs
- tfhe/src/shortint/key_switching_key/test.rs
- parameters are optimized for a clean ciphertext, the ciphertext being keyswitched was noisy
Circuit is
```
x = Input
x = bootstrap(x, input_bootstrap_key)
x = keyswitch(x, cast_keyswitch_key)
x = bootstrap(x, output_bootstrap_key)
```
we were doing 
```
x = Input
x = bootstrap(x, input_bootstrap_key)
x = x * 3
x = keyswitch(x, cast_keyswitch_key)
x = bootstrap(x, output_bootstrap_key)
```
for parameters with the drift mitigation this means that the noise after the multiplication by 3 is very large (as it gets mitigated right before the PBS)
> fix: fix the atomic pattern used to cast in trivium and a test in shortint

- Makefile
Because of the rustup upgrade, dylint is currently not working: https://github.com/trailofbits/dylint/pull/1546.
This PR disables temporarily it to unblock the ci
> chore(ci): disable dylint until rustup issue is fixed

- tfhe/src/integer/gpu/ciphertext/boolean_value.rs
- tfhe/src/integer/gpu/ciphertext/mod.rs
- tfhe/src/integer/server_key/crt/scalar_mul_crt.rs
- tfhe/src/integer/server_key/crt_parallel/scalar_mul_crt.rs
- tfhe/src/integer/server_key/radix_parallel/block_shift.rs
- tfhe/src/integer/server_key/radix_parallel/mod.rs
- tfhe/src/integer/server_key/radix_parallel/mul.rs
- tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
- tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_random_op_sequence.rs
- tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_random_op_sequence.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_vector_find.rs
- tfhe/src/shortint/ciphertext/compact_list.rs
- tfhe/src/shortint/ciphertext/compressed.rs
- tfhe/src/shortint/ciphertext/standard.rs
- tfhe/src/shortint/oprf.rs
- tfhe/src/shortint/server_key/tests/modulus_switch_compression.rs
- this is required to make sure we have correctness checks on noise_level updates if we enable them
> fix(shortint): make noise_level field of Ciphertext private again

- tfhe/src/integer/block_decomposition.rs
- tfhe/src/integer/server_key/radix/scalar_sub.rs
The BlockDecomposer gave the possibility when the number of bits per block was not a multiple of the number of bits in the original integer to force the extra bits of the last block to a particular value.
However, the way this was done could only work when setting these bits to 1, when wanting to set them to 0 it would not work.
Good news is that we actually never wanted to set them to 0, but it should still be fixed for completeness, and allow other feature to be added without bugs
> fix: BlockDecomposer

- .github/workflows/benchmark_gpu_core_crypto.yml
- .github/workflows/benchmark_gpu_erc20_common.yml
- .github/workflows/benchmark_gpu_integer_common.yml
- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_full_h100_tests.yml
- .github/workflows/gpu_signed_integer_h100_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
Due to 'continue-on-error' directive 'use-permanent-instance' step could not rely on failure() function.
I've tested the behavior, and now it falls back on the permanent instance.
> chore(ci): fix permanent instance selection condition

- Makefile
- tfhe/benches/integer/bench.rs
- tfhe/benches/integer/glwe_packing_compression.rs
- tfhe/benches/integer/oprf.rs
- tfhe/benches/integer/signed_bench.rs
- tfhe/benches/integer/zk_pke.rs
- tfhe/benches/utilities.rs
- tfhe/src/integer/gpu/ciphertext/boolean_value.rs
This is done to load benchmarks machine in smarter way. This makes sure to saturate compute load of the benchmark machine while keeping execution time reasonable.
iter_batched() criterion method is used instead of iter() so that benchmarks are compatible with other flavors of operations (unchecked_* or smart_*).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2112)
> chore(ci): use new heuristic for throughput benchmarks

- tfhe/docs/_static/cpu_gpu_integer_benchmark_fheuint64_tuniform_2m64_ciphertext.svg
- tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m128_ciphertext.svg
- tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m128_plaintext.svg
- tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m64_ciphertext.svg
- tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m64_plaintext.svg
- tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m64_ciphertext.svg
- tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m64_plaintext.svg
- tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m64_ciphertext.svg
- tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m64_plaintext.svg
- tfhe/docs/getting_started/benchmarks/README.md
- tfhe/docs/getting_started/benchmarks/cpu/cpu_integer_operations.md
- tfhe/docs/getting_started/benchmarks/cpu/cpu_programmable_bootstrapping.md
- tfhe/docs/getting_started/benchmarks/gpu/gpu_integer_operations.md
- tfhe/docs/getting_started/benchmarks/gpu/gpu_programmable_bootstrapping.md
Reduce number of FheUint types displayed in the integer benchmark tables. Increase policy size and better columns fitting. Remove link to enlarge image.
> [backport] docs: change svg benchmark tables appearance

- tfhe/examples/utilities/generates_test_keys.rs
- tfhe/src/keycache/mod.rs
- we run in a cross process race condition which fucks up the key file
- no rust crate seems to help and linux locks are just a fucking mess
- also avoid truncating file when we are going to write to it, get a lock first
Added the key gen for the test as well to avoid issues
> chore: pre-generate keyswitching keys for shortint tests

- tfhe/docs/_static/cpu_pbs_benchmark_tuniform_2m128.svg
- tfhe/docs/_static/cpu_pbs_benchmark_tuniform_2m40.svg
- tfhe/docs/_static/cpu_pbs_benchmark_tuniform_2m64.svg
- tfhe/docs/_static/gpu_pbs_benchmark_tuniform_2m40.svg
- tfhe/docs/_static/gpu_pbs_benchmark_tuniform_2m64.svg
Fresh SVGs for PBS benchmarks results.
I'm wondering if we should keep these new tables with the same overall size in width than integer ones, or if we should make it more fitted ? @yuxizama
> docs: change svg benchmark tables appearance for pbs

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/ilog2.rs
- tfhe/src/integer/gpu/server_key/radix/mod.rs
- tfhe/src/integer/gpu/server_key/radix/vector_find.rs
This PR reverts ilog2 to how it was before the single carry propagation refactor 00037f3b14e5b1dbc363.
Before the refactor, prepare_count_consecutive_bits would return num_blocks * num_blocks ciphertexts in the output vec, which seems to be different from the CPU as far as I can see. When I changed prepare_count_consecutive_bits to return only num_blocks ciphertexts, ilog2(1) started not being equal to 0 anymore.
> fix(gpu): fix ilog2 result when input is 0

- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
This PR fixes a bug in scalar eq, where `is_max_value_lut` is used twice but lut indexes were not reset between the two so we were applying to wrong lut to the first block for the second run of `are_all_comparisons_block_true`.
> fix(gpu): fix scalar eq bug

- .github/workflows/benchmark_gpu_common.yml
Installing dependencies several times, due to matrix strategy, lead to job failure. Now, if the workflow uses the remote instance, the dependencies will be installed only once.
> chore(ci): install dependencies as standalone job

- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cu
- backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
host_compare_with_zero_equality was not following the same logic as the CPU, because it included the call to are_all_comparison_blocks_true. This PR fixes it, and thus avoids doing redundant computation for scalar comparisons (and division).
> fix(gpu): fix logic of host_compare_with_zero_equality

- .github/workflows/aws_tfhe_backward_compat_tests.yml
- ci/slab.toml
Git LFS transfers use a lot of bandwidth. Since data used to test backward compatibility won't change every day, we can leverage GitHub cache action.
> chore(ci): cache backward compatibility data

- tfhe/src/high_level_api/strings/ascii/mod.rs
- tfhe/src/strings/ciphertext.rs
- tfhe/src/strings/client_key.rs
- tfhe/src/strings/server_key/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2146)
> feat: add trivial enc/dec for strings

- backends/tfhe-cuda-backend/cuda/include/pbs/programmable_bootstrap.h
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/benches/core_crypto/pbs128_bench.rs
- tfhe/src/core_crypto/gpu/algorithms/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping_128.rs
- tfhe/src/core_crypto/gpu/mod.rs
Remove lwe_input_indexes, lwe_output_indexes and lut_vector_indexes for pbs128.
> refactor(gpu): remove lwe_input_indexes, lwe_output_indexes and lut_vector_indexes for pbs128

- tfhe-fft/Cargo.toml
- tfhe-ntt/Cargo.toml
- tfhe/Cargo.toml
This is done to get the current version of dependencies defined in workspace, especially pulp.
> chore: update tfhe-fft and tfhe-ntt minor version

- tfhe-ntt/src/prime64.rs
- tfhe-ntt/src/roots.rs
Those root-of-unity enable friendly twiddle generation with low hamming-weigth. And thus, enable to replace some multiplication with simple shift.
> feat(tfhe-ntt): Add custom root-of-unity for Solinas Prime

- backends/tfhe-cuda-backend/cuda/src/device.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
Fix max shared memory bug for CG PBS
> fix(gpu): fix max shared memory bug for CG PBS

- Makefile
- tfhe/src/high_level_api/integers/signed/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/integer/server_key/radix/neg.rs
- tfhe/src/integer/server_key/radix/scalar_add.rs
- tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_sub.rs
- tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_sub.rs
Add integer and hlapi function to perform
`clear - ciphertext`
As subtraction is not commutative having a specialized version is better.
As can be seen from the code, the real benefit is for the default version where the cost of `clear - ciphertext` is the same as `clear + ciphertex` which is better that transforming the clear into a trivial ciphertext to perform the subtract algorithm
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2210)
> feat: add clear - ciphertex

- tfhe/Cargo.toml
- tfhe/src/high_level_api/mod.rs
This PR adds a conversion method from i32 into FheTypes.
This is done using the `strum` crate. It could also be used later to remove some big matches on FheTypes in the C and JS APIs.
> feat(hl): create FheTypes from i32

- .github/workflows/benchmark_gpu_common.yml
- .github/workflows/benchmark_gpu_erc20_common.yml
If an instance, that is not a single-h100, fails to start, the whole setup-instance job have to fail.
Only single-h100 profile can use a permanent remote instance.
> chore(ci): fix handling of instance setup failure

- tfhe/src/core_crypto/algorithms/lwe_bootstrap_key_conversion.rs
- tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping/mod.rs
- tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping/ntt64_bnf_pbs.rs
- tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/commons/math/ntt/ntt64.rs
New Pbs implementation based on NTT.
This implementation work on 2**k modulus and used modswitch before and after every cmux. It mimics the HW implementation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2148)
> feat(ntt-bnf) Add back&Forth ntt implementation

- tfhe-zk-pok/Cargo.toml
- tfhe/Cargo.toml
- utils/tfhe-versionable-derive/Cargo.toml
- utils/tfhe-versionable-derive/src/associated.rs
- utils/tfhe-versionable-derive/src/lib.rs
- utils/tfhe-versionable-derive/src/version_type.rs
- utils/tfhe-versionable-derive/src/versionize_attribute.rs
- utils/tfhe-versionable/Cargo.toml
- utils/tfhe-versionable/examples/skip.rs
- utils/tfhe-versionable/examples/transparent.rs
- utils/tfhe-versionable/src/lib.rs
- utils/tfhe-versionable/tests/skip_enum.rs
Adds the `#[versionize(skip)]` attribute to skip an enum/struct field during the versioning:
```rust
#[derive(Versionize)]
#[versionize(MyStructVersions)]
struct MyStruct {
val: u64,
#[versionize(skip)]
to_skip: NotVersionable,
}
```
This is similar to what serde does: https://serde.rs/field-attrs.html#skip (except that the optional `default = ...` argument is not handled). The `#[serde(skip)]` attribute is also handled the same way if the type derives Serialize.
During unversionizing, the field will be created using `Default::default()`.
This will be needed for the Dynamic AP, because as a trait object it is a bit complex to make it Versionize (same for Serialize). Even if it were possible/easy I don't think it would be a good idea to do it (because it is user defined, we can serialize …
> feat(versionable): add `skip` attribute to skip field versioning

- tfhe/src/shortint/noise_squashing/server_key.rs
Adds `from_raw_parts` / `into_raw_parts` for the shortint NoiseSquashingKey
> feat(shortint): add from_raw_parts for NoiseSquashingKey

- tfhe/src/core_crypto/commons/math/random/uniform_ternary.rs
- corrected from 1.0 to 0.75 given 3/4 of tries will yield a ternary value
- this would have caused a forked generator to fail almost certainly
> fix(core): fix success probability for Ternary Uniform generation

- tfhe/src/high_level_api/keys/server.rs
cc @kc1212 this one is going into main but the same patch will make it to release/1.1.x
to note that you likely will need to call
```rust
let sns_key: Option<&tfhe::integer::NoiseSquashingKey> = sk.as_ref().as_ref();
```
the reason being that we can only return a reference to the internal option from the `AsRef` Implem, and then you call `Option::as_ref` to convert the `&Option<T>` to `Option<&T>`
> feat(hl): add AsRef implementation on ServerKey to access NoiseSquashingKey

- tfhe/src/core_crypto/commons/math/random/mod.rs
- tfhe/src/core_crypto/commons/math/random/t_uniform.rs
- tfhe/src/core_crypto/commons/math/random/tests.rs
Only real tricky part here is making sure that the custom modulus can properly generate the TUniform value and encode that value properly.
Had to put an assert in the generate_one_custom_modulus because the distribution system (which is ancient and was just patched up to work with custom moduli) is not very well suited to the custom modulus stuff to enforce invariants.
Changes in the test file are mainly updating the helper trait for TUniform to make sure that we are able to properly encode/decode the values when the modulus is not native.
One day it might get reworked 😅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2275)
> feat(core): enable custom modulus generation for TUniform

- CODEOWNERS
cc @agnesLeroy 
For now the reviews are not mandatory from code owners to avoid blocking people, but it likely will be enabled with a backup owner to avoid blocking people when both are on leave.
> chore: add CODEOWNERS file to avoid unwanted changes to core_crypto source

- .github/workflows/aws_tfhe_backward_compat_tests.yml
- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/benchmark_boolean.yml
- .github/workflows/benchmark_core_crypto.yml
- .github/workflows/benchmark_erc20.yml
- .github/workflows/benchmark_gpu_4090.yml
- .github/workflows/benchmark_integer.yml
- .github/workflows/benchmark_shortint.yml
- .github/workflows/benchmark_signed_integer.yml
- .github/workflows/benchmark_tfhe_fft.yml
- .github/workflows/benchmark_tfhe_ntt.yml
- .github/workflows/benchmark_tfhe_zk_pok.yml
- .github/workflows/benchmark_wasm_client.yml
- .github/workflows/benchmark_zk_pke.yml
- .github/workflows/code_coverage.yml
- .github/workflows/csprng_randomness_tests.yml
- .github/workflows/gpu_4090_tests.yml
- .github/workflows/integer_long_run_tests.yml
- .github/workflows/make_release.yml
- .github/workflows/make_release_cuda.yml
- .github/workflows/make_release_tfhe_csprng.yml
- .github/workflows/make_release_tfhe_fft.yml
- .github/workflows/make_release_tfhe_ntt.yml
- .github/workflows/make_release_tfhe_versionable.yml
- .github/workflows/make_release_zk_pok.yml
If a step is cancelled, it is not considered as failure by GitHub. 
So if a user cancelled a task or if a job timed out, then no Slack notification was sent and devs weren't able to track down these events.
> chore(ci): fix slack notify in case of cancelled step

- backends/tfhe-cuda-backend/Cargo.toml
- backends/tfhe-cuda-backend/build.rs
- backends/tfhe-cuda-backend/cuda/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cu
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
- backends/tfhe-cuda-backend/cuda/src/utils/helper_profile.cu
- backends/tfhe-cuda-backend/cuda/src/utils/helper_profile.cuh
- tfhe/Cargo.toml
By default nvtx compilation flags will be disable since they might introduce performance degradation. 
To enable the default nvtx labels the wrapper should be compiled with the env variable USE_NVTOOLS=true like this
USE_NVTOOLS=true cargo build --release
To add extra nvtx labels use the PUSH_RANGE and POP_RANGE to delimit the range of the label, and introduce the name of the label in the PUSH_RANGE macro, like this:
PUSH_RANGE("my new label")
POP_RANGE()
> chore(gpu): add nvtx tool for profiling

- .github/workflows/approve_label.yml
~~`FHE_ACTIONS_TOKEN` was needed to display zama-bot as user who add/remove the `approved` label.
This had an inconvenient, PR from external contributor couldn't benefit from this automation, since secrets are not available from users that are not part of the organization.
Moreover, workflow that run on approval wouldn't be executed, unless someone manually add the 'approved' label. By using GitHub token we ensure that these workflows could run on approval.~~
External contributor don't have access to secrets so this workflow would fail when attempting to add/remove 'approved' label on pull-request from forks.
This simple log message is here to remind maintainers to handle 'approved' label manually to trigger the second CI pipeline.
> chore(ci):  log action to perform on approval for external pr

- tfhe/src/core_crypto/backward_compatibility/entities/compressed_modulus_switched_multi_bit_lwe_ciphertext.rs
- tfhe/src/core_crypto/entities/compressed_modulus_switched_multi_bit_lwe_ciphertext.rs
An additional body term was included with the packed mask in the multibit ms compressed ct.
Since this term was simply ignored during extraction I don't think this has any impact on the backward compatibility. From what I understand the Conformance already uses the lwe dimension to check the size of the packed list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2291)
> fix(core): remove additional body coeff in multi bit ms compression

- backends/tfhe-cuda-backend/build.rs
- backends/tfhe-cuda-backend/cuda/include/ciphertext.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/include/keyswitch/keyswitch.h
- backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
- backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cu
- backends/tfhe-cuda-backend/cuda/src/crypto/packing_keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/setup_and_teardown.h
- backends/tfhe-cuda-backend/src/bindings.rs
- backends/tfhe-cuda-backend/wrapper.h
- tfhe/benches/core_crypto/ks_bench.rs
- tfhe/src/core_crypto/gpu/algorithms/lwe_packing_keyswitch.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_packing_keyswitch.rs
- tfhe/src/core_crypto/gpu/mod.rs
> feat(gpu): add necessary entry points for 128 bit compression

- .github/workflows/benchmark_dex.yml
- .github/workflows/benchmark_gpu_dex.yml
- .github/workflows/benchmark_gpu_dex_common.yml
- .github/workflows/benchmark_gpu_dex_weekly.yml
- Makefile
- tfhe/Cargo.toml
- tfhe/benches/high_level_api/dex.rs
- tfhe/benches/high_level_api/erc20.rs
- tfhe/benches/utilities.rs
This PR introduces a new HL API benchmark for the Swap operation, which is executed in the DEX contract. 
There are 2 phases in a confidential swap: the request and the claim. Rand described the flow as:
- user makes swap request by depositing tokens
- the request is added to the current batch of swaps to do
- contract decrypts the batch and updates liquidity in the pool
- each user in the batch can claim their new tokens
We technically only need to run in FHE the deposit and the claim, the rest is not FHE. We also don't care about having more than 1 user in a batch, so we can benchmark with only 1 deposit and 1 claim.
FHEVM implementation:
- for the request swap : https://github.com/jatZama/fhevm-dex/blob/main/contracts/EncryptedDEXPair.sol#L164-L …
> chore(gpu): write swap bench

- backends/tfhe-cuda-backend/cuda/CMakeLists.txt
- backends/tfhe-cuda-backend/cuda/include/linear_algebra.h
- backends/tfhe-cuda-backend/cuda/src/crypto/packing_keyswitch.cuh
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/linearalgebra/multiplication.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/dot_product.cuh
- backends/tfhe-cuda-backend/cuda/src/polynomial/polynomial_math.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/core_crypto/gpu/algorithms/glwe_linear_algebra.rs
- tfhe/src/core_crypto/gpu/algorithms/mod.rs
- tfhe/src/core_crypto/gpu/algorithms/test/glwe_dot_product_with_clear.rs
- tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
To support encrypted GLWE  x clear matrix product, all polys of the GLWE are multiplied with the clear matrix. For each poly of the GLWE, this PR builds a circulant matrix that is multiplied with the clear matrix to obtain the polynomial product. Sample N of this product contains the matrix product of the original clear vector that was encrypted and the clear matrix. 
Now, with `make test_core_crypto_gpu` there are two new tests:
```
test core_crypto::gpu::algorithms::test::glwe_dot_product_with_clear::test_gpu_glwe_dot_product_with_clear_test_params_4_bits_native_u64 ... ok
test core_crypto::gpu::algorithms::test::glwe_dot_product_with_clear::test_gpu_poly_product_with_clear_test_params_4_bits_native_u64 ... ok
```
- Adds a Cargo config to enable GPU multi-architecture builds
> feat(gpu): add circulant matrix for one vs many poly product

- .github/workflows/ci_lint.yml
Usage of bash script to download and extract the final binary has been dropped.
Instead, the tarball is directly fetched according to the ACTIONLINT_VERSION value and the integrity of the tarball is checked with an hardcoded SHA256 sum.
> chore(ci): upgrade actionlint to v1.7.7

- tfhe-zk-pok/src/proofs/mod.rs
- tfhe-zk-pok/src/proofs/pke_v2.rs
Reducing the number of available threads actually improve performance:
Latency is improved by capping the number of threads to 30-50. This is caused by sub-optimal chunk values in arkworks for our hardware: https://github.com/arkworks-rs/algebra/issues/976.
On a 192 threads machines this means that we can actually run ~6 verification in parallel.
For zkv2 verify, compute load verify, 4096bits:
- Latency goes from ~180ms to ~160ms
- If we chunk verification by group of 6, throughput goes from 26/s to 36/s (throughput benches are currently not visible in grafana)
The PR runs the verification in dedicated thread pools. The number of pools is by default based on the number of cores on the machine. Since it uses rayon, it will inherit from the higher level user configuration. The user is still …
> refactor(zk): run pke_v2 verification inside dedicated thread pools

- tfhe/src/core_crypto/commons/parameters.rs
- tfhe/src/shortint/client_key/mod.rs
- tfhe/src/shortint/engine/client_side.rs
- tfhe/src/shortint/parameters/mod.rs
During encryption the AP inside the ciphertext was always hardcoded to standard
> fix(shortint): store correct ap in ciphertext during encryption

- .github/workflows/benchmark_boolean.yml
- .github/workflows/benchmark_dex.yml
- .github/workflows/benchmark_erc20.yml
- .github/workflows/benchmark_gpu_common.yml
- .github/workflows/benchmark_integer.yml
- .github/workflows/benchmark_shortint.yml
- .github/workflows/benchmark_signed_integer.yml
These continue-on-error would lead to misleading report in Action tab since it would display a successful workflow on the global status page while a job may have failed inside.
> chore(ci): remove misleading continue-on-error

- .github/workflows/make_release.yml
- .github/workflows/make_release_cuda.yml
- .github/workflows/make_release_tfhe_csprng.yml
- .github/workflows/make_release_tfhe_fft.yml
- .github/workflows/make_release_tfhe_ntt.yml
- .github/workflows/make_release_zk_pok.yml
If the DRY_RUN variable is empty and double-quoted to perform a safe expansion, then `cargo publish` treat the environment variable as `""` and thus fail by handling an unrecognized argument.
I just got the issue on `hw_regmap` repository which had a similar command.
> chore(ci): avoid double-quote on dry-run variable

- .github/workflows/aws_tfhe_backward_compat_tests.yml
- .github/workflows/aws_tfhe_fast_tests.yml
- .github/workflows/aws_tfhe_integer_tests.yml
- .github/workflows/aws_tfhe_signed_integer_tests.yml
- .github/workflows/aws_tfhe_tests.yml
- .github/workflows/aws_tfhe_wasm_tests.yml
- .github/workflows/benchmark_gpu_4090.yml
- .github/workflows/cargo_build.yml
- .github/workflows/cargo_build_tfhe_fft.yml
- .github/workflows/cargo_build_tfhe_ntt.yml
- .github/workflows/cargo_test_fft.yml
- .github/workflows/cargo_test_ntt.yml
- .github/workflows/check_commit.yml
- .github/workflows/ci_lint.yml
- .github/workflows/code_coverage.yml
- .github/workflows/csprng_randomness_tests.yml
- .github/workflows/gpu_4090_tests.yml
- .github/workflows/gpu_fast_h100_tests.yml
- .github/workflows/gpu_fast_tests.yml
- .github/workflows/gpu_full_multi_gpu_tests.yml
- .github/workflows/gpu_integer_long_run_tests.yml
- .github/workflows/gpu_pcc.yml
- .github/workflows/gpu_signed_integer_classic_tests.yml
- .github/workflows/gpu_signed_integer_h100_tests.yml
- .github/workflows/gpu_signed_integer_tests.yml
- .github/workflows/gpu_unsigned_integer_classic_tests.yml
- .github/workflows/gpu_unsigned_integer_h100_tests.yml
- .github/workflows/gpu_unsigned_integer_tests.yml
- .github/workflows/m1_tests.yml
With recent enforcing of the least permissions for GITHUB_TOKEN, pull-request from external contributors would trigger systematic error (i.e. on repository checkout) in the continuous integration pipeline.
Allowing `contents:read` fixes this behavior.
> chore(ci): ensure minimal permission for github default token

- backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
- backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cu
- backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_keyswitch.cpp
- backends/tfhe-cuda-backend/src/cuda_bind.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/high_level_api/array/gpu/booleans.rs
- tfhe/src/high_level_api/array/gpu/integers.rs
- tfhe/src/high_level_api/booleans/base.rs
- tfhe/src/high_level_api/booleans/encrypt.rs
- tfhe/src/high_level_api/booleans/oprf.rs
- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/high_level_api/global_state.rs
- tfhe/src/high_level_api/integers/oprf.rs
- tfhe/src/high_level_api/integers/signed/base.rs
- tfhe/src/high_level_api/integers/signed/encrypt.rs
- tfhe/src/high_level_api/integers/signed/ops.rs
- tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
- tfhe/src/high_level_api/integers/signed/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
- tfhe/src/high_level_api/integers/unsigned/encrypt.rs
- tfhe/src/high_level_api/integers/unsigned/ops.rs
- tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
- tfhe/src/high_level_api/keys/server.rs
- tfhe/src/high_level_api/tests/gpu_selection.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/960
> feat(gpu): add support for a custom device selection on multi-gpu mode

- tfhe-zk-pok/src/curve_api.rs
- tfhe-zk-pok/src/proofs/mod.rs
- tfhe-zk-pok/src/proofs/pke.rs
- tfhe-zk-pok/src/proofs/pke_v2.rs
- tfhe-zk-pok/src/serialization.rs
Adds a check in the ZK CRS that the group element at index n+1 (one based) is equal to zero.
This is checked during decompression and in `PublicParam::is_usable`, which is used by crs conformance
> chore(zk): check that crs group element at index n is 0

- .github/workflows/gpu_pcc.yml
- Makefile
- tfhe/src/high_level_api/booleans/inner.rs
- tfhe/src/high_level_api/integers/signed/ops.rs
- tfhe/src/high_level_api/integers/signed/scalar_ops.rs
- tfhe/src/high_level_api/integers/unsigned/base.rs
- tfhe/src/high_level_api/integers/unsigned/inner.rs
- tfhe/src/high_level_api/integers/unsigned/ops.rs
- tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
Fix tfhe build with gpu and hpu features enabled. Even if it is not officially supported, it can be useful to enable both at the same times (for example when looking for cross-refs with rust-analyzer).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2358)
> fix(gpu): allow to build with hpu feature enabled

- Makefile
- tfhe-benchmark/benches/integer/zk_pke.rs
- tfhe/docs/configuration/gpu_acceleration/zk-pok.md
- tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
- tfhe/src/core_crypto/gpu/entities/lwe_compact_ciphertext_list.rs
- tfhe/src/core_crypto/gpu/entities/lwe_keyswitch_key.rs
- tfhe/src/core_crypto/gpu/mod.rs
- tfhe/src/high_level_api/backward_compatibility/compact_list.rs
- tfhe/src/high_level_api/compact_list.rs
- tfhe/src/high_level_api/keys/inner.rs
- tfhe/src/high_level_api/keys/server.rs
- tfhe/src/high_level_api/tests/tags_on_entities.rs
- tfhe/src/integer/ciphertext/compact_list.rs
- tfhe/src/integer/gpu/ciphertext/compact_list.rs
- tfhe/src/integer/gpu/key_switching_key/mod.rs
- tfhe/src/integer/gpu/zk/mod.rs
- tfhe/src/test_user_docs.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/986
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2276)
> feat(gpu): add support for GPU-accelerated expand on the HL Api

- tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_random_op_sequence.rs
- tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_signed_random_op_sequence.rs
- tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_random_op_sequence.rs
I was missing the GPU long run tests in the previous commits. Also I think all div/rem should be wrapping, even unsigned, because encrypted division/remainder are wrapping themselves.
> chore(gpu): fix overflow in div in long run tests

- Makefile
- tfhe/Cargo.toml
- tfhe/examples/utilities/params_to_file.rs
- tfhe/src/core_crypto/commons/ciphertext_modulus.rs
- tfhe/src/shortint/keycache.rs
- tfhe/src/shortint/parameters/v1_2/mod.rs
- tfhe/src/shortint/parameters/v1_3/mod.rs
A small refactoring has been done to handle ciphertext modulus in a more convenient way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2380)
> chore(ci): check ks32 parameters with lattice estimator

- .github/workflows/benchmark_gpu_common.yml
- .github/workflows/benchmark_integer.yml
- .github/workflows/benchmark_shortint.yml
- .github/workflows/benchmark_signed_integer.yml
- .github/workflows/benchmark_zk_pke.yml
Previous implementation was done to please Zizmor and avoid template-injection findings during analysis. This had a downside, using `env` directive implies a double-interpolation that messes with `fromJSON()` later and build badly formatted matrix parameters.
> chore(ci): fix benchmark matrix parameters generation

- .github/workflows/benchmark_tfhe_zk_pok.yml
- .github/workflows/benchmark_zk_pke.yml
This is done to avoid name collision when both latency and throughput benchmarks are executed within the same workflow run.
> chore(ci): add bench type to zk benchmarks artifact name

- .github/workflows/aws_tfhe_fast_tests.yml
- tests/backward_compatibility/high_level_api.rs
- tfhe-zk-pok/src/backward_compatibility/mod.rs
- tfhe-zk-pok/src/proofs/binary.rs
- tfhe-zk-pok/src/proofs/mod.rs
- tfhe-zk-pok/src/proofs/pke.rs
- tfhe-zk-pok/src/proofs/pke_v2.rs
- tfhe-zk-pok/src/proofs/range.rs
- tfhe-zk-pok/src/proofs/rlwe.rs
- tfhe-zk-pok/src/serialization.rs
- tfhe/src/shortint/parameters/mod.rs
- tfhe/src/zk/backward_compatibility.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/1004
- Use 8 bytes (instead of 256) for the domain separators used by hash functions
- Adds a random 128bits sid in all the hashes. The SID is defined by the CRS
These changes are made backward compatible, which means:
- the SID is an option, set to None for old CRS
- the 256 bytes domain separators are still supported
This PR also fixes a bug in the `bad_noise` test where the generated noise for the test ended up within the bounds if the tested noise coeff was negative (this is bad because we want to test that proofs are correctly rejected with "out of bound" noise). This was not detected because the test vectors are seeded and the seed always generated a positive coeff.
- - -
This change is [<img …
> chore(zk): use 8 bytes dsep and 128bits SID in hash functions

- tfhe/src/high_level_api/compressed_ciphertext_list.rs
The error in the CI comes from the fact that when executing several tests in parallel we don't have enough memory to run compression. I propose to modify this part of the test with a wait, but we could also reduce test-threads for HL API tests, wdyt?
> chore(gpu): fix ci on H100

- tfhe/src/core_crypto/commons/generators/encryption/mask_random_generator.rs
- tfhe/src/core_crypto/commons/generators/encryption/mod.rs
- tfhe/src/core_crypto/commons/math/random/generator.rs
For tfhe-csprng's new XofSeed (and xof-init) to be useable for
tfhe::core_crypto API, some changes needs to be made
* RandomGenerator acceps T: impl Into<SeedKind>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2426)
> feat(core): plug XofSeed in core's RNG

- .github/workflows/check_commit.yml
This is mandatory according to the action documentation, notably to be able to write issue comment within the pull-request.
> chore(ci): set pull-requests permission to write in commit checks

- tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_signed_random_op_sequence.rs
Random op tests on GPU now include the Abs unary op
> chore(gpu): add abs to random op sequence test on GPU

- Makefile
- backends/tfhe-cuda-backend/Cargo.toml
- backends/tfhe-cuda-backend/build.rs
- backends/tfhe-cuda-backend/cuda/CMakeLists.txt
- tfhe/Cargo.toml
Adds a makefile target `test_integer_gpu_debug` that enables Debug compilation of the CUDA backend
> chore(gpu): add cuda debug target for integer tests

- tfhe-benchmark/benches/high_level_api/erc20.rs
would not be caught by clippy enabling all required features
benchmark could be changed to force to always have pbs-stats enabled for info @soonum
> chore: move gated import to section with feature gate in HL erc20 bench

- tfhe-benchmark/benches/core_crypto/ks_pbs_bench.rs
- tfhe-benchmark/benches/core_crypto/pbs128_bench.rs
- tfhe-benchmark/benches/core_crypto/pbs_bench.rs
- tfhe-benchmark/src/utilities.rs
- tfhe/src/core_crypto/gpu/algorithms/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
- tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping_128.rs
- tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_programmable_bootstrapping_noise.rs
- tfhe/src/integer/gpu/server_key/radix/oprf.rs
- This also fixes the throughput for those PBSs.
> fix(gpu): refactor the (128-bit and regular) classical PBS entry point to remove the num_samples parameter

- tfhe/docs/README.md
> chore: remove dead link from docs

- tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
- tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_hpu_noise.rs
- tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_keyswitch_noise.rs
- tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_multi_bit_programmable_bootstrapping_noise.rs
- tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_programmable_bootstrapping_noise.rs
- tfhe/src/core_crypto/algorithms/test/noise_distribution/mod.rs
- tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_multi_bit_programmable_bootstrapping_noise.rs
- tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_programmable_bootstrapping_noise.rs
- tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/mod.rs
- allows to have less variability and matches exactly what the noise formulas expect for uniform binary secret keys
> test: use hamming weight = 1/2 for core noise tests

- backends/tfhe-cuda-backend/cuda/include/integer/integer.h
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cuh
- backends/tfhe-cuda-backend/src/bindings.rs
- tfhe/src/integer/gpu/mod.rs
- tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
> refactor(gpu): moving unsigned_scalar_div_rem and signed_scalar_div_rem to the backend

- tfhe/src/core_crypto/commons/utils.rs
Fixed a bug in the izip! macro where the 7-parameter version incorrectly returned the 5th element (e) instead of the 7th element (g) in the result tuple. This could cause silent data corruption when using the macro with exactly 7 iterators
> fix: correct tuple element in izip! macro for 7 parameters

- tfhe/src/error.rs
Fixed a typo in the error message for InvalidRangeError::WrongOrder where "gound" was incorrectly used instead of "bound". This makes the error message consistent with the documentation and other error messages in the codebase, improving the overall user experience
> fix: correct typo in InvalidRangeError message

- backends/tfhe-cuda-backend/cuda/include/zk/zk_utilities.h
- backends/tfhe-cuda-backend/cuda/src/crypto/packing_keyswitch.cuh
- `backends/tfhe-cuda-backend/cuda/include/zk/zk_utilities.h` - flatenning to [flattening](https://en.wikipedia.org/wiki/Flattening)
-  `backends/tfhe-cuda-backend/cuda/src/crypto/packing_keyswitch.cuh` - decomposiion to decomposition 
> fix: couple of typos in comment 

- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
Taking a look at scatter, it can't be a function of int_radix_lut as it is also used for the noise squashing lut (which is a different struct). What I can do to avoid possible errors in the future is check that the gpu count given as input to scatter does not exceed the active gpu count used to create the lut. 
> chore(gpu): enhance scatter to check gpu count is ok

- Makefile
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/polynomial/dot_product.cuh
Fix the warnings detector - the previous pattern was only detecting some warnings. 
Also fixes some unused variable warnings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2615)
> chore(gpu): fix warnings detection

- tfhe-benchmark/benches/integer/zk_pke.rs
To be parsable each benchmark criterion ID must have their crypto details written to a file.
> chore(bench): write params to file for each zk benchmark on gpu

- tfhe-benchmark/src/utilities.rs
- tfhe/src/shortint/parameters/ks32.rs
- tfhe/src/shortint/parameters/mod.rs
pfail in bench metadata was hardcoded to 2^-41, this uses the correct pfail from the parameters
> fix(bench): store correct pfail from params

- .github/workflows/make_release_cuda.yml
- .github/workflows/make_release_hpu.yml
- .github/workflows/make_release_tfhe_csprng.yml
- .github/workflows/make_release_tfhe_fft.yml
- .github/workflows/make_release_tfhe_ntt.yml
- .github/workflows/make_release_tfhe_versionable.yml
- .github/workflows/make_release_zk_pok.yml
Only tfhe crate was using crates.io trusted publishing feature. This commit ensure all other tfhe-rs crates are using this secure publishing method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2655)
> chore(ci): deploy trusted publishing usage to all remaining crates

- tfhe-benchmark/src/utilities.rs
This is done to measure execution time on FheBool equivalent on all operations.
> chore(bench): add 2 bits integer to full benchmarks

- tfhe-zk-pok/Cargo.toml
- tfhe-zk-pok/src/curve_api/bls12_446.rs
- tfhe/Cargo.toml
add ZeroizeZp type that is automatically zeroized on drop by deriving ZeroizeOnDrop. The tradeoff is that this type is not Copy.
This can be used to remove "toxic waste" secret data after they are used. This is a need for the kms crs generation.
Zp already derives Zeroize but is also Copy. This means that the user must manually track and zeroize all copies, which is error prone.
ZeroizeOnDrop is not a silver bullet and is not a guarantee that memory won't be present in memory. In particular:
- "moves" create memory copies, so data must be passed by reference
- ZeroizeZp is still a wrapper of a type from arkworks, so upstream code might create copies
- the compiler is still free to create copies, for example through register spills. In the end …
> feat(zk): add ZeroizeZp type that is automatically zeroized on drop

- .github/workflows/make_release.yml
- .github/workflows/make_release_cuda.yml
- .github/workflows/make_release_hpu.yml
- .github/workflows/make_release_tfhe_csprng.yml
- .github/workflows/make_release_tfhe_fft.yml
- .github/workflows/make_release_tfhe_ntt.yml
- .github/workflows/make_release_tfhe_versionable.yml
- .github/workflows/make_release_zk_pok.yml
When using crates.io trusted publishing feature GitHub token `id-token: write` permission to be able to authenticate the workflow on the registry.
> chore(ci): add permission to github token to release crates

- tfhe/src/high_level_api/compact_list.rs
- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/high_level_api/compressed_noise_squashed_ciphertext_list.rs
- tfhe/src/high_level_api/strings/ascii/mod.rs
- tfhe/src/integer/backward_compatibility/ciphertext/mod.rs
- tfhe/src/integer/ciphertext/compact_list.rs
- tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/ciphertext/compressed_noise_squashed_ciphertext_list.rs
- tfhe/src/integer/ciphertext/utils.rs
- tfhe/src/integer/gpu/ciphertext/compact_list.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/zk/mod.rs
- tfhe/src/shortint/ciphertext/compact_list.rs
- tfhe/src/strings/ciphertext.rs
- tfhe/src/zk/mod.rs
- utils/tfhe-versionable/src/lib.rs
Change the type used to store a block count in
DataKind to NonZero. This makes it impossible to store
'empty' kinds such as DataKind::Unsigned(0), DataKind::Signed(0).
Also, when deserializing, if the count is zero and error will be
returned, adding an additional layer of sanitization.
> refactor!: Use NonZero<T> in DataKind 

- tfhe/src/core_crypto/entities/lwe_ciphertext.rs
- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/high_level_api/keys/inner.rs
- tfhe/src/high_level_api/keys/server.rs
- tfhe/src/integer/ciphertext/compressed_noise_squashed_ciphertext_list.rs
- tfhe/src/integer/noise_squashing/keys.rs
- linked to new lints/warnings for elided lifetimes our old nightly toolchain does not know about
> chore: fix some warnings appearing during compilation with 1.89

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
it was missing the release of the carry propagation struct
> fix(gpu): fix memory leak in count consecutive bits

- .github/workflows/coprocessor-benchmark-gpu.yml
Adds the coprocessor benchmarks in tfhe-rs GPU CI
- uploads latency and throughput of erc20 to grafana
- runs `nsys` profiling and uploads the report in an artifact
Closes https://github.com/zama-ai/tfhe-rs-internal/issues/1068
Closes https://github.com/zama-ai/tfhe-rs-internal/issues/1049
> chore(gpu): add coprocessor benchmarks in tfhe-rs gpu ci

- .github/workflows/gpu_fast_tests.yml
- .github/workflows/gpu_memory_sanitizer.yml
- Makefile
- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/abs.cu
- backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cu
- backends/tfhe-cuda-backend/cuda/src/integer/cast.cu
- backends/tfhe-cuda-backend/cuda/src/integer/cmux.cu
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
- backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cu
- backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cu
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
- backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cu
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cu
- backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cu
- backends/tfhe-cuda-backend/cuda/src/integer/subtraction.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
- backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit_128.cu
- backends/tfhe-cuda-backend/cuda/src/zk/zk.cu
- scripts/check_memory_errors.sh
Adds valgrind to catch mem leak in the debug build workflow
Memory checks CI runs every 3 months and can be run manually
Closes https://github.com/zama-ai/tfhe-rs-internal/issues/1053
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2612)
> chore(gpu): add valgrind in debug workflow

- Makefile
We've been seeing OOM errors in the 4090 tests for a while (I think it's because I removed the anticipated buffer drop in scalar mul). I'm reducing the number of test threads for these tests and it fixes it (I've checked in an action run already).
> chore(gpu): fix oom in 4090 tests

- tfhe/src/core_crypto/fft_impl/fft128/crypto/ggsw.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/1101
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2697)
> chore(core): size checks in Fourier128GgswCiphertext::from_container

- tfhe-zk-pok/src/four_squares.rs
- tfhe-zk-pok/src/proofs/mod.rs
- tfhe-zk-pok/src/proofs/pke_v2/mod.rs
Fix issue with limit cases in the four_square algorithm. Before this pr, the algorithm would panic/overflow if `v = 2*4^n` (for any n) and run into an infinite loop if `v = k*4^n with k in [6, 10, 14, 22, 34, 38, 110]`.
Added a test to check these limit values
> fix(zk): handle limit cases in the four_squares algorithm

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
- backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
The idea is to avoid synchronizaton in the comparison algo that uses streams.
host memory is preallocated in the mem structure and then used when generating the lut inside the integer operation.
> feat(gpu): enable lut generation with preallocated buffers

- tfhe-benchmark/src/utilities.rs
GPU backend cannot accept less than 2 blocks for integer benchmarks. Since 2-bits precision benchmarks are run with *_MESSAGE_2_CARRY_2_* parameters, it will create only one block of ciphertext, thus making the benchmarks unsuitable for GPU backend.
> chore(bench): remove 2-bits size for full precision bench on gpu

- tfhe/docs/configuration/gpu-acceleration/noise-squashing.md
- tfhe/src/test_user_docs.rs
> doc(gpu): add a section about noise squashing

- Makefile
We're getting out of memory in doc tests because we're not restraining the number of test threads used on 4090.
> chore(gpu): reduce test threads for 4090 doc tests

- .cargo/audit.toml
- .github/workflows/cargo_audit.yml
- Makefile
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/1132
Not sure if this is really needed with dependabot, but it is fast and we can run it locally if we want.
I ignored the warning about paste being unmaintained because:
- paste is not considered broken but "finished" by its author
- alternatives are from lesser known authors, switch to an alternative would be more risky security wise
- it would be complicated to remove it, and it is also used by some of our dependencies anyway
I could also have left the warnings about unmaintained as "non deny" but this way at least we have to be explicit about if we accept the risk or not on a case by case basis. This can be changed later if it becomes too tedious.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> chore(ci): run cargo audit

- tfhe-benchmark/benches/integer/zk_pke.rs
This is done get more details about the benchmarks when parsing results.
> chore(bench): add crs size in zk-pke benchmark names

- .github/workflows/sync_on_push.yml
This is done to better handle git-lfs related changes when syncing with another repository.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2777)
> chore(ci): perform sync on push without third-party action

- backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
- tfhe-benchmark/src/utilities.rs
> fix(gpu): avoid out of memory when benchmarking throughput

- utils/tfhe-versionable-derive/src/associated.rs
- utils/tfhe-versionable-derive/src/lib.rs
closes: https://github.com/zama-ai/tfhe-rs-internal/issues/1137
This avoids name clashes with user re-defined types.
For example before this PR doing this in tfhe-rs would not compile:
```rust
use crate::Result;
#[derive(Versionize)]
#[versionize(MyTypeVersions)]
struct MyType {
// ...
}
```
> fix(versionable): use full type path in proc macro

- backends/tfhe-cuda-backend/Cargo.toml
- tfhe/Cargo.toml
> chore: bump tfhe-cuda-backend to 0.12.0-alpha.0

- backends/tfhe-cuda-backend/Cargo.toml
- tfhe/Cargo.toml
- bump tfhe-cuda-backend to 0.12.0-alpha.2
- bump tfhe to 1.4.0-alpha.2
> chore: prepare alpha.2

- tfhe/src/high_level_api/compressed_ciphertext_list.rs
- tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
- tfhe/src/integer/gpu/list_compression/server_keys.rs
In get_decompression_size_on_gpu, we used to do:
```
self.inner.on_gpu(streams).get_decompression_size_on_gpu(
index,
decompression_key,
streams,
```
The problem is that calling `on_gpu()` allocates and copies data to the GPU. 
It shouldn't be necessary to do this only to query decompression size. 
Also, this means the allocated GPU variable gets dropped at the end of `get_decompression_size_on_gpu` which means a
`cuda_device_synchronize` gets called, and this affects performance in the coprocessor.
This PR introduces an entry point for `get_decompression_size_on_gpu` when the input is on the CPU, using the CPU metadata to compute the size directly.
[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-descript …
> chore(gpu): get decompress size on gpu without calling on_gpu

- .github/workflows/benchmark_core_crypto.yml
Classical or multi-bit or both parameters type can be now run on CPU core_crypto benchmarks at user discretion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zama-ai/tfhe-rs/2853)
> chore(ci): enable multi-bit parameters for core_crypto benchmarks
